artichoke/artichoke

Cargo.lock, mruby-sys/Cargo.toml, mruby-sys/build.rs, mruby-sys/src/ffi.rs
This pulls in the fix for rust-lang/rust-bindgen#1589 which unblocks
enabling layout tests for mruby-sys.
=> Upgrade bindgen to 0.51.0

artichoke-wasm/src/index.html
All Strings consumed by the interpreter need to be owned by Rust. The Wasm
frontend returns 'pointers' to Strings in a 'heap' (HashMap) and exposes
an API for finding the length of the String behind a pointer and reading
and writing characters from and into the String.
JS copies code into the heap and copies results out of the heap. Once this
eval and result extract is done, the Rust copies of the Strings are no longer
required. Currently, these Strings leak. This PR explicitly frees the Strings
from the heap which will let them be reclaimed by Rust.
=> Free Strings from Rust heap after evaling Ruby

artichoke-wasm/src/index.html, artichoke-wasm/src/playground.js, artichoke-wasm/src/string.rs
Properly encode/decode between Rust UTF-8 String and JavaScript UCS-2 String.
Modify String heap to be backed by a `Vec<u8>`.
Move playground runtime out of `index.html` into `playground.js`.
=> Support non-ascii strings in Wasm frontend

artichoke-wasm/src/main.rs
Fix a crash in Mobile Safari caused by an out of memory error.
=> Limit total memory in Wasm build to 5MiB

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-backend/README.md, artichoke-backend/src/extn/core/kernel/require.rs, artichoke-backend/src/fs/abs.rs, artichoke-backend/src/fs/mod.rs, artichoke-vfs/README.md, mruby-sys/README.md
path_abs does not compile under wasm32-unknown-unknown because it
includes conditional compilation on OS vendor targeting unix and
windows. Artichoke does not make use of this functionality.
path_abs canonicalizes relative paths using env::current_dir. Artichoke
uses a virtual filesystem so this behavior is never what we want.
This commit removes the dependency on path_abs and replaces it with a
vendored copy of the PathAbs implementation. This fork modifies the
public API of PathAbs::new to take the "canonicalized" current working
directory to use for absolutizing relative paths.
Tests from upstream are included.
This commit forks path_abs from commit https://github.com/vitiral/path_abs/tree/8370838b6110786c2ba7cf7fd984a4783f37701c.
=> Vendor and fork path_abs::PathAbs

README.md, artichoke-backend/src/extn/core/mod.rs, artichoke-backend/src/extn/core/regexp/opts.rs, artichoke-backend/src/extn/core/string.rs, artichoke-backend/src/extn/stdlib/json.rb, artichoke-wasm/src/index.html, artichoke-wasm/src/main.rs, artichoke-wasm/src/playground.js, scripts/format-text.sh
Works around a link failure under emscripten.
Updates the prepopulated example to use JSON and Regexp.
Fixes GH-48.
=> Enable Regexp in Wasm build

.circleci/config.yml, scripts/lint.sh
Followup to GH-85. cc @johnwahba
=> Enable CircleCI to lint Ruby scripts

Cargo.lock, Cargo.toml, README.md, artichoke-core/Cargo.toml, artichoke-core/README.md, artichoke-core/src/convert.rs, artichoke-core/src/def.rs, artichoke-core/src/eval.rs, artichoke-core/src/exception.rs, artichoke-core/src/file.rs, artichoke-core/src/lib.rs, artichoke-core/src/load.rs, artichoke-core/src/state.rs, artichoke-core/src/symbol.rs, artichoke-core/src/top_self.rs, artichoke-core/src/types.rs, artichoke-core/src/value.rs, artichoke-core/src/warn.rs, artichoke-wasm/src/index.html
This is an experimental branch to split apart `mruby` crate into a core and several backend implementations.
I do not intend to merge this branch, but will pull learnings from it back into `master`.
Changes so far in this branch:
- `Value` is a trait.
- `class:Spec` and `module::Spec` unified under a `ClassLike` trait object.
- Simplified `Method` definition.
- Converters are generic over interpreter.
- Added `Nil` trait so interpreters can provide a `nil` `Value`.
- Removed `Mrb` prefix from all trait definitions.
=> Extract artichoke core

artichoke-backend/src/extn/core/matchdata/begin.rs, artichoke-backend/src/extn/core/matchdata/captures.rs, artichoke-backend/src/extn/core/matchdata/element_reference.rs, artichoke-backend/src/extn/core/matchdata/end.rs, artichoke-backend/src/extn/core/matchdata/length.rs, artichoke-backend/src/extn/core/matchdata/mod.rs, artichoke-backend/src/extn/core/matchdata/named_captures.rs, artichoke-backend/src/extn/core/matchdata/names.rs, artichoke-backend/src/extn/core/matchdata/offset.rs, artichoke-backend/src/extn/core/matchdata/to_a.rs, artichoke-backend/src/extn/core/matchdata/to_s.rs, artichoke-backend/src/extn/core/regexp/case_compare.rs, artichoke-backend/src/extn/core/regexp/match_.rs, artichoke-backend/src/extn/core/regexp/match_operator.rs, artichoke-backend/src/extn/core/regexp/match_q.rs, artichoke-backend/src/extn/core/regexp/mod.rs, artichoke-backend/src/extn/core/regexp/named_captures.rs, artichoke-backend/src/extn/core/regexp/names.rs, artichoke-backend/src/extn/core/string/scan.rs
To prepare to implement GH-57.
Introduce a `Backend` enum which will allow the `Regexp` implementation to toggle between the `onig` and `regex` implementations.
=> Add support for multiple Regexp backend implementations

README.md
Reflect that a Wasm build exists, it's just only runnable on the web.
=> Update Wasm build status in README

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-backend/src/extn/core/matchdata/begin.rs, artichoke-backend/src/extn/core/matchdata/captures.rs, artichoke-backend/src/extn/core/matchdata/element_reference.rs, artichoke-backend/src/extn/core/matchdata/end.rs, artichoke-backend/src/extn/core/matchdata/length.rs, artichoke-backend/src/extn/core/matchdata/mod.rs, artichoke-backend/src/extn/core/matchdata/named_captures.rs, artichoke-backend/src/extn/core/matchdata/names.rs, artichoke-backend/src/extn/core/matchdata/offset.rs, artichoke-backend/src/extn/core/matchdata/to_a.rs, artichoke-backend/src/extn/core/matchdata/to_s.rs, artichoke-backend/src/extn/core/regexp/case_compare.rs, artichoke-backend/src/extn/core/regexp/match_.rs, artichoke-backend/src/extn/core/regexp/match_operator.rs, artichoke-backend/src/extn/core/regexp/match_q.rs, artichoke-backend/src/extn/core/regexp/mod.rs, artichoke-backend/src/extn/core/regexp/named_captures.rs, artichoke-backend/src/extn/core/regexp/names.rs, artichoke-backend/src/extn/core/string/scan.rs
This PR adds a new entry to the `regexp::Backend` enum which uses the Rust regex crate.
regex crate is a regex engine implemented with an FSM. For some cases, it is _much_ faster than oniguruma, but it does not support all features that Ruby `Regexp`s must have, like lookahead and backreferences.
Artichoke now supports choosing between multiple Regexp backends. Right now, the regex crate backend is a set of unimplemented stubs, but this lays the groundwork for implementing support for both engines.
This PR is in support of GH-57.
=> Add scaffolding to support Regexp backed by Rust regex crate

artichoke-backend/build.rs, artichoke-backend/scripts/.rubocop.yml, artichoke-backend/scripts/auto_import/auto_import.rb, artichoke-backend/scripts/auto_import/get_constants_loaded.rb, artichoke-backend/scripts/auto_import/get_package_files.rb, artichoke-backend/scripts/auto_import/rust_glue.rs.erb
Followup to GH-117. cc @johnwahba.
- Cleanup dead code in `build.rs`.
- implement commands with Ruby directly instead of redirecting through bash.
- The `-I` flag no longer exists in MRI. Sorry @johnwahba I led you astray.
- Simulate the `-I` flag by passing around the vendored base path and manipulating `$LOAD_PATH`.
- Dump stderr on command failures in `build.rs`.
- add missing rubocop config to `artichoke-backend/scripts`.
- Generated rust sources reference files through `OUT_DIR`.
- Add support for multi-source packages.
=> Fixups to auto import build step

README.md
Link to `CONTRIBUTING.md#rust-toolchain`.
=> Fix a broken link to toolchain setup in README

webpack.config.js
By default, webpack outputs to `main.js` which conflicts with the JS generated by rustdoc.
The CircleCI build blindly copies generated webpack sources into the doc root.
This PR changes the webpack config to use generated hashes for JS and CSS filenames.
=> Rename generated webpack outputs so they do not conflict with rustdoc

.circleci/config.yml, CONTRIBUTING.md, Cargo.lock, mruby-sys/Cargo.toml, mruby-sys/bootstrap.gembox, mruby-sys/build.rs, mruby-sys/build_config.rb
Modify mruby-sys build to use the `cc` crate to compile one static library called `libmrubysys.a`.
Compiling with `cc` crate makes it easier to compile a wasm32-unknown-unknown build. We still can't do that because of `onig`.
To accomplish this, the `host` build now compiles the bare minimum of mruby to bootstrap the `sys` build. Until GH-32 is complete, mruby-sys depends on gems with Ruby sources. These Ruby sources get translated to bytecode embedded in C sources using the `mrbc` binary. The `host` build produces this binary.
The `sys` build only generates C sources using `minirake` by replacing compiler commands with `true`. `build.rs` the collects all of the headers and sources and compiles them with `cc` crate.
Adds docs for GH-137. `cc` is required to build. By default, that is …
=> Use cc crate to build mruby-sys static library

artichoke-backend/src/extn/core/env/backends.rs, artichoke-backend/src/extn/core/env/env_object.rs, artichoke-backend/src/extn/core/env/errors.rs, artichoke-backend/src/extn/core/env/mod.rs
ENV object: Follow up from GH-148.
- Modify backend trait to return Result with Env Error.
- Make env module Error into an Error type.
- Handle null byte in env::var_os (fixes segfaulting test introduced in
previous commit).
- Return Error::Fatal instead of unwrapping, e.g. HashMap backend with
RwLock.
- Move arg validation into backend implementation.
- Move calls to raise into C API to work prevent memory leaks with
longjmp.
- get set and to_h internal return Value instead of sys::mrb_value.
```
mruby 2.0 [2.0.1-12]
[Compiled with rustc 1.38.0-nightly 6e310f2 2019-07-07]
>>> ENV["as\0"]
Backtrace:
(airb):1: bad environment variable name: contains null byte (ArgumentError)
(airb):1
>>> ENV["as\0"] = "a"
Backtrace:
(airb):2: bad environment variable name: contains null byte …
```
=> Env followup

artichoke-backend/src/extn/core/array.rs, artichoke-backend/src/extn/core/env/env_object.rs, artichoke-backend/src/extn/core/env/mod.rs, artichoke-backend/src/extn/core/error.rs, artichoke-backend/src/extn/core/hash.rs, artichoke-backend/src/extn/core/kernel/mod.rs, artichoke-backend/src/extn/core/mod.rs, artichoke-backend/src/extn/core/module.rs, artichoke-backend/src/extn/core/string.rs, artichoke-backend/src/extn/mod.rs, artichoke-backend/src/extn/stdlib/mod.rs, artichoke-backend/src/extn/stdlib/stubs.rs, artichoke-backend/src/interpreter.rs
`patch` is an artifact of basing extn initially on mruby. The goal is to
be able to initialize extn from scratch, so we won't be patching from a
base, but rather initializing from nothing.
=> Rename patch functions to init in artichoke-backend extn

.circleci/config.yml, CONTRIBUTING.md, mruby-sys/build_config.rb
I think the build flakiness started when we switched back to gcc for the bootstrap
build. Maybe something to do with the buster upgrade?
Either way, cc crate already requires clang so it makes sense to unify things.
=> Fix mruby-sys build flakiness when compiling mruby-compiler mrbgem

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-backend/src/extn/core/matchdata/begin.rs, artichoke-backend/src/extn/core/matchdata/element_reference.rs, artichoke-backend/src/extn/core/matchdata/end.rs, artichoke-backend/src/extn/core/matchdata/named_captures.rs, artichoke-backend/src/extn/core/matchdata/names.rs, artichoke-backend/src/extn/core/matchdata/offset.rs, artichoke-backend/src/extn/core/regexp/named_captures.rs, artichoke-backend/src/extn/core/regexp/names.rs
onig 5.0 uses bindgen to generate bindings for oniguruma and is easier
to hack on. To upstream the changes in GH-172 that add
wasm32-unknown-unknown support to Artichoke, we need to build with onig
5.0.
In addition to updating the dependency, this commit updates the `Regexp`
and `MatchData` implementations to work with the new APIs exposed by
onig.
The only change is the removal of `Regex::capture_names` and the
addition of the `Regex::foreach_name` function that replaces it. This
changes the API from an iterator to a callback with a break parameter.
This change appears to be a result of upstream changes in oniguruma.
This commit does not include any of the wasm support present in our
fork: https://github.com/artichoke/rust-onig/tree/wasm3. This means that
once this commit is merged, …
=> Update to onig 5.0

artichoke-backend/src/extn/core/enumerable/enumerable.rb
Thanks @isbear for pointing this out.
This made it through because we're not yet running the enumerable tests.
=> Fix missing rename from h to groups

.circleci/config.yml
=> Sets the circleci rust toolchain build image to 1.37.0-buster

artichoke-backend/src/class.rs, artichoke-backend/src/extn/core/error.rs, artichoke-backend/src/extn/core/integer/integer.rb, artichoke-backend/src/extn/core/integer/mod.rs, artichoke-backend/src/extn/core/mod.rs
Fixes GH-186.
This PR adds support for `Integer#chr` when called with no argument. `Integer#chr` with no argument requires that `self` convert to a `u8` and creates a `String` with a single byte `Vec<u8>`.
=> Implement Integer#chr in Rust

artichoke-backend/src/module.rs
Make the same change as a4ffbe38, but for module.rs.
Following Matz's recommendation in https://github.com/mruby/mruby/issues/4660
=> Don't define existing Modules if they already exist on the mruby VM

artichoke-backend/src/extn/core/integer/mod.rs
This PR implements `Integer#size` in Rust.
Fixes #179 
Ran the tests (integer/size_spec.rb), only passed for the fixnum's not the bignum's.
=> Impl. Integer#size in Rust

spec-runner/vendor/mspec/lib/mspec/guards/platform.rb
Revendor artichoke/mspec@2f8d060
GH-212 implements `Integer#size` which allows us to remove a patch we carry in mspec.
See https://github.com/artichoke/mspec/issues/1.
=> Revendor artichoke/mspec@2f8d060

artichoke-backend/src/extn/core/integer/mod.rs, artichoke-backend/src/extn/core/symbol/symbol.rb
Followup to GH-218.
Implement the complete `Symbol` API in Ruby. The only remaining pieces implemented in C are:
- `Symbol::all_symbols`
- `Symbol#id2name`
- `Symbol#to_s`
- `Symbol#inspect`
This PR cleans up some of the Unicode handling in `casecmp` and delegates to `String` wherever possible.
cc @tkbky
=> Implement more methods on Symbol in Ruby

Cargo.lock, mruby-sys/Cargo.toml, mruby-sys/build.rs
@tkbky and @lopopolo had a discussion in GH-217 about whether some mrbgems could be removed from the build.
The set of gems in the build was chosen for [artichoke/ferrocarril](https://github.com/artichoke/ferrocarril) which targets running Sinatra.
Our goals in Artichoke are to pass the specs we have implemented. Incompleteness in the Ruby core implementation is acceptable.
This PR removes the following gems for the build and gives their tracking tickets:
- mruby-math => GH-222
- mruby-time => GH-33
- mruby-struct => GH-223
- mruby-random => GH-34
=> Purge mrbgems

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-frontend/Cargo.toml, artichoke-vfs/Cargo.toml, spec-runner/Cargo.toml
Update all deps to latest.
Bumped semver incompatible for:
- rust-embed
- rustyline
- rand
- quickcheck
=> Cargo deps upgrade

README.md, doc/artichoke-design-and-goals.md
- Pull call to action and playround above the fold.
- Move detailed description of design and goals to `doc/`.
- Link to design and goals from README.
- Include top-5 project goals in README.
- Inclue top-5 project goals in design and goals doc.
cc @tummychow
=> Improve focus of README

artichoke-backend/src/extn/core/kernel/kernel.rb
This API and constant were added in artichoke/ferrocarril#85 to load Sinatra and
work around mruby not supporting expressions as default parameters in method argument
lists.
This patch belongs in nemesis instead of artichoke core.
=> Remove Kernel::NOT_SET and Kernel#not_set?

artichoke-backend/src/convert/fixnum.rs
This converter is not compiled as part of the artichoke build pipeline
and it got missed in GH-242.
=> Fix wasm32 i64 converter compiler error

artichoke-backend/src/convert/object.rs, artichoke-backend/src/exception.rs, artichoke-backend/src/extn/core/kernel/mod.rs, artichoke-backend/src/extn/core/matchdata/begin.rs, artichoke-backend/src/extn/core/matchdata/end.rs, artichoke-backend/src/extn/core/regexp/union.rs, artichoke-backend/src/extn/core/string.rs, artichoke-backend/src/extn/core/string/scan.rs, artichoke-backend/src/value.rs, artichoke-backend/src/warn.rs, artichoke-backend/tests/leak_funcall.rs, spec-runner/src/mspec.rs
Unify funcall and funcall_with_block into ValueLike::funcall that takes
an optional block.
This commit is made possible by and is a follow up to GH-248. This
commit is a prerequisite to implementing Value in artichoke-backend with
the Value trait in artichoke-core.
Simplify the signature of funcall to remove AsRef generics. The method is
now always an &str and the args always a &[Value].
This commit updates every funcall callsite in Artichoke. Update converted
return type to use &str converters to avoid allocations where possible.
=> Unify ValueLike::funcall and ValueLike::funcall_with_block

artichoke-backend/Cargo.toml, artichoke-backend/src/convert/object.rs, artichoke-backend/src/eval.rs, artichoke-backend/src/exception.rs, artichoke-backend/src/extn/core/comparable/mod.rs, artichoke-backend/src/extn/core/env/mod.rs, artichoke-backend/src/extn/core/error.rs, artichoke-backend/src/extn/core/integer/mod.rs, artichoke-backend/src/extn/core/kernel/mod.rs, artichoke-backend/src/extn/core/kernel/require.rs, artichoke-backend/src/extn/core/string.rs, artichoke-backend/src/ffi.rs, artichoke-backend/src/interpreter.rs, artichoke-backend/src/lib.rs, artichoke-backend/src/load.rs, artichoke-backend/src/value.rs, artichoke-backend/src/warn.rs
- Relax log dep to `0.4`.
- Import macros globally with `macro_use` + `extern crate log`.
- Remove explicit macro imports.
This makes it easier to log in `artichoke-backend`.
=> Improve log ergonomics in artichoke-backend

artichoke-backend/src/extn/core/error.rs, artichoke-backend/src/extn/core/string.rb, scripts/spec-compliance.sh
Prep to make GH-268 easier.
- Include all shared setups when running specs, not just the ones in the target class.
- Add `Encoding` stub to get `ENV` specs to load.
- Add docs for Ruby `Exception` hierarchy.
The `Exception` docs will come in handy because `ENV` requires an implementation of `Errno::EINVAL`.
=> Prepare for adding ENV to spec-compliance.sh

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-backend/build.rs, artichoke-backend/src/extn/mod.rs, artichoke-frontend/Cargo.toml, artichoke-frontend/src/repl.rs
Add the following constants to the VM when initializing `extn`:
```ruby
RUBY_COPYRIGHT
RUBY_DESCRIPTION
RUBY_ENGINE
RUBY_ENGINE_VERSION
RUBY_PATCHLEVEL
RUBY_PLATFORM
RUBY_RELEASE_DATE
RUBY_REVISION
RUBY_VERSION
```
Also add these Artichoke-specific constants:
```ruby
ARTICHOKE_COMPILER_VERSION
```
These constants are generated at compile time in `build.rs`.
TODO: include backend type in `RUBY_ENGINE_VERSION`.
=> Add RUBY_* global constants

artichoke-core/src/file.rs, artichoke-core/src/load.rs
Tweaks to the signatures of `File` and `Load` traits to make them easier to use in `artichoke-backend`.
Porting artichoke-backend to use these traits will require some surgery because removing the `AsRef<[u8]>` type parameter for file contents is a breaking change. We use `include_string` _a lot_ where we should be using `include_bytes(...).as_ref()`.
One use is the auto import stdlib generator:
https://github.com/artichoke/artichoke/blob/ede8269e156eb6a469f098fb2d033d40ce8fac48/artichoke-backend/scripts/auto_import/rust_glue.rs.erb#L22-L25
The new API is more correct and allows _all_ permissible sources to be loaded by forcing the caller to deal in bytes.
=> Prepare File and Load traits in artichoke-core for use in artichoke-backend

artichoke-backend/build.rs
- dbm
- gdbm
- zlib
These packages are implemented in native code so the auto import script is a no-op.
dbm and gdbm are not compiled into Ruby in some cases on Linux.
Fixes GH-206.
=> Disable building Rust stubs for some Ruby stdlib packages

.circleci/config.yml, package.json, scripts/spec-compliance.sh, spec-runner/src/spec_runner.rb
Instead of forking for every spec, register the files in a bash array
and invoke the spec-runner once with the collected specs.
Tweak the spec-runner to enable running the passing specs with MRI.
MRI runs 5x faster than Artichoke to run the passing specs.
=> Improve performance of spec-compliance.sh script

artichoke-backend/build.rs
Required to update artichoke dependency in playground.
=> Properly resolve emscripten headers and include them for all Wasm targets

artichoke-backend/src/extn/mod.rs, artichoke-backend/src/interpreter.rs
Fixes https://github.com/artichoke/artichoke/issues/273
Is this about what we'd like for this issue? Maybe stash "mruby" into a static?
=> include backend name in RUBY_VERSION

artichoke-backend/src/value.rs, artichoke-core/src/value.rs
Fixes https://github.com/artichoke/artichoke/issues/249 . Is this the intended behavior for `unchecked_funcall`?
=> adds unchecked_funcall

Cargo.lock, artichoke-frontend/Cargo.toml, artichoke-frontend/src/bin/airb.rs, artichoke-frontend/src/bin/artichoke.rs, artichoke-frontend/src/bin/ruby.rs, artichoke-frontend/src/repl.rs
These binaries are identical (ruby.rs is a symlink to artichoke.rs).
Currently supported flags:
--copyright for printing RUBY_COPYRIGHT
-e for inline eval (including multiple -e flags)
programfile for loading programs from the host filesystem
reading program input from STDIN
These binaries are useful for benchmarking Artichoke using the shell
in the absence of a Time Core implementation.
This commit makes progress on GH-17.
=> Add artichoke and ruby binaries to artichoke-frontend

artichoke-backend/src/extn/core/string.rs, artichoke-backend/src/extn/core/string/scan.rs
The existing implementation of String#scan always delegated to regexp, even for
fixed patterns. This patch implements scanning for literal byte slices using
the Rust memchr crate. memchr is a vectorized scanner which is blisteringly fast.
Artichoke always uses memchr for literal patterns with length > 0, and further
optimizes for length == 1 case by directly consuming an iterator.
Compared to MRI, Artichoke's implementation of String#scan with literal String
patterns is approx. 3x faster.
=> Optimize String#scan for literal String patterns

artichoke-backend/src/extn/core/string/scan.rs, scripts/spec-compliance.sh
- proper handling of `Regexp` globals
- proper setting of `MatchData` with a clone per block iteration.
- Optimizations for deferring `MatchData` creation for `String` patterns.
=> Make String#scan implementation pass ruby/spec

artichoke-backend/src/exception.rs, artichoke-backend/src/extn/core/array/backend/aggregate.rs, artichoke-backend/src/extn/core/array/backend/buffer.rs, artichoke-backend/src/extn/core/array/backend/fixed/empty.rs, artichoke-backend/src/extn/core/array/backend/fixed/hole.rs, artichoke-backend/src/extn/core/array/backend/fixed/one.rs, artichoke-backend/src/extn/core/array/backend/fixed/two.rs, artichoke-backend/src/extn/core/array/backend/repeated/value.rs, artichoke-backend/src/extn/core/array/mod.rs
I sometimes add an `!#[allow(warnings)]` pragma when iterating on code and it looks like I forgot to remove these.
=> Remove warning silencers and fixup warnings in array and exception modules

.circleci/config.yml, artichoke-backend/src/extn/core/array/mod.rs, artichoke-backend/src/extn/core/array/mruby.rs, artichoke-backend/src/extn/core/array/trampoline.rs, artichoke-backend/src/extn/core/regexp/match_.rs, artichoke-backend/src/extn/core/regexp/mod.rs, artichoke-backend/src/extn/core/string.rs, artichoke-backend/src/extn/core/string/scan.rs, artichoke-backend/src/macros.rs, artichoke-backend/src/value.rs
The entire suite of `Array` specs is runnable with:
```shell
./scripts/run-spec.sh core array
```
The previous `VecDeque` implementation of `Array` was able to run the specs to completion and had the following pass rate:
```
Passed 654, skipped 116, not implemented 99, failed 345 specs.
```
The class cluster implementation was not able to run the specs to completion:
- Improperly calling `block.funcall("call")` instead of using `mrb_yield` caused segfaults.
- Some methods on `Array` required a mutable borrow _and_ call back into the VM to parse arguments. These funcalls can trigger GC runs. Marking `Array`s requires a shared borrow, which panics.
The fixes are:
- Introduce a `Block` type that properly (and only) implements `yield`.
- Modify `mrb_get_args!` macro to extract block arguments …
=> Fix segfault and borrow errors when running the entire Array spec suite

.circleci/config.yml, artichoke-backend/Cargo.toml, artichoke-backend/build.rs, artichoke-backend/mruby-sys/include/mruby-sys.h, artichoke-backend/mruby-sys/include/mruby-sys/artichoke.h, artichoke-backend/mruby-sys/include/mruby-sys/ext.h, artichoke-backend/mruby-sys/src/mruby-sys/ext.c, artichoke-backend/src/convert/array.rs, artichoke-backend/src/convert/hash.rs, artichoke-backend/src/extn/core/array/mruby.rs, artichoke-backend/src/extn/core/artichoke/mod.rs, artichoke-backend/src/extn/core/env/mruby.rs, artichoke-backend/src/extn/core/exception/mod.rs, artichoke-backend/src/extn/core/integer/mod.rs, artichoke-backend/src/extn/core/kernel/mod.rs, artichoke-backend/src/extn/core/mod.rs, artichoke-backend/src/extn/core/regexp/union.rs, artichoke-backend/src/extn/core/string.rs, artichoke-backend/src/value.rs
An assortment of changes that will make it easier to bump the playground to the latest master.
- Add a `artichoke-array` feature, enabled by default, that controls whether `artichoke-backend` builds without `RArray`.
- Changes to headers in `mruby-sys` C extension for clarity.
- Set `EMSCRIPTEN_KEEPALIVE` macro in `artichoke-backend` build script for wasm32-unknown-emscripten target.
- Define `Artichoke` module explicitly in Rust rather than implicitly through `array.rb`.
- Stop swallowing errors during init by squashing into `ArtichokeError::New`.
=> Rollout to playground

artichoke-backend/src/convert/object.rs, artichoke-backend/src/extn/core/regexp/mod.rs
There is a better API than mrb_obj_new for allocating MRB_TT_DATA objects
called mrb_data_object_alloc which allows to directly inject a data pointer
and avoid going through the object's initialize method.
Prior to this change, every Array serialization to Ruby from Rust resulted
in _two_ arrays being allocated _and_ the first being leaked.
This commit removes the gross workaround for passing arguments to the
Regexp constructor in the Regexp impl of RustBackedObject.
=> Avoid double allocation of MRB_TT_DATA objects

artichoke-backend/src/convert/object.rs, artichoke-backend/src/def.rs, artichoke-backend/src/extn/core/array/backend/buffer.rs, artichoke-backend/src/extn/core/array/mod.rs, artichoke-backend/src/extn/core/array/mruby.rs, artichoke-backend/src/extn/core/array/trampoline.rs
While investigating the segfaults in GH-327, I encountered several bits of suboptimal code.
This PR is several small refactorings to improve code quality.
- Refactor `RustBackedValue::try_from_ruby` for readability, remove duplicated conditionals, and panic when encountering null pointers.
- Panic in `rust_data_free::<T>` when encountering a null pointer.
- Use `Vec::from` or `Iterator::collect` where possible in `Buffer`.
- Downcast to `Buffer` for some mutable operations in `Buffer` to minimize allocations and method calls.
- Use an in place swap to handle single-part reallocs in `Array`.
- Delete unused and semantically confusing function `Array::initialize_copy`.
- Clean up the last remaining Array mruby trampoline functions that passed arguments by reference.
=> Code quality improvements

artichoke-backend/src/extn/core/array/backend/aggregate.rs, artichoke-backend/src/extn/core/array/backend/buffer.rs, artichoke-backend/src/extn/core/array/backend/fixed/empty.rs, artichoke-backend/src/extn/core/array/backend/fixed/hole.rs, artichoke-backend/src/extn/core/array/backend/fixed/one.rs, artichoke-backend/src/extn/core/array/backend/fixed/two.rs, artichoke-backend/src/extn/core/array/backend/repeated/value.rs, artichoke-backend/src/extn/core/array/mod.rs
This API change allows us to drop interior mutability via RefCell from
all concrete ArrayType implementations. This cuts down on allocations
by allowing ArrayTypes to not realloc by mutating themselves directly,
e.g. Hole::pop.
This is a followup to GH-333.
=> Alter ArrayType to take &mut self for mutating methods

artichoke-backend/src/extn/core/array/backend/aggregate.rs
There was a bug during the implementation of GH-320 where Aggregate::pop
was popping from the first part instead of the last. The bug was fixed,
but the local variable names were not changed.
This commit fixes up the names so they refer to the last chunk.
=> Rename temporary in Aggregate::pop from first to last

artichoke-backend/Cargo.toml, artichoke-backend/src/convert/object.rs, artichoke-backend/src/def.rs, artichoke-backend/src/extn/core/array/mod.rs, artichoke-backend/src/extn/core/env/env.rb, artichoke-backend/src/extn/core/env/mod.rs, artichoke-backend/src/extn/core/env/mruby.rs, artichoke-backend/src/extn/core/matchdata/mod.rs, artichoke-backend/src/extn/core/regexp/mod.rs, artichoke-backend/src/lib.rs, artichoke-backend/tests/leak_mrb_tt_data_rc.rs, artichoke-backend/tests/manual.rs, artichoke-backend/tests/obj_new_borrow_mut.rs, artichoke-backend/vendor/mruby/mrbgems/mruby-method/src/method.c, artichoke-backend/vendor/mruby/src/class.c, artichoke-backend/vendor/mruby/src/state.c, artichoke-backend/vendor/mruby/src/vm.c
This commit introduces the `artichoke-system-environ` feature. This feature
is enabled by default. When `artichoke-system-environ` is enabled, `ENV` will
delegate to the system environment via `std::env`.
When this feature is disabled, `ENV `will fallback to a `HashMap<Vec<u8>, Vec<u8>>`.
Using an in-memory backend is desirable in Wasm environments where (modulo an
emscripten shim) there is no environ. This also helps Artichoke tell a better
sandboxing story.
This commit also makes use of a technique introduced in the
`Kernel#Integer` patch which exposes functionality through an `Artichoke`
module that the Core delegates to. `Artichoke::Environ#[]`,
`Artichoke::Environ#[]=`, and `Artichoke::Environ#to_h` provide the same
glue that originally came from `EnvClass`.
`Artichoke::Environ` …
=> Enable compile-time selection of ENV backend

artichoke-backend/src/eval.rs, artichoke-backend/src/extn/core/array/args.rs, artichoke-backend/src/extn/core/matchdata/element_reference.rs, artichoke-backend/src/macros.rs, artichoke-backend/src/sys/ffi_tests.rs, artichoke-backend/src/value.rs, artichoke-backend/tests/leak/mod.rs, artichoke-backend/tests/manual.rs
- Use the docs recommended syntax for initializing.
- Replace mem::zeroed usage in leak module with MaybeUninit.
=> Improve usage of MaybeUninit

Cargo.lock, README.md, artichoke-backend/Cargo.toml, artichoke-backend/build.rs
I just got a new machine so it was an opportunity to set up a fresh clone with no prior deps installed.
Issues I ran into:
- Missing `bundler`
- `artichoke-backend` takes forever to build even on my 8 core machine with lots of time at low CPU utilization.
To address these:
- Added a new quickstart guide to the `README` to describe high level build deps.
- Add `parallel` feature to `cc` crate. We already include `rayon` so this pulled in no new deps.
- Added `num_cpus` crate to specify `--jobs` arg when building host build for mruby.
The build is still slow, but these build changes shaved 10 seconds off.
Fixes GH-319.
=> Improvements to project onboarding

Cargo.lock, Gemfile.lock, artichoke-backend/tests/leak/mod.rs, artichoke-backend/tests/leak_unbounded_arena_growth.rs, package.json, yarn.lock
Big change was upgrading the airbnb eslint config to v18.
Also disabled enforcement of all leak tests on all non-linux platforms.
=> [chore] Upgrade JS, Ruby, and Rust deps

artichoke-backend/src/fs/abs.rs, artichoke-backend/src/fs/mod.rs
`PathAbs` tests and `OsStr` converters.
This PR was extracted from GH-338.
=> Windows build fixes for artichoke_backend::fs

artichoke-backend/scripts/auto_import/auto_import.rb, artichoke-backend/scripts/auto_import/get_package_files.rb, artichoke-backend/scripts/auto_import/rust_glue.rs.erb
There are some crimes being committed by all parties converting back and forth between forward and backward slashes on windows.
This PR was extracted from GH-338.
=> Fixes to auto_import script to handle windows paths

artichoke-backend/src/extn/core/kernel/kernel.rb, artichoke-backend/src/extn/core/method/method.rb, artichoke-backend/src/extn/core/method/mod.rs, artichoke-backend/src/extn/core/mod.rs, artichoke-backend/src/extn/core/module/module.rb, artichoke-backend/src/extn/core/proc/mod.rs, artichoke-backend/src/extn/core/string.rb
Extract the Ruby sources from the remaining mrbgems. These are the last
dependencies on mrblib and mrbc from the mruby build. This unblocks work
on GH-303.
Fixes GH-196.
This PR was extracted from GH-338.
=> Remove dependency on mrblib

artichoke-backend/src/extn/core/env/env.rb, artichoke-frontend/src/ruby.rs
Fix lint failures on master for Rust clippy and Ruby rubocop.
- Split apart `artichoke_frontend::ruby::entrypoint` to make smaller functions by breaking out program file and inline eval cases.
- run `rubocop -a --only Migration/DepartmentName`.
=> Lint buildfix

scripts/spec-compliance.sh
The changes to introduce Artichoke Array to mruby were invasive and in some rare
but deterministic circumstances exhibit a use after free vulnerability.
This has been tickled already on GH-327, GH-342, and now on GH-357. Rather than
invest time and energy fixing this segfault, this PR disables the spec suite.
Disabling the spec suite sidesteps CI failures and allows us to maintain iteration
velocity.
The _reason_ to press onward and disable the specs is that moving faster on
implementing Ruby Core enables removing the mruby dependency more quickly. Removing
the C code from Artichoke is the stratgic approach to fixing the segfault.
The remaining bits of core are:
- nil, true, false
- String
- Integer
- Float
- Range
- Hash
- Class
- Module
- Exception
- Kernel
- Object, BasicObject
There …
=> Disable spec compliance suite due to segfaults in mruby VM

artichoke-backend/bootstrap.gembox, artichoke-backend/build.rs, artichoke-backend/mruby_build_config_null.rb, artichoke-backend/vendor/mruby/lib/mruby/gem.rb
mruby requires a host build that is not configurable enough to build
Artichoke. This has meant that Artichoke builds the host build to
bootstrap a 'sys' crossbuild that is used to produce the static library.
In the beginning, mruby's build process was used directly to produce
the static library that build.rs would link into Artichoke. More
recently, the sys crossbuild would only do C source generation and
build.rs would discover and compile these sources with the cc
crate.
Now that Artichoke no longer depends on mrblib or Ruby sources in
mrbgems, mrbc is no longer required and the host build is no longer
needed.
This PR replaces the host build with a noop. This changes the code
emitted by the mruby build process to eliminate gem irep embedding.
The bootstrap gembox no longer includes or …
=> Null out the mruby host build

.circleci/config.yml, artichoke-backend/mruby_build_config_null.rb, artichoke-backend/src/interpreter.rs
The build installs Rust, MRI, and executes `cargo build`.
Tests are run via `cargo test` but they currently segfault. Test failures are suppressed but tests are still built to ensure they compile.
=> Add a build on Windows with the Rust msvc toolchain

.circleci/config.yml
- Add sccache on Linux and Windows.
- Unify all linting tasks into a single job.
- Rename `rust` build and test on Linux to
match Windows job.
- Use `debian:buster-slim` as the base image
on Linux.
- Bump docs deploy base image to LTS node.
- Split ruby/spec suite testing into its own job.
- Suppress errors in ruby/spec job.
- Use `shfmt` to discover sources for `shellcheck`.
=> Improve CircleCI build

artichoke-backend/src/extn/core/string.rb
There were two issues with the delete methods
* In case the prefix / suffix does not match, we need to return
a copy of the string
* The methods were destructive
Disclaimer: Patch is untested!
=> Fix String#delete_suffix / prefix methods

.circleci/config.yml
CircleCI provides buster images with Ruby and node preinstalled.
Rust installs in ~30 seconds whereas building Ruby 2.6.3 from
source takes over 2 minutes, so use the Ruby images over the
Rust ones.
=> Use prebuilt images with Ruby 2.6.3 and node

artichoke-backend/src/extn/core/array/array.rb, artichoke-backend/src/extn/core/array/backend/aggregate.rs, artichoke-backend/src/extn/core/array/backend/buffer.rs, artichoke-backend/src/extn/core/array/backend/fixed/empty.rs, artichoke-backend/src/extn/core/array/backend/fixed/hole.rs, artichoke-backend/src/extn/core/array/backend/fixed/one.rs, artichoke-backend/src/extn/core/array/backend/fixed/two.rs, artichoke-backend/src/extn/core/array/backend/repeated/value.rs, artichoke-backend/src/extn/core/array/mod.rs, artichoke-backend/src/extn/core/array/mruby.rs, artichoke-backend/src/extn/core/array/trampoline.rs
This PR addresses #335. 
- Implement `Array#reverse` in ruby
- Update `ArrayType::reverse` to do an in-place reversal
- Cleanup the now unused `reverse` function in trampoline and update `reverse_bang` to use the in-place reversal
- Cleanup `ary_reverse` method in mruby
=> Change ArrayType::reverse to do an in-place reversal

artichoke-backend/src/extn/core/array/ffi.rs, artichoke-backend/src/extn/core/exception/mod.rs, artichoke-backend/src/extn/core/integer/mod.rs, artichoke-backend/src/extn/core/string.rs
This avoids boxing in some cases where the exception type is monomorphic.
=> Make exception::raise take impl RubyException

artichoke-backend/src/extn/core/regexp/backend/onig.rs, artichoke-backend/src/extn/core/regexp/backend/regex_utf8.rs
When profiling, Regexp pattern parsing was significant, since `Regexp` patterns were reparsed for every `MatchData`.
This PR implements `Clone` for the `RegexpType`s to cheaply and implements `RegexpType::box_clone` in terms of the `Clone` implementation.
=> Implement Clone for Onig and RegexUtf8 RegexpTypes

artichoke-backend/Cargo.toml, artichoke-backend/src/extn/core/exception/mod.rs
Backtrace generation was profiled to be 10% of all execution time during
a run of the spec suite. These backtraces are only useful in debug mode,
so hide them behind a crate feature.
=> Disable backtrace generation in non-debug builds

artichoke-backend/src/load.rs
Metadata structs are lazily allocated anyway when attaching Rust extensions or
requiring. There is no need to eagerly allocate.
This allocation was visible when profiling the ruby/spec runner.
=> Stop allocating a vfs metadata struct when defining a source file

.circleci/config.yml, doc/ruby-spec.md, package.json, scripts/spec.rb
This PR adds native support to performance timing and profiling to the spec runner script.
The new script unifies `spec-compliance.sh` and `run-spec.sh`.
This PR is to support GH-356.
=> Implement ruby/spec testing with a pure Ruby script

CONTRIBUTING.md, package.json
the flamegraph docs are handled better by the --profile option in
the spec runner.
=> Remove docs on loc flamegraph

artichoke-backend/src/extn/core/regexp/backend/onig.rs, artichoke-backend/src/extn/core/regexp/backend/regex_utf8.rs, artichoke-backend/src/extn/core/regexp/mod.rs, artichoke-backend/src/extn/core/string/scan.rs, artichoke-backend/src/module.rs, artichoke-backend/src/state.rs, artichoke-backend/src/value.rs, artichoke-frontend/src/ruby.rs
The `Symbol` cache in `State` held owned `String`s as the keys.
This was suboptimal because:
1. Symbols can contain arbitrary byte content.
2. Most symbols are known at compile time and have &'static lifetime.
This PR changes the type of the keys in the `Symbol` cache to
`Cow<'static, [u8]>`. This allows the state to avoid allocating a byte
vector unless it needs to to satisy ownership constraints.
Fixes GH-317.
=> Reduce allocations of Symbols backed by &'static byte strings

artichoke-backend/src/state.rs
mruby has a basic notion of lifetimes with two APIs for creating
Symbols:
- `mrb_intern`, which takes ownership of a borrowed Symbol by doing an
allocation and a memcpy.
- `mrb_intern_static`, which takes a Symbol whose lifetime outlives the
`mrb_state` and does no copy or free.
`mrb_intern_static` is only ergonomic for static String literals in C,
but when adding a `Cow<'static, [u8]>` to a `HashMap` in Rust, the bytes
will be cleaned up automatically when the interpreter closes.
This avoids an allocation for every `Symbol` created in Rust.
=> Use mrb_intern_static for interned Symbols from Rust

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-backend/mruby-sys/include/mruby-sys/artichoke.h, artichoke-backend/src/convert/array.rs, artichoke-backend/src/extn/core/array/backend/mod.rs, artichoke-backend/src/extn/core/array/ffi.rs, artichoke-backend/src/extn/core/array/inline_buffer.rs, artichoke-backend/src/extn/core/array/mod.rs, artichoke-backend/src/extn/core/array/mruby.rs, artichoke-backend/src/ffi.rs, artichoke-backend/vendor/mruby/include/mrbconf.h, artichoke-backend/vendor/mruby/src/class.c, artichoke-backend/vendor/mruby/src/error.c, artichoke-backend/vendor/mruby/src/init.c, artichoke-backend/vendor/mruby/src/vm.c, scripts/lint.js
`InlineBuffer` is a new Array implementation based on `Vec` and
`ArrayVec`. `Array`s with 8 elements or fewer are inlined into the
struct body. Larger `Arrays` are stored elsewhere on the heap in a
`Vec`.
`InlineBuffer` has a similar but not identical API to `ArrayType`. It partially implements `ArrayType` with this API. The other `ArrayType` backends are disabled with this
commit.
`InlineBuffer` supports moving `Array` contents from inline to dynamic
storage and back according to resizes and mutations.
`InlineBuffer` comes with a massive simplification of the modifications
to the mruby VM required to inject an Artichoke `Array`. This is
possible because:
- `InlineBuffer` stores `sys::mrb_value` rather than `Value`.
- `InlineBuffer` is coercable to `*const sys::mrb_value` and
`*mut …
=> Reimplement Array with a buffer type that optionally inlines

.circleci/config.yml
Without this change, caches that depend on checksums of lockfiles fail to load, like yarn deps.
=> Make checkout the first step of every job

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-backend/src/convert/array.rs, artichoke-backend/src/convert/float.rs, artichoke-backend/src/convert/hash.rs, artichoke-backend/src/convert/nilable.rs, artichoke-backend/src/extn/core/float/mod.rs, artichoke-backend/src/extn/core/kernel/kernel.rb, artichoke-backend/src/extn/core/mod.rs, artichoke-backend/src/extn/core/random/backend/default.rs, artichoke-backend/src/extn/core/random/backend/mod.rs, artichoke-backend/src/extn/core/random/backend/rand.rs, artichoke-backend/src/extn/core/random/mod.rs, artichoke-backend/src/extn/core/random/mruby.rs, artichoke-backend/src/extn/core/random/random.rb, artichoke-backend/src/state.rs, artichoke-backend/src/types.rs, artichoke-backend/src/value.rs
This commit implements all APIs of `Random` except for the internal
private method `Random#state` and `Random::Formatter`.
Random is implemented with the `rand` crate's not cryptographically
secure `SmallRng`. For cryptographically secure APIs like
`Random::urandom`, the re-seeding `rand::thread_rng` is used.
`Random` is gated behind a crate feature.
To support the `Random::DEFAULT` interpreter-widre PRNG, the interpreter
stores a `Random` on the `State` and injects a special backend to allow
the `DEFAULT` constant to target this `State`-owned `Random`.
`Random` is implemented with multiple backends and has a small API which
would make supporting a future CRuby algorithm possible. The `Rand`
backend is generic over the `rand::Rng` implementation.
This commit passes 30 ruby/specs and fails …
=> Implement Random core class and random functions in Kernel

artichoke-core/README.md
Dearest Reviewer,
The links back to the milestones are missing their S's. I found them over there in the snow. They are now pleased and working again.
Changes:
Updated the links back to github.
Thanks,
Becker
=> Fix links in readme

CONTRIBUTING.md
The Ruby dependencies aren't installed automatically like the documentation suggests. Running `yarn lint` will fail with the following message unless you have first run `bundle install`:
```
Could not find jaro_winkler-1.5.4 in any of the sources
Run `bundle install` to install missing gems.
```
This PR updates the documentation to include an explicit mention of `bundle install` and moves the Ruby section above the Node.js section since the gems are a dependency of `yarn lint`.
=> Update CONTRIBUTING.md for accuracy

artichoke-backend/build.rs, artichoke-backend/mruby_build_config_null.rb, artichoke-backend/scripts/noop.rb
This compatibility layer enables building on Windows without Cygwin or
bash installed in a native PowerShell environment.
=> Add a NOOP ruby script tha emulates Unix 'true' on Windows

.circleci/config.yml, artichoke-backend/src/convert/object.rs, artichoke-backend/src/extn/core/regexp/trampoline.rs, artichoke-backend/src/warn.rs, artichoke-core/src/lib.rs
`Object#allocate` is a Ruby API that creates uninitialized objects.
These objects have the correct class, but have not had the class's
`#initialize` method called on the allocated instance.
In the case of `MRB_TT_DATA`, this means that objects have the correct
class, but they do not have a valid `Rc` stored in the `DATA_PTR` and
they do not have a valid `mrb_data_type`.
Since GH-398 was merged, calling `RustBackedValue::try_from_ruby` with
an object created via `#allocate` would cause a borrow on the
interpreter to not get cleaned up because mruby would unwind past it.
This bad state was surfaced in the spec suite as a `AlreadyBorrowed`
panic when attempting a mutable borrow on the `Artichoke` interpreter.
This commit changes which APIs `RustBackedValue` calls when extracting
pointers …
=> Handle uninitialized objects in RustBackedValue::try_from_ruby

README.md, artichoke-backend/README.md, artichoke-backend/src/lib.rs, artichoke-core/README.md, artichoke-core/src/lib.rs, artichoke-frontend/README.md, artichoke-vfs/Cargo.toml, artichoke-vfs/README.md, package.json, scripts/lint.js, spec-runner/Cargo.toml, spec-runner/README.md, yarn.lock
Fixes GH-262.
This PR adds toml formatting to `scripts/lint.js`.
=> Revamp crate READMEs

README.md, artichoke-backend/README.md
Fix some typos introduced in GH-399.
=> Fix some typos in the new crate READMEs

artichoke-backend/src/fs.rs
fs module always passes the relative cwd, so eagerly prefix the path if
it is relative.
Followup to GH-403.
=> Avoid dependency on std::env::current_dir with path-dedot

artichoke-backend/src/extn/stdlib/abbrev.rb, artichoke-backend/src/extn/stdlib/abbrev.rs, artichoke-backend/src/extn/stdlib/mod.rs, scripts/spec.rb
Closes #74
This PR implements the Abbrev module in Rust.
=> Implement Abbrev module

artichoke-backend/src/extn/core/float/mod.rs, artichoke-backend/src/extn/core/integer/div.rs, artichoke-backend/src/extn/core/integer/mod.rs, artichoke-backend/vendor/mruby/src/vm.c
@CodeGradox Thanks for reporting GH-410. 💪 💎 
This PR overrides the implementation of `/` method attached to `Integer` class.
This PR also modifies the implementation of the `OP_DIV` opcode in the murby VM.
For speed, mruby pulls `/` out of the normal method dispatch flow and attempts to process operands as `Integer`s and `Float`s before falling back to method dispatch. This approach was hardcoded to return `Float` and promoted all `Integer` operands to `Float`s. This PR adds special handling for the two `Integer` operand case and adds a `raise ZeroDivisionError` in case of a zero divisor.
```console
$ RUST_BACKTRACE=1 cargo run --bin airb
artichoke 0.1.0 (2019-12-08 revision 2171) [x86_64-darwin]
[Rust 1.39.0 (rev 4560ea7) on x86_64-apple-darwin]
>>> x = 3
=> 3
>>> y = 2
=> 2
>>> …
```
=> Integer division

artichoke-backend/mruby-sys/include/mruby-sys/artichoke.h, artichoke-backend/src/extn/core/array/ffi.rs
There was drift between the definitions in array/ffi.rs and
artichoke.h in mruby-sys. clang was more forgiving of this
than emscripten.
This change is necessary to deploy the playground.
=> Sync Array FFI prototypes from ffi to C header

artichoke-backend/src/convert/hash.rs, artichoke-backend/src/convert/object.rs, artichoke-backend/src/convert/string.rs, artichoke-backend/src/extn/core/integer/mod.rs, artichoke-backend/src/extn/core/kernel/mod.rs, artichoke-backend/src/extn/core/regexp/mod.rs, artichoke-backend/src/value.rs, artichoke-backend/tests/leak_unbounded_arena_growth.rs, artichoke-core/src/value.rs, artichoke-frontend/src/repl.rs
Fixes #390. The root of the bug stems from `Value::to_s` cannot convert some byte sequences to UTF-8, so the fix suggested is to use the lossy UTF-8 conversion. I tried doing this in the implementation of `TryConvert<Value, &'a str> for Artichoke`, but ran into temporary value issues.
=> Changes .inspect/.to_s to return Vec<u8>

.circleci/config.yml
From https://circleci.com/gh/artichoke/artichoke/5205
```
#!powershell.exe -ExecutionPolicy Bypass
rustc --version --verbose
cargo --version --verbose
ruby --version
clang --version
win_bison --version
rustc 1.39.0 (4560ea788 2019-11-04)
binary: rustc
commit-hash: 4560ea788cb760f0a34127156c78e2552949f734
commit-date: 2019-11-04
host: i686-pc-windows-msvc
release: 1.39.0
LLVM version: 9.0
cargo 1.39.0 (1c6ec66d5 2019-09-30)
release: 1.39.0
commit-hash: 1c6ec66d5bae40e9dfd2fb82f091b5172c212d73
commit-date: 2019-09-30
ruby 2.6.3p62 (2019-04-16 revision 67580) [x64-mingw32]
clang version 9.0.0 (tags/RELEASE_900/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
bison (GNU Bison) 3.3.2
Written by Robert Corbett and Richard Stallman.
Copyright (C) …
```
=> Latest rustup is installing i686 Rust

scripts/lint.js, yarn.lock
Rewrite scripts/lint.js to use async/await instead of callbacks to make the resulting code easier to follow, more robust in the face of errors, and easier to extend.
This PR adds better error messages specific to each failed step.
Fixes GH-420.
=> Use async/await style in scripts/lint.js

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-backend/src/extn/core/array/inline_buffer.rs
The previous two iterations of `InlineBuffer` have slowly been reinventing `SmallVec`, which is a fixed-size array that can spill to a heap-allocated `Vec`.
This PR replaces that one off implementation with the `smallvec` crate from the Servo project which is more battle tested and should be higher performing than the previous `InlineBuffer` implementation.
This PR significantly reduces the code required to implement the Ruby `Array` type. This PR adapts the existing algorithms to remove the buffer management since this is now handled by `smallvec`. In practice this means the `Dynamic` variant algorithms were carried forward.
=> Reimplement InlineBuffer with smallvec crate

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-frontend/Cargo.toml
Run a cargo update to pull in a new version of rustyline that will enable adding a wasm32-unknown-emscripten build to Artichoke.
See GH-413.
=> Cargo update

artichoke-backend/Cargo.toml, artichoke-backend/src/extn/core/mod.rs, artichoke-backend/src/extn/core/time/backend/chrono.rs, artichoke-backend/src/extn/core/time/backend/mod.rs, artichoke-backend/src/extn/core/time/mod.rs, artichoke-backend/src/extn/core/time/mruby.rs, artichoke-backend/src/extn/core/time/time.rb, artichoke-backend/src/extn/core/time/trampoline.rs
This PR implements the `Time` class backed by the `chrono` crate. This
PR implements `Time::now` with local timezone and many of the date
accessors like `Time#year` and `Time#sec`.
This PR follows the same approach used in other core classes. There is a
public `Time` type that wraps a boxed trait object containing one of
potentially many backend implementations of the Ruby `Time`
functionality.
This code cannot pass ruby/spec because it does not expose fixed time
constructors.
Progress on GH-33.
=> Partially implement Time core class

artichoke-backend/src/class.rs, artichoke-backend/src/extn/core/exception/mod.rs, artichoke-backend/src/extn/core/regexp/backend/lazy.rs, artichoke-backend/src/module.rs, artichoke-backend/src/sys/mod.rs
Clean up sys module, class and module `CString` creation, and lazy regexp memoizing
Adds a clone interface to `RubyException`.
=> Remove unwraps

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-core/Cargo.toml
`log` in artichoke-core.
`arrayvec` in artichoke-backend (this was replaced by `smallvec`).
=> Remove unused deps from artichoke-core and artichoke-backend

artichoke-backend/src/extn/core/kernel/mod.rs, artichoke-backend/src/state.rs, artichoke-frontend/src/repl.rs
Ruby `String`s are equivalent to Rust's `Vec<u8>`, but not every Ruby
`String` could be printed by Artichoke because the `State::puts` and
`State::print` APIs took `&str`.
This commit is a followup to GH-406 which altered the `Value::to_s` and
`Value::inspect` APIs to return `Vec<u8>`. That PR pushed Rust UTF-8
`String` conversion to the `State` and `repl` frontend.
This commit changes the `State` APIs and `repl` to write binary content
to `io::stdout()` using Rust's `io::Write` trait. The internal capture
buffer for `wasm` targets is now a `Vec<u8>`.
Fixes GH-415.
To test, I used the `artichoke` binary to print some invalid UTF-8 and
dumped it with `xxd`. Before this patch, the program prints the UTF-8
replacement character. After this patch, the program prints `0xFF`.
Before:
```console …
```
=> Write Binary content to stdout

artichoke-backend/src/eval.rs, artichoke-backend/src/extn/core/kernel/require.rs, artichoke-frontend/src/repl.rs, artichoke-frontend/src/ruby.rs
The API for constructing a `Context` allowed creating Contexts that
could never be used as Contexts. `Context::new` takes effectively a byte
slice and is infallible. `Context` is used as a `CString` by
`Artichoke`'s `Eval` implementation to set the filename on the mruby
parser.
This restriction means that the byte slice used to make the Context
cannot contain any NUL bytes. This restriction also means that getting a
`CString` from the `Context` now must be fallible. Falliblilty when
getting the `Context`'s `CString` is inconvenient in APIs like
`unchecked_eval` which themselves are infallible.
This PR alters the constructor `Context::new` to return
`Option<Context>`. This changes `Context` so that it parses the
`CString` on create instead of validating at use whether the object is
valid. …
=> Eagerly parse a Context filename into a CString

doc/ruby-spec.md
The example she’ll code was missing the interpreter arg
=> Fix ruby spec example doc

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-backend/src/fs.rs
Upon review, `path-dedot` relies on a lazily-initialized snapshot of the process's current working directory. This is lurky and there is no way to disable this.
This PR reimplements path normalization using the `Path::components` iterator.
=> Replace path-dedot with an iterator-based implementation

artichoke-backend/build.rs, artichoke-backend/src/convert/array.rs, artichoke-backend/src/convert/bytes.rs, artichoke-backend/src/convert/hash.rs, artichoke-backend/src/convert/string.rs, artichoke-backend/src/extn/core/regexp/backend/regex_utf8.rs, artichoke-backend/src/extn/core/string.rs, artichoke-backend/tests/manual.rs
`Vec::<String>::new()` instead of `<Vec<String>>::new()`.
=> Convert some syntax in converters to preferred style

artichoke-backend/src/convert/fixnum.rs, artichoke-backend/src/convert/hash.rs, artichoke-backend/src/convert/string.rs, artichoke-backend/src/value.rs, artichoke-backend/tests/leak_funcall.rs
Call convert as an associated function to add the type hints
and specify `Vec` inner types when collecting.
=> Remove explicit type annotations where possible

artichoke-backend/scripts/auto_import/rust_glue.rs.erb, artichoke-backend/src/class.rs, artichoke-backend/src/convert/object.rs, artichoke-backend/src/def.rs, artichoke-backend/src/eval.rs, artichoke-backend/src/extn/core/artichoke/mod.rs, artichoke-backend/src/extn/core/comparable/mod.rs, artichoke-backend/src/extn/core/enumerable/mod.rs, artichoke-backend/src/extn/core/kernel/mod.rs, artichoke-backend/src/extn/core/random/mruby.rs, artichoke-backend/src/extn/core/warning/mod.rs, artichoke-backend/src/extn/stdlib/abbrev.rs, artichoke-backend/src/extn/stdlib/forwardable.rs, artichoke-backend/src/method.rs, artichoke-backend/src/module.rs
This commit breaks the dependency of `def` module on the Artichoke
interpreter. `def` is predominantly glue between Rust and FFI and only
needs a reference to the `mrb_state`.
`class::Spec::rclass` and `module::Spec::rclass` now take an
`mrb_state`.
`module::Spec::new` takes an `Artichoke` and eagerly generates the
`Symbol` ID for the class name, which removes the `Cell` member and
enables `module::Spec::rclass` to take only an `mrb_state`.
=> Return Option<NonNull<sys::rclass>> from rclass APIs.

artichoke-backend/src/exception_handler.rs
Use Rust patterns like mem::replace and NonNull to minimize unsafe in
ExceptionHandler impl to one pointer deref and one FFI funcall.
Add safety proofs.
=> Minimize unsafe in ExceptionHandler::last_error

artichoke-backend/src/extn/core/array/args.rs, artichoke-backend/src/extn/core/array/mod.rs, artichoke-backend/src/extn/core/kernel/integer.rs, artichoke-backend/src/extn/core/matchdata/begin.rs, artichoke-backend/src/extn/core/matchdata/element_reference.rs, artichoke-backend/src/extn/core/matchdata/end.rs, artichoke-backend/src/extn/core/matchdata/offset.rs, artichoke-backend/src/extn/core/regexp/mod.rs
=> Replace to_int funcalls in Rust with Value::implicitly_convert_to_int

artichoke-backend/src/ffi.rs, artichoke-backend/src/interpreter.rs, artichoke-backend/src/state.rs, artichoke-backend/src/sys/mod.rs, artichoke-backend/src/value.rs
This commit was extracted from GH-442.
This commit is a step toward storing `NonNull<sys::mrb_state>` on
the Artichoke struct directly.
=> Parse raw mrb pointers into NonNull for added safety

artichoke-backend/src/convert/array.rs, artichoke-backend/src/convert/bytes.rs, artichoke-backend/src/convert/hash.rs, artichoke-backend/src/convert/nilable.rs, artichoke-backend/src/convert/string.rs
Remove instances of value.try_into and instead use the TryConverter trait, sometimes
with assisted inference.
=> Remove dependency on artichoke_core::value::Value in artichoke-backend converters

artichoke-backend/src/class.rs, artichoke-backend/src/exception.rs, artichoke-backend/src/extn/core/array/mruby.rs, artichoke-backend/src/extn/core/regexp/mruby.rs, artichoke-backend/src/value.rs
- Convert Result to Option with ok().
- Handle failed FFI conversions between usize and mrb_int.
See also GH-430.
=> Replace unwrap_or_default with semantic error handling

artichoke-backend/src/exception.rs, artichoke-backend/src/lib.rs
- Add `Artichoke::into_raw` associated function analogous to `Box::into_raw` that consumes an interpreter and returns the underlying `*mut mrb_state`.
- Use this new API in `exception::raise`.
- Add a `fmt::Debug` trait bound on the `RubyException` passed into `exception::raise`.
- Use debug formatting of exception in `error` and `panic` messages.
This PR was inspired by GH-442.
=> Add safety and logging to exception::raise

artichoke-backend/src/extn/core/array/inline_buffer.rs
Returning an error into the interpreter is better than panicking, even if the `unimplemented!` branch is unreachable.
=> Replace unimplmented! with Err(Fatal) in InlineBuffer

artichoke-backend/src/extn/core/array/backend/mod.rs, artichoke-backend/src/extn/core/array/ffi.rs, artichoke-backend/src/extn/core/array/inline_buffer.rs, artichoke-backend/src/extn/core/array/mod.rs
Change the return type on ArrayType::get to return Option<Value> in
the success case. This makes the type more closely align with std
collections and may eliminate the need for an ArrayType to use the
converter APIs.
This pushes conversion of None valued options into a nil Value to
the public API of Array.
This is part of a push to push interpreter glue to out of core type
backends.
This PR was inspired by GH-442.
=> Push nil-value coercion to the edge of Array API

artichoke-backend/src/extn/core/array/mod.rs
When InlineBuffer was introduced, the branches in Array::initialize that
were previously implemented with `backend::repeated::value` and
`backend::fixed::hole` were replaced with a call to `unimplemented`.
This commit implements these cases and does so by unifying them into one
branch. This branch and the one above for block initializations are
modified to build a buffer of `sys::mrb_value` instead of `Value` to
reduce an allocation while constructing the `SmallVec`.
This PR is inspired by GH-442.
=> Implement default fill branches of Array#initialize constructor

artichoke-backend/src/extn/core/array/mod.rs, artichoke-backend/src/extn/core/regexp/mod.rs
When `Warn::warn` used to return `ArtichokeError` in the error case, it was necessary to mask these errors into a `RubyException`. `Warn::warn` now returns a `RubyException` compatible error, so these masks are no longer necessary.
This means underlying errors from the funcall on `Warning::warn` in Ruby will be propagated.
This PR was inspired by GH-442 and the bug discovered when reviewing GH-462.
=> Propagate Exception errors from Warn::warn in extn

artichoke-backend/src/extn/core/env/backend/memory.rs, artichoke-backend/src/extn/core/env/backend/mod.rs, artichoke-backend/src/extn/core/env/backend/system.rs, artichoke-backend/src/extn/core/env/mod.rs
- Rename `Env` trait to `EnvType` and move it to the `env::backend`
module to be consistent with Array and other core types.
- Modify return types of `EnvType::get` to return Option<Vec<u8>>. This
pushes conversions out to the edge. See GH-460.
- Rewrite error handling to use question mark operator for automatic
`Exception::from` conversions and clearer control flow.
- Return `Cow<'self, [u8]>` in `EnvType::get` to reduce allocations if
the backend owns the data (as the `Memory` type does).
=> Rewrite ENV module

artichoke-backend/src/extn/core/exception/mod.rs
Use ? operator to unpack options.
=> Simplify implementation of RubyException::as_value

artichoke-backend/src/extn/core/random/backend/default.rs, artichoke-backend/src/extn/core/random/backend/mod.rs, artichoke-backend/src/extn/core/random/backend/rand.rs, artichoke-backend/src/extn/core/random/mod.rs, artichoke-backend/src/extn/core/random/mruby.rs, artichoke-backend/src/state/mod.rs, artichoke-backend/src/state/prng.rs
This commit renames `random::backend::Rand` trait to `RandType` to match
more closely with other modules. The API has been redefined to remove
fallibility and take mutable references to the interpreter when
required. This approach is part of gradually introducing mutability
requirements that was first rolled out in GH-467.
The previous implementation of the interpreter default PRNG attached a
`Random` instance to the `State`. This approach is not compatible with
an idiomatic borrowing setup, as found in GH-442.
This PR introduces a new `Prng` state component. The `Prng` binds
directly to a `Rand<SmallRng>` instead of a `Random` wrapper around a
`RandType` trait object.
`Rand` random backend has now implemented methods outside of `RandType`
that do not take an interpreter. Since the PRNG …
=> Rewrite random module to introduce a new state component

artichoke-backend/src/eval.rs, artichoke-backend/src/exception_handler.rs, artichoke-backend/src/sys/mod.rs, artichoke-backend/src/sys/protect.rs, artichoke-backend/src/value.rs
This commit extracts the low-level `mrb_protect` API out of
`Value::funcall`, `Eval::eval`, and `Block::yield_arg`. Module
`sys::protect` exposes functions for each use case that call the
appropriate mruby APIs and wrap each interpreter call in `mrb_protect`
to prevent `longjmp` unwinds from unwinding Rust frames.
This fixes a bug where `mrb_protect` was not present for block yields.
The `sys::protect` family of functions properly extract exceptions from
the interpreter and return `Result<sys::mrb_value, sys::mrb_value>`.
This signigifcantly simplifies the exception handler which has been
refactored into a function instead of a trait.
This change makes explicit an exception handling step that worked by
accident before: some errors like `SyntaxError` do not get returned out
of …
=> Move low-level protect code into sys::protect module

artichoke-backend/src/warn.rs
Discovered when working on GH-442.
=> Write warnings to stderr instead of using the log crate

artichoke-backend/src/extn/core/regexp/mod.rs
`Warn::warn` already takes byte slices so it is not necessary to round trip through String.
Discovered when working on GH-442.
=> Construct warnings as raw byte slices to avoid using String::from_utf8_lossy

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-backend/src/extn/core/exception/mod.rs
`env_logger` dev-dependency is a relic from when cactusref was part of this repo I
think and is not used in tests.
I added backtraces to RubyExceptions because I thought it was cool and then added
a feature to turn them off because they are slow. This was functionality without
a concrete use case. Time to purge this dep and code. This commit also removes the
`artichoke-debug` feature.
=> Remove env_logger and backtrace from artichoke-backend

artichoke-backend/src/extn/core/kernel/integer.rs, artichoke-backend/src/extn/core/kernel/require.rs, artichoke-backend/src/extn/core/matchdata/element_reference.rs, artichoke-backend/src/extn/prelude.rs, artichoke-backend/src/lib.rs, artichoke-backend/src/string.rs, artichoke-frontend/src/repl.rs, artichoke-frontend/src/ruby.rs
Sometimes (mostly when generating `Exception` messages), Ruby escapes `String` contents so they can be displayed. This mostly means escaping invalid UTF-8 sequences into `\xXX` escape sequences.
`bstr` offers a way to do this with the `fmt::Debug` implementation on the `&BStr` type. Unfortunately this is not quite flexible enough:
- `bstr` by wraps the escaped string in quotes.
- Most of the time Artichoke inserts an escaped string into the context of a larger message.
- Slicing into the debug String and formatting again causes unnecessary and fallible allocations.
This PR inlines the `Debug` implementation minus the quotes into the `string::escape_unicode` method. This method takes a `fmt::Write` to write the escaped string into and returns a specific, but `RubyException` compatible …
=> Implement a wrapper around BStr's Debug impl

artichoke-backend/Cargo.toml, artichoke-backend/build.rs, artichoke-backend/src/convert/array.rs, artichoke-backend/src/convert/hash.rs, artichoke-backend/src/extn/core/array/mruby.rs, artichoke-backend/src/extn/core/regexp/mod.rs
The `artichoke-array` feature was added to enable a temporary rollout of
the Artichoke-native `Array` to the playground as the implementation
evolved and shook off all of the segfaults.
As of GH-382, these segfaults are fixed since the Array type is
implemented with a contiguous buffer.
This commit removes the legacy code, makes the Artichoke Array the
default, and removes the feature.
As of this commit, mruby is always built with `-DARTICHOKE`. This change
was required as I think about implementing more core types, like
`Symbol`.
=> Remove artichoke-array feature

artichoke-frontend/src/repl.rs
Use the locally-defined From impls and ?-operator coercion.
=> Clean up unnecessary map_err in REPL

artichoke-backend/src/extn/core/array/mod.rs, artichoke-backend/src/extn/core/array/mruby.rs, artichoke-backend/src/extn/core/array/trampoline.rs, artichoke-backend/src/extn/core/regexp/mod.rs, artichoke-backend/src/extn/core/regexp/mruby.rs, artichoke-backend/src/extn/core/regexp/trampoline.rs, artichoke-backend/src/warn.rs, artichoke-core/src/warn.rs
Warn::warn allocates on the interpreter heap when sending the message to
the Warning#warn method, so it requires unique access.
=> Make Warn::warn take &mut self

artichoke-backend/Cargo.toml, artichoke-backend/src/convert/array.rs, artichoke-backend/src/convert/hash.rs, artichoke-backend/src/convert/nilable.rs, artichoke-backend/src/extn/core/array/inline_buffer.rs, artichoke-backend/src/extn/core/string.rs, artichoke-backend/src/extn/stdlib/forwardable.rs
Remove the 1000+ Convert and TryConvert implementations. Remove the
`artichoke-all-converters` feature.
Manually implement all converters required by the current application.
Converters are specialized for each type and do not funnel through the
base `Value` converter for collections.
This change is in preparation for converter work falling out of GH-442
which will require converters that allocate on the interpreter heap as
`&mut self`.
This patch removes a bunch of code and speeds up compile times. (Shaves
5s or 10% off a clean build on my machine.)
Fixes GH-486.
=> Remove macro-generated converter implementations

Cargo.lock, artichoke-backend/Cargo.toml
The playground has long used a fork of rust-onig that lives at
https://github.com/artichoke/rust-onig
The playground used this fork to pull in changes to the `onig_sys`
`build.rs` to add wasm support.
artichoke/rust-onig@952305049073f37ada5543536c4c58540ea3642b adds a
change to the `bindgen` dependency of `onig_sys` to pull in the same
version of `bindgen` that is used in `artichoke-backend`.
This change reduces the dependency count in `Cargo.lock` measurably.
With this commit, `Cargo.lock` contains only one version of `syn`,
`quote`, and `proc-macro2`. Artichoke no longer has `failure` or
backtrace` in its dependency tree.
=> Replace crates.io rust-onig with the artichoke fork

artichoke-backend/src/string.rs
The write does not need to be moved into escape_unicode
=> Take &mut fmt::Write in string::escape_unicode

scripts/spec.rb
This prevents the spec runner from executing if there is a compilation
error.
=> Abort scripts/spec.rb unless cargo build succeeds

doc/ruby-spec.md, scripts/spec.rb, spec-runner/enforced-specs.yaml
This commit extracts the definitions of the enforced passing specs into
a YAML file in the spec-runner crate.
This is a required step to consume this information from Rust.
`scripts/spec.rb` still runs and passes 804 specs after this commit.
=> Define enforced specs in an external YAML config

artichoke-backend/src/eval.rs, artichoke-backend/src/extn/core/env/backend/system.rs, artichoke-backend/src/extn/core/kernel/require.rs, artichoke-backend/src/ffi.rs, artichoke-backend/src/ffi/unix.rs, artichoke-backend/src/ffi/unknown.rs, artichoke-backend/src/ffi/windows.rs, artichoke-backend/src/fs.rs, artichoke-backend/src/load.rs, artichoke-core/src/eval.rs, artichoke-frontend/src/ruby.rs
The `ruby` CLI frontend must eval `-e` inline eval strings directly from
the command line args. Rust + Clap + StructOpt exposes these as
`OsString`.
Rather than expose `artichoke-backend` internals for ffi adapters or
duplicate `OsStr` <=> bytes conversions, this commit adds a new `Eval`
API that takes an `OsStr` directly and does the conversion in
`artichoke-backend`.
This commit extracts the conversion functions from the `fs` module
(where they were originally extracted from `extn::core::env`). Since
these converters are platform-specific code, move them to the `ffi`
module.
The converters use a custom error type which implements `RubyException`
and `Into<Exception>`, which eliminates the need for these APIs to take
an interpreter.
This commit moves the platform specific FFI functions …
=> Add Eval::eval_os_str API to artichoke-core

artichoke-backend/src/def.rs, artichoke-backend/src/exception.rs, artichoke-backend/src/exception_handler.rs, artichoke-backend/src/extn/core/exception/mod.rs, artichoke-backend/src/extn/core/kernel/mod.rs, artichoke-backend/src/extn/core/thread.rs, artichoke-backend/src/ffi.rs, artichoke-backend/src/io.rs, artichoke-backend/src/lib.rs, artichoke-backend/src/string.rs, artichoke-backend/tests/leak_unbounded_arena_growth.rs, artichoke-core/src/lib.rs, artichoke-core/src/parser.rs, artichoke-frontend/src/repl.rs
- Remove `description` implementations. `description` is soft
deprecated.
- Convert `cause` implementations to `source`. `cause` is deprecated and
`source` supports downcasting.
- Remove empty `source` implementations.
- Inline static str when code previously called `description`.
- Rename `RubyException::backtrace` to `RubyException::vm_backtrace` to
address upcomming `std::backtrace` name reservation.
- Add `WriteError::into_inner` for extracting inner `fmt::Error` for use
in `Debug` and `Display` impls.
- Replace `String::from_utf8_lossy` with `string::escape_unicode` in
several `Debug` and `Display` impls.
- Add a `std::error::Error` supertrait to `RubyException`.
- Add missing error impls.
- Update frontend backtrace callsite.
=> Fix std::error deprecations

artichoke-backend/src/extn/core/regexp/backend/lazy.rs, artichoke-backend/src/extn/core/regexp/backend/mod.rs, artichoke-backend/src/extn/core/regexp/backend/onig.rs, artichoke-backend/src/extn/core/regexp/backend/regex/utf8.rs
The new name actually names the type by its purpose, which makes the code easier
to read.
=> Rename HashOfStringToArrayOfInt type alias to NameToCaptureLocations

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-backend/build.rs
This change pulls in artichoke/rust-onig@11bc679 which similarly updates
bindgen in our fork of `onig_sys`.
This upgrade took a while because `artichoke-backend` depends on
`bindgen` with no default features and 0.52.0 added a new `runtime`
feature which is required to have `clang-sys` load libclang correctly.
=> Update bindgen to latest (0.53.1)

artichoke-backend/src/convert.rs, artichoke-backend/src/convert/array.rs, artichoke-backend/src/convert/boolean.rs, artichoke-backend/src/convert/bytes.rs, artichoke-backend/src/convert/fixnum.rs, artichoke-backend/src/convert/float.rs, artichoke-backend/src/convert/hash.rs, artichoke-backend/src/convert/nilable.rs, artichoke-backend/src/convert/string.rs, artichoke-backend/src/def.rs, artichoke-backend/src/extn/prelude.rs, artichoke-backend/src/ffi.rs, artichoke-backend/src/io.rs, artichoke-backend/src/lib.rs, artichoke-backend/src/string.rs, artichoke-backend/src/test/prelude.rs, artichoke-backend/src/value.rs, artichoke-backend/src/warn.rs, artichoke-backend/tests/leak_funcall.rs, artichoke-backend/tests/manual.rs, artichoke-frontend/src/ruby.rs
Simplify the module tree in artichoke-backend by removing redundant
exports of `Convert`, `ConvertMut`, `TryConvert`, and `TryConvertMut`
from the `artichoke_backend::convert` module.
Modify all imports to use the traits at the crate root which are already
reexported from artichoke-core.
=> Remove converter trait reexports from artichoke_backend::convert

artichoke-backend/src/interpreter.rs, artichoke-core/src/lib.rs
This commit modifies the return type of the `interpreter` constructor to
return `Exception` error type instead of `BootError`. This allows a
single error type that unifies `extn` initialization errors with
allocation failures behind a `std::error::Error` implementing type.
The `ArtichokeError::New` variants are replaced by a specialized error
type that implements `RubyException` and can be raised as a `fatal`.
The only remaining public API that returns `ArtichokeError` is the
converter suite.
=> Add InterpreterAllocError for interpreter initialization failures

artichoke-backend/src/convert/array.rs, artichoke-backend/src/convert/hash.rs, artichoke-backend/src/convert/object.rs, artichoke-backend/src/extn/core/array/mod.rs, artichoke-backend/src/extn/core/array/trampoline.rs, artichoke-backend/src/extn/core/env/mod.rs, artichoke-backend/src/extn/core/matchdata/begin.rs, artichoke-backend/src/extn/core/matchdata/captures.rs, artichoke-backend/src/extn/core/matchdata/element_reference.rs, artichoke-backend/src/extn/core/matchdata/end.rs, artichoke-backend/src/extn/core/matchdata/length.rs, artichoke-backend/src/extn/core/matchdata/named_captures.rs, artichoke-backend/src/extn/core/matchdata/names.rs, artichoke-backend/src/extn/core/matchdata/offset.rs, artichoke-backend/src/extn/core/matchdata/post_match.rs, artichoke-backend/src/extn/core/matchdata/pre_match.rs, artichoke-backend/src/extn/core/matchdata/regexp.rs, artichoke-backend/src/extn/core/matchdata/string.rs, artichoke-backend/src/extn/core/matchdata/to_a.rs, artichoke-backend/src/extn/core/matchdata/to_s.rs, artichoke-backend/src/extn/core/random/mod.rs, artichoke-backend/src/extn/core/regexp/trampoline.rs, artichoke-backend/src/extn/core/time/trampoline.rs, artichoke-backend/tests/manual.rs, artichoke-core/src/lib.rs
This patch adds consistent handling for allocated but uninitialized
values and returns either `TypeError` or `NotDefinedError` in Rust.
This commit removes two error variants in `ArtichokeError`:
`UninitializedValue` and `NotDefined`.
=> Return Exception errors from RustBackedValue APIs

artichoke-backend/src/value.rs, artichoke-core/src/lib.rs
Add a new error type `ArgCountError` which is returned by
`Value::funcall` when there are more than 16 arguments passed to a
funcall.
This struct implements `RubyException` and replaces the
`ArtichokeError::TooManyArgs` variant. This variant is removed.
=> Add ArgCountError RubyException

artichoke-backend/src/value.rs, artichoke-core/src/lib.rs
This variant was unused and erroneously referenced in documentation.
=> Remove ArtichokeError::UnreachableValue variant

artichoke-backend/src/ffi.rs, artichoke-backend/src/interpreter.rs, artichoke-core/src/lib.rs
Return a single error type from `ffi::from_user_data` that raises as a
`fatal`.
Remove the unused variant from `ArtichokeError`.
=> Replace ArtichokeError::Uninitialized with InterpreterExtractError

artichoke-backend/src/convert.rs, artichoke-backend/src/convert/array.rs, artichoke-backend/src/convert/boolean.rs, artichoke-backend/src/convert/bytes.rs, artichoke-backend/src/convert/fixnum.rs, artichoke-backend/src/convert/float.rs, artichoke-backend/src/convert/hash.rs, artichoke-backend/src/convert/nilable.rs, artichoke-backend/src/convert/string.rs, artichoke-backend/src/extn/core/array/ffi.rs, artichoke-backend/src/extn/core/kernel/mod.rs, artichoke-backend/src/extn/core/matchdata/regexp.rs, artichoke-backend/src/extn/core/regexp/backend/onig.rs, artichoke-backend/src/extn/core/regexp/backend/regex/utf8.rs, artichoke-backend/src/extn/core/regexp/enc.rs, artichoke-backend/src/extn/core/regexp/mod.rs, artichoke-backend/src/extn/core/regexp/opts.rs, artichoke-backend/src/extn/core/string.rs, artichoke-backend/src/extn/core/string/scan.rs, artichoke-backend/src/value.rs, artichoke-backend/tests/manual.rs, artichoke-core/src/convert.rs, artichoke-core/src/types.rs, artichoke-core/src/value.rs
This PR continues the push toward removing the `ArtichokeError` type and moving toward a unified error abstraction where all APIs return a variant of `dyn RubyException`.
This PR introduces two new error types in `artichoke_backend::convert`:
- `UnboxRubyError`: returned when failing to unbox a Ruby `Value` into a Rust native type. Raisable as a Ruby `TypeError`.
- `BoxIntoRubyError`: returned when failing to box a Rust value into a Ruby `Value`. This usually occurs when the Ruby box does not have sufficient capacity to store the Rust value. For example, trying to box a `u64` on wasm32. Raisable as a Ruby `TypeError`.
To wire up this change, the converter traits in `artichoke-core` have been modified to encode the error type as an associated type.
`ValueLike::itself` has been removed. …
=> Return Exception error type from TryConvert implementations

artichoke-backend/src/extn/prelude.rs, artichoke-backend/src/lib.rs, artichoke-backend/src/test/prelude.rs, artichoke-core/src/lib.rs, artichoke-frontend/src/bin/artichoke.rs, artichoke-frontend/src/bin/ruby.rs, artichoke-frontend/src/repl.rs, artichoke-frontend/src/ruby.rs, spec-runner/src/mspec.rs
This completes the migration to a unified error type in Artichoke that
began with GH-311. All uses of the `ArtichokeError` enum have been
migrated to specialized error types that implement `std::error::Error`
and `RubyException`. This enables them to be handled by standard Rust
error handling mechanisms as well as be raisable on an Artichoke
interpreter.
`BootError` was always a temporary stopgap to bridge the
`ArtichokeError` and `Exception` error types in frontend and `extn` code
as the rollout and migration was executed.
The following PRs contributed to this fix:
- GH-311
- GH-371
- GH-387
- GH-430
- GH-437
- GH-457
- GH-461
- GH-463
- GH-465
- GH-470
- GH-474
- GH-496
- GH-497
- GH-500
- GH-507
- GH-508
- GH-509
- GH-510
- GH-511
- GH-512
=> Remove ArtichokeError and BootError

.circleci/config.yml, Cargo.lock, artichoke-frontend/Cargo.toml, deny.toml
Enforce only during builds instead of the interactive linter since
this check is less likely to break accidentally, i.e. you'd have to
add a dependency or a security advisory would have to be issued.
=> Add cargo-deny configuration and enforce during builds

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-backend/build.rs
`rayon` is a heavy dependency and brings in a lot of crossbeam crates.
Depending on `rayon` directly in artichoke-backend's build.rs used to be
free because `cc` used rayon to implement the `parallel` feature for
parallel compilation. cc 1.0.42 moved away from `rayon` to `jobserver`.
This commit removes `rayon` and converts the `par_iter` loops into normal
for loops.
This code also cleans up the package generation code:
- renamed functions for path generation
- renamed erb invocation to "module render" step
- simplified source iterator chain
- pass `--disable-all` flag to MRI to disable all features instead of
only `gems` and `did_you_mean`
Added documentation to birthdate build step that the code assumes there
is only one reachable git root.
This commit also removes the explicit `bstr` …
=> Remove rayon from artichoke-backend build

artichoke-backend/src/def.rs
This error type is already constructed with a constructor that takes
`Into<String>`. All callers already have `Cow<'static, str>`. Plumb the
cow through and potentially avoid an allocation.
=> ConstantNameError holds a Cow<str>

artichoke-backend/src/extn/core/matchdata/element_reference.rs
The iterator expression returns:
Option<&Option<Vec<u8>>>
This code is refactored to avoid a clone by using a nested pattern and
coercing the resultant `&Vec<u8>` to a slice, which can be correctly
processed by the converter.
This avoids an unnecessary allocation and makes the code easier to read.
=> Handle nested option of Vec without cloning in MatchData#[]

Cargo.lock, artichoke-backend/src/class.rs, artichoke-backend/src/convert/object.rs, artichoke-backend/src/def.rs, artichoke-backend/src/extn/core/env/mruby.rs, artichoke-backend/src/extn/core/kernel/mod.rs, artichoke-backend/src/extn/core/random/mruby.rs, artichoke-backend/src/extn/mod.rs, artichoke-backend/src/module.rs, artichoke-backend/src/warn.rs
Make `NotDefinedError` store `Cow<'static, str>` and add constructors
for all variants that use an `Into<Cow<'static, str>>` type bound.
=> NotDefinedError takes a Cow<str>

artichoke-backend/src/extn/core/matchdata/element_reference.rs
Followup to GH-516.
Use `Option::as_deref` to turn `&Option<Vec<u8>>` into `Option<&[u8]>`.
This gives us a nested owned `Option` which lets us call `flatten`.
=> Simplify nested Option conversion in MatchData#[]

artichoke-backend/src/extn/core/env/mod.rs, artichoke-backend/src/extn/core/kernel/integer.rs, artichoke-backend/src/extn/core/kernel/require.rs, artichoke-backend/src/extn/core/matchdata/element_reference.rs, artichoke-backend/src/extn/core/matchdata/mod.rs, artichoke-backend/src/extn/core/matchdata/offset.rs, artichoke-backend/src/extn/core/regexp/mod.rs, artichoke-backend/src/extn/core/string/scan.rs, artichoke-backend/src/value.rs
Implement `Value::implicitly_convert_to_string` and `Value::implicitly_convert_to_nilable_string`.
Modify all sites manually doing a funcall on `to_str`.
This unifies many different and subtly incorrect ways to call this method.
These implementations and `implicitly_convert_to_int` are modified to return `TypeError` and check if the receiver `responds_to?` the converter before making the funcall.
Fixes GH-452
cc GH-310
=> Implicitly convert to string

artichoke-backend/src/extn/core/matchdata/element_reference.rs
Followup to GH-519.
https://www.reddit.com/r/rust/comments/f3cvkr/using_optionas_deref_and_optionflatten_to_remove/
See also https://github.com/rust-lang/rust-clippy/issues/5175
=> Replave map(_).flatten() with and_then(_)

artichoke-backend/src/eval.rs, artichoke-backend/src/ffi.rs, artichoke-backend/src/interpreter.rs, artichoke-backend/src/state/mod.rs, artichoke-backend/src/sys/mod.rs
This function replaces the DescribeState trait and the fmt::Debug
implementations on the various mrb_state pointer types.
DescribeState was introduced because it was not possible to implement
fmt::Debug on a *mut sys::mrb_state due to conflicts with blanket impls
in std.
The trait was awkward to use and provides no additional value over a function
that takes a *mut mrb_state directly.
This removes some panicking pathways from sys and makes the debug info generation
infallible and panic free.
=> Add sys::mrb_sys_state_debug free function

.circleci/config.yml, artichoke-backend/build.rs, artichoke-backend/src/extn/core/array/mruby.rs, artichoke-backend/src/sys/mod.rs, spec-runner/build.rs
The restriction job logs less than good patterns that we one day should
eliminate. Restriction lint passes fall into these categories:
- Identify code that may panic.
- Identify code that is checked in debugging code.
- Identify unimplemented APIs.
This job makes use of cargo-expand to find known panicking formatting
macros in `std` and clippy with manually opted-in restriction lints such
as `dbg_macro`, `index_slicing`, or `result_unwrap_used`.
This job will not be required to pass for PRs to merge. It is intended
to gather metrics and eventually drive these lint failures to zero
before a public release.
This PR fixes one restriction lint error: a stray `println!` in `Array` FFI code.
=> Add a restriction lint job to CI

artichoke-backend/src/constant.rs, artichoke-backend/src/def.rs, artichoke-backend/src/extn/core/random/mruby.rs, artichoke-backend/src/extn/mod.rs, artichoke-backend/src/extn/prelude.rs, artichoke-backend/src/lib.rs, artichoke-core/src/constant.rs, artichoke-core/src/lib.rs
`DefineConstant` exposes APIs for defining global constants as well as
constants on class or module values.
Use them in extn global constants and `Random::DEFAULT`. This commit
removes the macro-based const definition approach in `extn::init`.
Related to GH-442.
=> Add constant definition APIs to artichoke-core

.circleci/config.yml, .github/workflows/rustdoc.yaml
Fix a missing credential for peaceiris/actions-gh-pages and remove the
CircleCI job.
=> Switch over to GitHub actions for rustdoc publish

.github/workflows/audit.yaml, .github/workflows/rustdoc.yaml
Triggering on pull_request meant some jobs only got kicked off
when PRs were 'synchronized', but not on initial creation.
=> Trigger workflows on push event

artichoke-backend/src/exception.rs, artichoke-backend/src/extn/core/exception/mod.rs, artichoke-backend/src/extn/core/kernel/integer.rs, artichoke-backend/src/extn/core/kernel/require.rs, artichoke-backend/src/extn/core/matchdata/element_reference.rs, artichoke-backend/src/string.rs, artichoke-frontend/src/bin/artichoke.rs, artichoke-frontend/src/ruby.rs
- Rename `string::escape_unicode` to
`string::format_unicode_debug_into`.
- Rename writer type parameters to `W` for int and unicode debug
formatters.
- Remove `&mut` from writer parameter.
- Remove the `impl From<fmt::Error> for WriteError` conversion.
- Sync docs for `format_unicode_debug_into` from BurntSushi/bstr#37.
While fixing up the use of `escape_unicode` in `artichoke-frontend`, I
got a bit distracted and let the scope of this change creep.
- Unify Ruby CLI errors on `Exception`. Imports `IOError` and
`LoadError` to manually construct some errors from strings.
- Do not use `eprintln!` in `artichoke` binary to suppress broken pipe
errors instead of panicking.
- Set exit code to 1 on error in `artichoke` binary.
=> Clean up string module

artichoke-backend/src/extn/core/float/mod.rs, artichoke-backend/src/extn/core/regexp/mruby.rs
`Float` and `Regexp` both define constants by string formatting `i64`s
and `f64`s  into a code string with `format!` and evaling it on the
interpreter. This is not ideal.
GH-526 added constant definition APIs to `artichoke-core` and
implemented them for `artichoke-backend`. This commit wires it up in
`extn`. The resulting code has more localized failures - errors are
reported on the granularity of defining a single constant. The constant
values are converted into proper `Value`s directly from their native
Rust form.
See also GH-27, the issue referenced by both of the TODOs (the TODO in
`float.rs` refers to the issue number from lopopolo/ferrocarril before
it was migrated to the artichoke/artichoke repo).
=> Use constant definition APIs from artichoke-core in extn

artichoke-backend/src/exception.rs
Remove a `panic!` from `exception::raise` by delegating to an mruby
lookup of the `RuntimeError` exception class which is infallible.
Long term, The Artichoke state should store a lazily initialized
reference to the `Fatal` exception type, which we would use here.
This commit uses `hint::unreachable_unchecked` instead of the panicking
`unreachable!` because this function is guaranteed to unwind.
=> Remove panicking branch from exception::raise

artichoke-backend/src/extn/core/kernel/mod.rs, artichoke-backend/src/state/mod.rs, artichoke-backend/src/state/output.rs, artichoke-backend/src/warn.rs
Refactor output capturing in the `State`. The `State` has methods for printing and overriding output behavior by capturing into a buffer.
Replace this with a single `output` field on the state that is a trait object pointing to a concrete output implementation. This PR includes three implementations, one that uses the native stdout and stderr of the process, one that captures stdout and stderr into two buffers, and one that drops all output.
This inches closer to a model where the `State` is just a container for components that hold domain specific state. See GH-442.
=> Refactor output capturing at the State

artichoke-backend/src/extn/core/array/mod.rs, artichoke-backend/src/extn/core/regexp/backend/lazy.rs, artichoke-backend/src/extn/core/regexp/backend/onig.rs, artichoke-backend/src/extn/core/regexp/backend/regex/utf8.rs
Implement `fmt::Display` and `RegexpType::debug` with `string::format_unicode_debug_into` for `Regexp` backends. This removes a `String::from_utf8_lossy` and some panicking pathways.
Replace calls to `format!` for string interpolation in `Array` impl to use a mutable `String` builder.
=> Remove some uses of format!

artichoke-backend/src/convert.rs, artichoke-backend/src/def.rs, artichoke-backend/src/exception.rs, artichoke-backend/src/exception_handler.rs, artichoke-backend/src/extn/core/exception/mod.rs, artichoke-backend/src/extn/core/kernel/mod.rs, artichoke-backend/src/extn/core/thread.rs, artichoke-backend/src/ffi.rs, artichoke-backend/src/interpreter.rs, artichoke-backend/src/io.rs, artichoke-backend/src/string.rs, artichoke-backend/src/value.rs, artichoke-backend/tests/leak_unbounded_arena_growth.rs, artichoke-frontend/src/repl.rs
This API was unused.
Modify `RubyException::vm_backtrace` to take `&mut Artichoke`.
=> Remove RubyException::box_clone

artichoke-frontend/src/bin/airb.rs, artichoke-frontend/src/parser.rs, artichoke-frontend/src/repl.rs
Binary:
- Write error `Display` to stderr.
- Exit with status code `1` on error.
Parser:
- Move `CodeTooLong` and and `TooManyLines` parser conditions from error
types into the `State` enum.
- Add `State::is_fatal` so the REPL loop can exit early.
- Store `NonNull` owning pointers in the `Parser` struct.
- Significantly shrink the size of the `unsafe` block in `Parser::parse`
by using the guarantees from the `NonNull` pointers.
REPL:
- Add `ParserAllocFailure` for failures to allocate the mruby parser.
- Add `ParserLineCountError` for `TooManyLines` parser state.
- Add `ParserInternalError` for fatal parser errors.
- Add `UnhandledReadlineError` for wrapping unknown `Err` variants from
`rustyline`.
- Use `Box<dyn Error>` as the error type in the REPL.
- Remove useless `continue` in match …
=> Refactor airb and REPL backend to modernize patterns

artichoke-backend/src/class.rs, artichoke-backend/src/extn/core/random/mod.rs, artichoke-backend/src/module.rs
- Use the `itoa` crate via `string::format_int_into` to replace interpolation of integers in `extn::core::random` implementation.
- Use string buffer builder instead of `format!` for concatenating strings and literals in `def` family of `fqname` implementations.
=> Replace some instances of format! panic-free variants

.github/workflows/audit.yaml
Use a blessed build instead of compiling from source. This should
speed up this workflow significantly and remove a failure mode
(compilation failures from mismatched stable compiler and public
release).
=> Install cargo-deny from public GitHub release

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-backend/src/extn/core/random/mod.rs, artichoke-backend/src/extn/stdlib/mod.rs, artichoke-backend/src/extn/stdlib/securerandom/mod.rs, artichoke-backend/src/extn/stdlib/securerandom/mruby.rs, artichoke-backend/src/extn/stdlib/securerandom/trampoline.rs, artichoke-backend/src/value.rs, spec-runner/enforced-specs.yaml
Based on rand::thread_rng, hex crate, base64 crate, uuid crate.
This implementation of `SecureRandom` supports these APIs:
- `SecureRandom::alphanumeric`
- `SecureRandom::base64`
- `SecureRandom::hex`
- `SecureRandom::random_bytes`
- `SecureRandom::random_number`
- `SecureRandom::uuid`
Fixes GH-34.
I am pleasantly surprised how little code it took to achieve this 😄
=> Add SecureRandom implementation

artichoke-backend/src/extn/stdlib/securerandom/mod.rs
`rand` has a `CryptoRng` marker trait that is added to PRNGs that are
cryptographically secure. `ThreadRng`, which is returned by the
currently used `rand::thread_rng` API is a `CryptoRng`.
Add a test to assert the `CryptoRng` bound on `rand::thread_rng`.
Inspired by this twitter thread:
https://twitter.com/rsthau/status/1234824812490563585
Followup to GH-554.
=> Add a test to ensure the SecureRandom uses a CSPRNG

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-backend/build.rs
The functionality for copying directories and enumerating source files
recursively was not that hard to implement with `std::fs`.
=> Remove fs_extra and walkdir build-dependencies in artichoke-backend

artichoke-backend/src/extn/core/regexp/backend/lazy.rs, artichoke-backend/src/extn/core/regexp/backend/mod.rs, artichoke-backend/src/extn/core/regexp/backend/onig.rs, artichoke-backend/src/extn/core/regexp/backend/regex/utf8.rs, artichoke-backend/src/extn/core/regexp/mod.rs, artichoke-backend/src/state/mod.rs
When prototyping the `Regexp` module with APIs for getting and setting
global variables, I made these changes as well. They are worthy of their
own commit and were making the diff hard to reason about.
- Rename all parameters named `pattern` that are really `haystack`.
- `regexp::nth_match_group` takes a `NonZeroUsize`.
- Remove `panic!` for `0` case in `regexp::nth_match_group`.
- Add `regexp::clear_capture_globals` API.
- `active_regexp_globals` on the interpreter `State` is now an
`Option<NoNonZeroUsize>`.
I tried to make `regexp::nth_match_group` return a `Cow<'static, str>`
since I am planning for constant names to be `&str`, but translating
this `Cow` to the `[u8]` `Cow` expected by `intern_symbol` was invasive
and the change is expected to be undone. Skipping for now.
This is prep …
=> Prepare Regexp module for global variable APIs

Cargo.toml
- Remove debug symbols
- Build with codegen-units = 1
The resulting binaries are about 10% smaller at similar performance.
```console
$ ls -la target/release/{airb,artichoke,spec-runner}
-rwxr-xr-x  2 lopopolo  staff   4.1M Mar  4 18:42 target/release/airb*
-rwxr-xr-x  2 lopopolo  staff   4.3M Mar  4 18:42 target/release/artichoke*
-rwxr-xr-x  2 lopopolo  staff    11M Mar  4 18:43 target/release/spec-runner*
```
```console
$ ls -la target/release/{airb,artichoke,spec-runner}
-rwxr-xr-x  2 lopopolo  staff   3.8M Mar  4 18:48 target/release/airb*
-rwxr-xr-x  2 lopopolo  staff   4.0M Mar  4 18:48 target/release/artichoke*
-rwxr-xr-x  2 lopopolo  staff    11M Mar  4 18:50 target/release/spec-runner*
```
`spec-runner` is unchanged because its size is dominated by the mspec and ruby/spec source …
=> Optimize Cargo release profile

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-backend/src/extn/core/integer/mod.rs, artichoke-backend/src/extn/core/math/mod.rs, artichoke-backend/src/extn/core/math/mruby.rs, artichoke-backend/src/extn/core/mod.rs, artichoke-backend/src/intern.rs, artichoke-backend/src/sys/mod.rs, artichoke-backend/vendor/mruby/src/vm.c, spec-runner/enforced-specs.yaml
Add a complete implementation of the `Math` module in Ruby Core.
Most functions in `Math` can be implemented with using `std`. Some functions, like `ldexp` and `erf` are not implemented in `std`. These functions are by default implemented to raise `NotImplementedError`.
`artichoke-backend` adds a new feature `core-math-extra` which is optional but enabled by default. This feature pulls in a dependency on `libm`, a pure Rust implementation of math functions in `musl`.
Some functions require `Bigint` support to pass ruby/spec.
The implementation of `Math::gamma` required inspiration from CRuby's implementation.
This PR fixes a segfault from improper assumption of lifetimes in `Intern::intern_symbol`.
This PR adds proper `Float` coercion behavior for `Numeric` subclasses to integer division. …
=> Add Math module implementation from Ruby Core

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-backend/src/convert/object.rs, artichoke-backend/src/extn/core/array/args.rs, artichoke-backend/src/extn/core/kernel/integer.rs, artichoke-backend/src/extn/core/matchdata/begin.rs, artichoke-backend/src/extn/core/matchdata/end.rs, artichoke-backend/src/extn/core/random/mod.rs, artichoke-backend/src/string.rs, artichoke-backend/src/value.rs, artichoke-backend/tests/leak_unbounded_arena_growth.rs
Replace all usage of the `format!` macro in non-test and non-build code
to use either:
- mutable `String` builder with `push` and `push_str` for concatenation
use cases.
- `string::format_int_into` + `String` builder for interpolating integer
values.
- `string::write_float_into` + `String` builder for interpolating float
values.
This PR adds a dependency on `dtoa` in artichoke-backend. This dep is
the float equivalent of `itoa` that was added in GH-547.
This PR continues the work in GH-547.
This type of formatting is predominantly used when building `Exception`
messages, so the performance speed up will not be noticable.
Filed dtolnay/dtoa#18 to investigate adding a `dtoa::fmt` variant to
make the `string` API similar to `format_int_into`, which can take a
`String`.
This commit removes …
=> Replace all usage of format! macro with panic-free alternatives

artichoke-backend/src/extn/core/random/backend/rand.rs, artichoke-backend/src/extn/core/random/mod.rs, artichoke-backend/src/extn/stdlib/securerandom/mod.rs, artichoke-backend/src/state/prng.rs
- `#[inline]` annotate a bunch of short functions.
- Use `Rng::gen_range` instead of sampling a distribution for
single-shot `Rng` use because `gen_range` is optimized for this use
case.
- Short circuit when requested byte length is zero instead of allocating
an empty buffer and invoking the RNG.
- Use `RngCore::try_fill_bytes` whenever possible since we can propagate
its failures as `RuntimeError`s instead of panicking.
- Simplify byte length calculations to only do one `usize` check in
`SecureRandom`. Parse, don't validate!
- Unchain `hex` and `base64` functions in `SecureRandom` for
readability.
=> Optimize random and securerandom implementations

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-backend/src/extn/core/array/backend/mod.rs, artichoke-backend/src/extn/core/array/inline_buffer.rs, artichoke-backend/src/extn/core/env/backend/memory.rs, artichoke-backend/src/extn/core/env/backend/mod.rs, artichoke-backend/src/extn/core/env/backend/system.rs, artichoke-backend/src/extn/core/env/mod.rs, artichoke-backend/src/extn/core/random/backend/default.rs, artichoke-backend/src/extn/core/random/backend/mod.rs, artichoke-backend/src/extn/core/random/backend/rand.rs, artichoke-backend/src/extn/core/random/mod.rs, artichoke-backend/src/extn/core/time/backend/chrono.rs, artichoke-backend/src/extn/core/time/backend/mod.rs, artichoke-backend/src/extn/core/time/mod.rs, artichoke-backend/src/extn/core/time/trampoline.rs, artichoke-backend/src/lib.rs, artichoke-backend/src/state/mod.rs, artichoke-backend/src/state/output.rs, artichoke-backend/src/state/prng.rs
This commit removes the `downcast` dependency from `artichoke-backend`
and replaces all instances of downcasting trait objects with dynamically
dispatched APIs.
One common use for downcasting in Artichoke was to get a concrete type
to feed into a `debug_struct` invocation in a `Debug` implementation.
This pattern can be used by adding a `fn as_debug(&self) -> &dyn fmt::Debug`
method to the trait definition, allowing concrete implementations of a
trait to forward their debug impls.
`ArrayType` used downcasting to specialize some operations for
`InlineBuffer` types. `ArrayType` is kept for compatibility and for the
medium term I expect `InlineBuffer` to remain the only implementation.
This PR reallocates a temporary `InlineBuffer` to make the
implementation work for all `ArrayType`s. …
=> Remove downcast dependency and all use of Any

artichoke-backend/build.rs, artichoke-backend/src/class.rs, artichoke-backend/src/constant.rs, artichoke-backend/src/def.rs, artichoke-backend/src/exception_handler.rs, artichoke-backend/src/extn/core/array/inline_buffer.rs, artichoke-backend/src/extn/stdlib/securerandom/mod.rs, artichoke-backend/src/extn/stdlib/securerandom/trampoline.rs, artichoke-backend/src/module.rs, artichoke-backend/src/sys/protect.rs, artichoke-backend/tests/leak/mod.rs, artichoke-core/src/constant.rs
- Convert inline type bounds to where clauses. Skip functions with a
single `AsRef<Path>` parameter or `Hasher` parameter.
- Fix `PartialEq` implementation for `class::Spec` and `module::Spec` to
compare fully qualified type names instead of local names.
- Add address of null pointer in panic branch of `def::rust_data_free`.
- Move `mrb->exc` pointer reset from exception handler to protect base
function. Exception handler now has no unsafe or pointer code.
- Leak gauge takes `Into<String>` instead of `AsRef<str>` since it
requires an owned `String`.
- Simplify computation of byte `len` in `SecureRandom` by using a
multi-branch match statement.
- Make `SecureRandom` functions free functions instead of associated
functions.
- Simplify implementation of some `FromIterator` traits in …
=> Some small refactorings and cleanups

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-backend/src/extn/core/mod.rs, artichoke-backend/src/extn/core/random/backend/rand.rs, artichoke-backend/src/extn/stdlib/mod.rs, artichoke-backend/src/state/mod.rs, artichoke-backend/src/state/prng.rs
Split the features for randomness APIs. This PR removes the
`artichoke-random` feature and replaces it with:
- `core-random`: gates the implementation of the `Random` core class.
Depends only on `rand` and `small_rng` crates.
- `stdlib-securerandom`: gates the implementation of the `SecureRandom`
module in the standard library. Depends on `rand`, `hex`, `base64`,
and `uuid`.
This PR aligns feature names with those of core `Math` and core `ENV`.
It makes it possible to depend either on a fast predictable RNG or a
CSPRNG or both with minimal dependency footprint.
To enable depending only on `rand` without the `small_rng` feature when
only enabling the `stdlib-securerandom` feature, `small_rng` is pulled
in as a top-level dependency instead of by a feature on `rand`.
=> Rename features for Random core class and SecureRandom stdlib module

.github/workflows/audit.yaml, .github/workflows/ci.yaml, .github/workflows/rustdoc.yaml
Only run workflows on pushes to master or PRs to master.
Also run workflows on  a schedule every Tuesday at midnight.
=> Ensure GitHub Actions with required checks run on external PRs

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-frontend/Cargo.toml
Disable `bstr` `unicode` cargo feature since it is unused in
`artichoke-backend`. This change removes some dependencies of `bstr`
from the `Cargo.lock` file.
Remove `bstr` dependency from `artichoke-frontend`. This dependency
likely has not been used since the introduction of the `string` module
in `artichoke-backend`.
=> Disable unicode cargo feature in bstr

Cargo.lock, artichoke-frontend/Cargo.toml
Disable `rustyline` `with-dirs` feature since it is unused in
`artichoke-frontend`. This change removes some dependencies of
`rustyline` from the `Cargo.lock`.
The `with-dirs` feature of `rustyline` activates tab completion behavior
for paths that start with `~`. `airb` uses `rustyline` to input Ruby
source code, not paths, so this optional feature is not being used.
=> Disable with-dirs cargo feature in rustyline

artichoke-backend/src/convert/bytes.rs, artichoke-backend/src/extn/core/env/backend/system.rs, artichoke-backend/src/extn/core/kernel/require.rs, artichoke-backend/src/ffi.rs
- Add   TryConvertMut` impls for `OsString` and `&OsStr`.
- Add `ffi` function for converting directly from owned `OsString` to
owned `Vec<u8>`.
- Directly convert owned string sin `env::backend::system`.
Follow up to GH-572.
=> Improve support for OsStrings in artichoke-backend

README.md
Artichoke repo is a workspace with multiple binary targets. cargo
install needs to know to install the artichoke crate.
=> Fix cargo install snippet

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-backend/src/extn/stdlib/securerandom/mod.rs
Brings in 
> Relaxed type restrictions to just AsRef<[ut8]> for main encode*/decode* functions
This matches `hex`, already in use in `securerandom`.
=> Upgrade to base64 0.12.0

artichoke-backend/src/class.rs, artichoke-backend/src/extn/stdlib/securerandom/mruby.rs, artichoke-backend/src/lib.rs, artichoke-backend/src/module.rs, artichoke-backend/src/sys/mod.rs, artichoke-core/src/lib.rs, src/lib.rs
- Turn all deny pragmas into warn pragmas
- Add missing_debug_implementations warning.
- Add missing debug impls.
- Add doc html_root annotations to artichoke-core and artichoke-backend.
- Remove license blurb from artichoke-core crate-level docs.
- Remove license blurb from artichoke-backend crate-level docs.
- Fix typos in artichoke crate-level docs.
- Add docs on available features to artichoke crate-level docs.
=> Doc cleanup

.github/workflows/ci.yaml
This test is flakey and is subject to rate limits. Remove for now
and run manually when prepping for releases.
=> Remove validate-links build step from CI workflow

artichoke-backend/build.rs, artichoke-backend/mruby_build_config_null.rb, artichoke-backend/vendor/mruby/lib/mruby/build/command.rb
I am able to successfully build Artichoke when the build path contains a space:
```console
Compiling artichoke v0.1.0-pre.0 (/Users/lopopolo/dev/repos/a space/artichoke)
Finished dev [unoptimized + debuginfo] target(s) in 38.06s
```
See GH-591.
This issue was caused by two bugs:
- the mruby build tooling to invoke `bison` (`win_bison` on Windows) did not quote filenames when formatting command line flags.
- Artichoke nulls out all other parts of the mruby build toolchain with a NOOP script that looks like `ruby /absolute/path/to/build/dir/empty_ruby_script.rb`. This command string was not shell escaped.
The fix is to use the Ruby `shellwords` module to escape and quote these commands and parameters in this two locations.
=> Fix artichoke-backend build failure when build path contains a space

artichoke-backend/src/extn/core/random/backend/rand.rs, artichoke-backend/src/extn/core/string/trampoline.rs, artichoke-backend/src/state/prng.rs
- rand_pcg does conditional pub based on target os and pointer width
- lossless convert from u32 is not supported on targets with i32 int
`uuid` v4 feature requires wiring through additional features to connect
to a runtime. Skipping for now.
=> Fix compilation errors on emscripten target

.github/workflows/ci.yaml, Cargo.toml
We are proxying all of artichoke-backend's features and setting them as default
in artichoke's Cargo.toml.
Add this test to CI.
=> Disable default features for artichoke-backend dependency in artichoke

Cargo.toml, artichoke-backend/Cargo.toml, artichoke-backend/src/extn/core/kernel/mod.rs, artichoke-backend/src/state/mod.rs, artichoke-backend/src/state/output.rs, artichoke-backend/src/warn.rs
By default use Process stdout and stdio. Allow overriding to a capture
buffer or null.
Use compile time features to use a concrete type in the State struct and
avoid infecting everything with lifetimes to allow a &mut Capture reference.
This will make the playground easier to integrate with the new approach.
=> Add compile time features for selecting output strategy

artichoke-backend/build.rs
This is 80MB of source that doesn't need to be copied for every build.
The existing behavior has the consequence of making the target directory
huge after a few builds.
These build steps are no longer required due to https://github.com/artichoke/artichoke/pull/581.
=> Stop copying vendored ruby tree into build directory

artichoke-backend/src/extn/core/array/args.rs, artichoke-backend/src/extn/core/array/array.rb, artichoke-backend/src/extn/core/array/inline_buffer_test.rb, artichoke-backend/src/extn/core/array/mod.rs
This commit helps Artichoke pass 10 more Array ruby/specs.
This commit sweeps through the Array implementation for all conversions
between `Int` and `usize` and improves handling of the conversion.
- Remove many `Fatal` errors by coalescing index transforms into
`Option` chains.
- Parse positive values first, handle negative values second.
- Use `checked_neg` when transforming `Int` to handle `Int::MIN`.
This commit properly handles returning `nil` for out of range `Array#[]`
indexes.
This commit marks known bad parts of `Range` extraction.
This commit improves the `Array#==` implementation to handle types that
don't implement `Comparable`.
=> Improve handling of Array indexes

artichoke-backend/build.rs, artichoke-backend/src/convert.rs, artichoke-backend/src/convert/fixnum.rs, artichoke-backend/src/extn/core/string/trampoline.rs, artichoke-backend/src/extn/core/time/trampoline.rs, artichoke-backend/src/types.rs
This PR simplifies Artichoke's numeric tower by using `i64` as the
Fixnum backend on all targets. This removes conditional compilation of
the `Int` type alias for `wasm32` targets and adds tests to assert that
`Int` is `i64`.
This change simplifies the implementation of integer converters by
allowing all targets to use lossless converters for `u32`. This change
is propagated to all `extn` callsites and partially undoes GH-596.
`build.rs` is modified to always pass `MRB_INT64` when compiling mruby
so Artichoke can safely assume all builds use `i64` `Fixnum`.
Because this change removes a source of platform-divergence, it helps
reduce the need for GH-413.
This PR cleans up the tests for the fixnum converter and annotates all
of the passthrough converters with `#[inline]`.
=> Use i64 for Fixnum backend on all targets

artichoke-backend/src/extn/core/integer/mod.rs, artichoke-backend/src/extn/core/integer/trampoline.rs
This commit tries to formalize the idea of what the `trampoline` modules
in `extn` are useful for. I propose all core `extn` APIs accept native
types as parameters and return native types. `trampoline` modules are
responsible for boxing and unboxing values as the glue layer between the
core and the Ruby VM.
This commit tries this approach out on the `Integer` module.
=> Experiment with using trampoline modules as a VM compat layer

src/ruby.rs
Submitted for review to address issue https://github.com/artichoke/artichoke/issues/478
Please let me know if there is a suggestion for a test that would cover this change that I could add.
=> Print backtraces of top-level exceptions in ruby frontend #478

artichoke-backend/src/extn/core/hash/hash.rb, src/bin/artichoke.rs, src/repl.rs, src/ruby.rs
This commit adds some polish to backtrace printing. Followup to GH-594.
- Fix case of `KeyError` message returned from `Hash#fetch`.
- Set exit code on exception in artichoke endpoint even if backtrace is
successfully printed.
- Clean up imports.
- Use new globals APIs instead of delegating to `sys`, GH-562.
- Rename `handle_exception` to `format_backtrace_into` and pass an
`io::Write`.
- Make `format_backtrace_into` public.
- Reorder exception message and exception name in output.
- Print top frame with no indent like MRI.
=> Address followups to GH-594 artichoke entrypoint backtrace formatting

src/backtrace.rs, src/bin/artichoke.rs, src/lib.rs, src/parser.rs, src/repl.rs, src/ruby.rs
- Parameterize `ruby::entrypoint` by input and error streams.
- Move backtrace printers to the `backtrace` module.
- Extract fixture setup to one place so it is easier to remove when the
time comes.
- Add `AsRef` generic parameters where appropriate.
- Use `Option::as_deref` in a few places for cleaner code.
=> Refactor frontend code

artichoke-backend/src/extn/core/float/mod.rs
https://ruby-doc.org/core-2.6.3/Float.html
The only one that was not straightforward to set was `Float::ROUNDS` since Rust does not specify its float rounding direction.
=> Initialize all Float constants

artichoke-backend/src/convert/array.rs, artichoke-backend/src/extn/core/regexp/backend/lazy.rs, artichoke-backend/src/extn/core/regexp/backend/mod.rs, artichoke-backend/src/extn/core/regexp/backend/onig.rs, artichoke-backend/src/extn/core/regexp/backend/regex/utf8.rs, artichoke-backend/src/extn/core/regexp/mod.rs, artichoke-backend/src/extn/core/string/trampoline.rs
Continuation of GH-605. Push conversions of `RegexpType` parameters and outputs out to the trampoline layer in `Regexp` and `String`.
This PR changes the signatures for the internals of `Regexp#=~`, `Regexp#named_captures`, and `String#scan`.
This approach continues to simplify the implementation of the core types and makes them easier to call as standalone APIs.
This code picks up the `pos` and `usize` handling improvements of GH-600 and applies them to `Regexp` and its backends.
This commit fixes a bug where `$&` was not unset if there was no match.
=> Trampoline as VM Compat Layer: Regexp

artichoke-backend/src/extn/core/float/mod.rs, artichoke-backend/src/extn/core/integer/mod.rs, artichoke-backend/src/extn/core/integer/mruby.rs, artichoke-backend/src/extn/core/integer/trampoline.rs, artichoke-backend/src/extn/core/numeric/mod.rs, artichoke-backend/src/types.rs, artichoke-backend/vendor/mruby/src/vm.c
This PR pokes around in the numeric core classes. The intent is to implement `Integer`, `Float`, and `Numeric` in Rust.
To achieve this, the `Integer` and `Float` types in `extn::core` are now tuple structs that wrap and underlying primitive type. Ruby core APIs are dangled off this struct. These structs have `Convert`, `ConvertMut`, and `TryConvert` support.
This PR implements `numeric::coerce` which drives all of the numeric conversions in `numeric.c` in MRI.
This PR implements `Float#%` using the new converter and container types. Coercions require returning an arbitrary numeric type from any arithmetic operations, which is represented by `numeric::Outcome` sum type.
1 additional Integer divide spec passes due to this PR.
=> Implement Numeric coercion

artichoke-backend/src/convert/array.rs, artichoke-backend/src/convert/boolean.rs, artichoke-backend/src/convert/bytes.rs, artichoke-backend/src/convert/fixnum.rs, artichoke-backend/src/convert/float.rs, artichoke-backend/src/convert/hash.rs, artichoke-backend/src/convert/string.rs
- Add quickcheck coverage for Array and Hash.
- Add a functional test for Bytes using quickcheck.
- Add a functional test for String using quickcheck.
- Convert all `expect` to `unwrap`.
=> Improve converter test coverage

artichoke-backend/src/extn/core/regexp/mod.rs
This change is necessary to support GH-442, where all implicit
conversions will take in `interp` and the lifetime of the returned
string will be bound to the interpreter.
This PR also changes the exception message for invalid UTF-8 to be more
terse like CRuby tends to be.
=> Refactor pattern parsing in Regexp to drop temporary on error branch

artichoke-backend/src/extn/core/random/mod.rs, artichoke-backend/src/extn/core/random/mruby.rs, artichoke-backend/src/extn/core/random/trampoline.rs, artichoke-backend/src/extn/stdlib/securerandom/mod.rs, artichoke-backend/src/extn/stdlib/securerandom/trampoline.rs
Return native types from SecureRandom functions.
This PR introduces a new pattern where API parameters are concrete types
that can be parsed from an incoming VM arg with `TryConvert`.
This PR introduces a new pattern where API reuslts are concrete types
that can be returned into the VM with `Convert` and `ConvertMut`
implementations.
This PR introduces a trampoline module to `core::random` similarly to the `securerandom` trampoline.
Related to GH-605.
=> Use Random and SecureRandom trampolines as VM compat layer

artichoke-backend/src/extn/core/matchdata/begin.rs, artichoke-backend/src/extn/core/matchdata/end.rs, artichoke-backend/src/extn/core/matchdata/length.rs, artichoke-backend/src/extn/core/matchdata/mod.rs, artichoke-backend/src/extn/core/matchdata/names.rs, artichoke-backend/src/extn/core/regexp/backend/lazy.rs, artichoke-backend/src/extn/core/regexp/backend/mod.rs, artichoke-backend/src/extn/core/regexp/backend/onig.rs, artichoke-backend/src/extn/core/regexp/backend/regex/utf8.rs, artichoke-backend/src/extn/core/regexp/mod.rs, artichoke-backend/src/extn/core/regexp/mruby.rs, artichoke-backend/src/extn/core/regexp/trampoline.rs, artichoke-backend/src/extn/core/string/trampoline.rs
Followup to GH-607 by extending the native types to the `Regexp` API
instead of stopping at `RegexpType`. These changes are necessary for
refactoring `MatchData` to use modern patterns.
This PR uses the same tricks introduced in GH-610 to use the converter
infra to parse arguments out of a VM `Value`.
Related to GH-605.
=> Use Regexp trampoline as a VM compat layer

artichoke-backend/src/extn/core/matchdata/args.rs, artichoke-backend/src/extn/core/matchdata/mod.rs, artichoke-backend/src/extn/core/matchdata/mruby.rs, artichoke-backend/src/extn/core/matchdata/trampoline.rs, artichoke-backend/src/extn/core/mod.rs, artichoke-backend/src/extn/core/regexp/backend/onig.rs, artichoke-backend/src/extn/core/regexp/backend/regex/utf8.rs, artichoke-backend/src/extn/core/string/trampoline.rs
`Regexp` and `MatchData` were the first two `extn` modules. `MatchData`
had mruby C trampolines as associated functions on the main type and one
module per trampoline. While `Regexp` was rewritten and updated to
support multiple backends, `MatchData` has aged.
This PR rewrites `MatchData` from scratch, incorporating the patterns
from GH-605 and GH-610 as well as the updates to `Regexp` in GH-607 and
GH-617.
Significant changes below (unordered):
- Unsafe `is_range` helper moved to private `matchdata::args` module.
- `Region` stores `start` and `end` as `Bound<usize>`.
- `Region` derives `Debug`, `Clone`, `Copy`, `Hash`, `PartialEq`, `Eq`.
- `Region::from_range(range: R)` where `R: RangeBounds<usize>`.
- `Region::offset` to compute offset into the haystack.
- `impl RangeBounds<usize> for …
=> Reimplement MatchData using modern patterns

artichoke-backend/src/extn/core/array/args.rs, artichoke-backend/src/extn/core/array/mod.rs, artichoke-backend/src/extn/core/array/mruby.rs, artichoke-backend/src/extn/core/array/trampoline.rs, artichoke-backend/src/extn/core/env/mod.rs, artichoke-backend/src/extn/core/integer/mod.rs, artichoke-backend/src/extn/core/integer/trampoline.rs, artichoke-backend/src/extn/core/kernel/integer.rs, artichoke-backend/src/extn/core/kernel/mod.rs, artichoke-backend/src/extn/core/kernel/require.rs, artichoke-backend/src/extn/core/matchdata/mod.rs, artichoke-backend/src/extn/core/matchdata/trampoline.rs, artichoke-backend/src/extn/core/math/mod.rs, artichoke-backend/src/extn/core/random/mod.rs, artichoke-backend/src/extn/core/random/trampoline.rs, artichoke-backend/src/extn/core/regexp/mod.rs, artichoke-backend/src/extn/core/regexp/trampoline.rs, artichoke-backend/src/extn/core/string/trampoline.rs, artichoke-backend/src/extn/stdlib/securerandom/mod.rs, artichoke-backend/src/extn/stdlib/securerandom/trampoline.rs, artichoke-backend/src/value.rs
Add a `&mut Artichoke` parameter to `Value::implicitly_convert_to_int`, `Value::implicitly_convert_to_string`, and `Value::implicitly_convert_to_nilable_string`.
These API changes are required to address GH-442.
The `&mut` part of the additional parameter is required because these implicit conversions bottom out in `Value::funcall`, which will require mutability to move the interpreter back into the `mrb_state`.
The changes introduced in GH-605 limited the scope of these changes mostly to trampolines (or functions that act as trampolines) and polymorphic functions that haven't been migrated to sum types parsed using `TryConvert` yet.
This change refactors `implicitly_convert_to_nilable_string` to be a wrapper around `implicitly_convert_to_string` with a `nil` check.
The arg conversion …
=> Add interpreter parameter to implicit conversions on Value

artichoke-backend/src/extn/core/array/args.rs, artichoke-backend/src/extn/core/array/ffi.rs, artichoke-backend/src/extn/core/array/mod.rs, artichoke-backend/src/extn/core/array/mruby.rs, artichoke-backend/src/extn/core/array/trampoline.rs, artichoke-backend/src/extn/core/kernel/integer.rs, artichoke-backend/src/extn/core/matchdata/trampoline.rs, artichoke-backend/src/extn/core/math/mod.rs, artichoke-backend/src/extn/core/numeric/mod.rs, artichoke-backend/src/extn/core/string/trampoline.rs, artichoke-backend/src/gc.rs, artichoke-backend/src/value.rs, artichoke-backend/tests/leak_unbounded_arena_growth.rs
Add `&mut Artichoke` parameter to all methods on `Value` that are on the
bare `impl` block.
Most of the updates in `extn` and elsewhere came from the change to
`Value::pretty_name`'s signature.
This commit refactors `Value::pretty_name` to minimize conversions.
This PR removes:
- `impl fmt::Display for Value`
- `Value::protect`
- `Value::to_s_debug`
`Value` now requires an interpreter to print out anything useful about
itself, so the `fmt::Debug` implementation only includes info about the
`Ruby` type of the value using a simple `debug_struct` formatter.
Follow up to GH-621 and required for GH-442.
=> Add &mut Artichoke parameter to all Value methods

src/repl.rs
Audit uses of the `write!` macro. One use of `write!` in the REPL
frontend should be a `writeln!` instead.
=> Output full line on recoverable parser error

artichoke-backend/src/exception.rs, artichoke-backend/src/exception_handler.rs, artichoke-backend/src/extn/core/exception/mod.rs, artichoke-backend/src/extn/core/matchdata/mod.rs, artichoke-backend/src/extn/core/regexp/mod.rs, artichoke-backend/src/state/output.rs
`&BStr` and `BString` come with conventional UTF-8 decoding debug impls, which means we can replace private `Vec<u8>` struct fields with `BString` to get a more usable `fmt::Debug` derived impl for free with no loss of functionality or other code changes because of the `Deref` and `DerefMut` impls to `Vec`.
=> Use BString struct fields where possible to get better debug impls

.github/workflows/audit.yaml, .github/workflows/ci.yaml, .github/workflows/fuzz.yaml, .github/workflows/rustdoc.yaml
Remove actions/setup-node. Artichoke build just depends on some recent
node, not a specific node. The runner images already include node 12, so
this build step is redundant and introduces flakiness by depending on
npm infrastructure.
Replace actions/setup-ruby with ruby/setup-ruby. The official Ruby
action is speedier, has no external dependencies, and supports reading
an exact Ruby version out of the `.ruby-version` file in Artichoke root.
=> Improve reliability of setup program lang actions

artichoke-backend/build.rs
I was trying to build artichoke on my machine. However even though my rustc version matches the one in toolchain file, I was still getting an error:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', artichoke-backend/build.rs:463:26
stack backtrace:
0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
1: core::fmt::write
2: std::io::Write::write_fmt
3: std::panicking::default_hook::{{closure}}
4: std::panicking::default_hook
5: std::panicking::rust_panic_with_hook
6: rust_begin_unwind
7: core::panicking::panic_fmt
8: core::panicking::panic
9: core::option::Option<T>::unwrap
at /build/rust/src/rustc-1.42.0-src/src/libcore/macros/mod.rs:10
10: build_script_build::release::compiler_version
at artichoke-backend/build.rs:463
11: …
```
=> Allow building when there is no commit info for rustc

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-backend/build.rs
Prevent the artichoke-backend build from failing if:
- Artichoke is not being built in a copy of its git repository.
- `rustc` version metadata cannot be read.
This PR replaces the subprocess calls to `git` with calls using the `libgit2` bindings.
Followup to GH-637.
=> Fallible artichoke backend build steps

artichoke-backend/build.rs
#639 introduced some formatting bugs when using timezone-aware date times.
Remove an unnecessary set of sorting options on revwalk for master revision count.
=> Fixup date handling in artichoke-backend build.rs

artichoke-backend/src/convert/float.rs, artichoke-backend/src/extn/core/float/mod.rs, artichoke-backend/src/extn/core/integer/mod.rs, artichoke-backend/src/extn/core/math/mod.rs, artichoke-backend/src/extn/core/numeric/mod.rs, artichoke-backend/src/extn/core/random/backend/default.rs, artichoke-backend/src/extn/core/random/backend/mod.rs, artichoke-backend/src/extn/core/random/backend/rand.rs, artichoke-backend/src/extn/core/random/mod.rs, artichoke-backend/src/extn/prelude.rs, artichoke-backend/src/extn/stdlib/securerandom/mod.rs, artichoke-backend/src/state/prng.rs, artichoke-backend/src/test/prelude.rs, artichoke-backend/src/types.rs
There was confusion where both the primitive alias and `Float` class
implementation were in scope.
=> Rename types::Float alias to types::Fp

artichoke-backend/src/convert/array.rs, artichoke-backend/src/convert/hash.rs, artichoke-backend/src/convert/object.rs, artichoke-backend/src/exception.rs, artichoke-backend/src/extn/core/array/ffi.rs, artichoke-backend/src/extn/core/array/mruby.rs, artichoke-backend/src/extn/core/array/trampoline.rs, artichoke-backend/src/extn/core/env/mod.rs, artichoke-backend/src/extn/core/env/mruby.rs, artichoke-backend/src/extn/core/kernel/trampoline.rs, artichoke-backend/src/extn/core/numeric/mod.rs, artichoke-backend/src/extn/core/time/mruby.rs, artichoke-backend/src/extn/core/time/trampoline.rs, artichoke-backend/src/value.rs, artichoke-backend/tests/leak_mrb_tt_data_rc.rs, artichoke-backend/tests/manual.rs, artichoke-backend/tests/obj_new_borrow_mut.rs, artichoke-core/src/value.rs
To prepare for closing out GH-442, the data converters need access to a
raw interpreter, which will require exclusive access.
This PR takes care of the last stragglers in the extn trampolines that
did not take `&mut Artichoke`.
This PR introduces `TryConvertMut` implementations from `Value` to a
Rust type. This introduces a split in APIs that perform conversions
automatically based on a type parameter. This PR introduces
`Value::try_into_mut` but does not introduce the corresponding
`Value::funcall_mut`.
=> Take mutable reference to an interpreter in RustBackedValue

.github/workflows/audit.yaml, .github/workflows/ci.yaml, CONTRIBUTING.md, Rakefile, package.json
- Remove `strategy.fail-fast` configution in GitHub Actions workflows
where there is no matrix.
- Check YAML formatting in CI.
- Update text formatting CI job with Prettier 2.0-style globs.
- Clean up some copy in `CONTRIBUTING.md`.
- Add `rake lint:clippy`. This rake task touches all lib and binary
source roots to force a clippy run. Fixes GH-638.
- Add `rake test`. Now that the Cargo workspace in this repo is not
virtual, I always forget to add the `--workspace` argument when
invoking `cargo test`. `rake test` is short to type and does the right
thing.
- Move prettier formatting script definitions to `package.json` npm
scripts. Invoke `npm run fmt:all` from `Rakefile`.
=> Fixes to build and linter

artichoke-backend/src/extn/core/kernel/kernel_test.rb, artichoke-backend/src/extn/core/kernel/mruby.rs, artichoke-backend/src/extn/core/kernel/trampoline.rs
Fixes #440 
I've taken a stab at implementing the `p` method in the `trampoline` of the `Kernel` module. Looking at the implementation of MRI it looks like this method is used to debug Ruby objects from C so I felt the the trampoline was a good place for it.
I also wasn't sure on how to get this under test. For the time being I added it to the `Kernel` module integration tests. I ran it against the Rubyspec tests but there were quite a few prerequisites required to run.
Let me know what you think. I'm a Rust beginner and new to working with interpreters in general, so I'm totally willing to re-work this in pure Ruby as well if the trampoline isn't a good place for this.
=> Implement Kernel#p as a trampoline method similar to Kernel#puts

artichoke-backend/src/eval.rs, artichoke-backend/src/extn/core/kernel/mod.rs, artichoke-backend/src/extn/core/thread/mod.rs, artichoke-backend/src/extn/stdlib/abbrev/mod.rs, artichoke-backend/src/extn/stdlib/cmath/mod.rs, artichoke-backend/src/extn/stdlib/delegate/mod.rs, artichoke-backend/src/extn/stdlib/forwardable/mod.rs, artichoke-backend/src/extn/stdlib/json/mod.rs, artichoke-backend/src/extn/stdlib/monitor/mod.rs, artichoke-backend/src/extn/stdlib/ostruct/mod.rs, artichoke-backend/src/extn/stdlib/securerandom/mruby.rs, artichoke-backend/src/extn/stdlib/set/mod.rs, artichoke-backend/src/extn/stdlib/shellwords/mod.rs, artichoke-backend/src/extn/stdlib/strscan/mod.rs, artichoke-backend/src/extn/stdlib/time/mod.rs, artichoke-backend/src/extn/stdlib/uri/mod.rs, artichoke-backend/src/load.rs, artichoke-backend/tests/leak_mrb_tt_data_rc.rs, artichoke-backend/tests/manual.rs, artichoke-core/src/load.rs, spec-runner/src/main.rs, spec-runner/src/mspec.rs, spec-runner/src/rubyspec.rs
In practice these APIs are called when a `Path` is already in context
which requires marshalling to bytes only to undo that by marshalling
back to `Path`.
Converting the filename argument to be a `Path` (and renaming it to
`path`) documents the intent that this argument will load from the
filesystem. It also pushes conversions to callers _only if they are
necessary_.
This PR is required to address GH-442, which will be lifting direct
access to the VFS out of `Kernel#require` into APIs in the `LoadSources`
trait.
=> Convert filename argument in LoadSources from &[u8] to AsRef<Path>

src/ruby.rs
Fixes GH-653.
$ ./target/debug/artichoke - <<EOF
puts "export RUBY_ENGINE=#{begin; Object.const_get(:RUBY_ENGINE); rescue NameError; 'ruby'; end};"
puts "export RUBY_VERSION=#{RUBY_VERSION};"
begin; require 'rubygems'; puts "export GEM_ROOT=#{Gem.default_dir.inspect};"; rescue LoadError; end
EOF
export RUBY_ENGINE=artichoke-mruby;
export RUBY_VERSION=2.6.3;
Artichoke does not support `defined?`, so to get the chruby script to
execute, I had to replace it with `Object.const_get`.
cc @deepj
=> Treat a single dash '-' programfile argument to CLI as 'read from stdin'

artichoke-backend/src/extn/core/kernel/require.rs, artichoke-backend/src/extn/core/kernel/trampoline.rs, artichoke-backend/src/load.rs, artichoke-core/src/load.rs
Lift access to the `vfs` on the `State` to the interpreter level.
This PR adds high level APIs for requiring and loading sources to the `LoadSources` trait. This significantly simplifies the implmentation of `Kernel#load` and `Kernel#require`.
This PR is required for progress on GH-442, which is made easier by removing access to the `State` from `extn`.
=> Move VFS access to LoadSources trait

artichoke-backend/src/extn/core/kernel/integer.rs, artichoke-backend/src/extn/core/kernel/kernel.rb, artichoke-backend/src/extn/core/kernel/trampoline.rs, spec-runner/enforced-specs.yaml, spec-runner/src/spec_runner.rb, spec-runner/vendor/spec/core/kernel/fixtures/classes.rb
Fix a regression in ruby/spec compliance of `Kernel#Integer`
This is the fourth iteration of this standard library function (third near-complete rewrite).
Refactoring the `Kernel` `extn` module to use trampolines introduced a
regression in parsing the `base` parameter. `base` is an optional
parameter that is also `nil`able. This PR flattens the `nil`able `Value`
into `Option<Value>`.
This PR rewrites the state machine used in parsing the numeric
`String`s. State transitions are moved into the `ParseState`. Each
transition consumes the state and returns a new state. Fallible
transitions are clearly marked by their return types and the main parse
loop is readable by high level operation. Extracting the `src` `String`
and parsed radix now consumes the `ParseState`.
`match` arms are …
=> Kernel#Integer rewrite

artichoke-backend/src/extn/core/regexp/backend/onig.rs, artichoke-backend/src/extn/core/regexp/backend/regex/utf8.rs, artichoke-backend/src/extn/prelude.rs, artichoke-backend/src/lib.rs, artichoke-backend/src/regexp.rs, artichoke-core/src/lib.rs, artichoke-core/src/regexp.rs
`regexp` module in `extn` no longer depends on the internals of the
Artichoke implementation.
This PR is required for GH-442.
=> Add interpreter-level APIs for manipulating Regexp global state

artichoke-backend/src/extn/core/random/backend/default.rs, artichoke-backend/src/extn/core/random/backend/mod.rs, artichoke-backend/src/extn/core/random/backend/rand.rs, artichoke-backend/src/extn/core/random/mod.rs, artichoke-backend/src/extn/core/random/trampoline.rs, artichoke-backend/src/lib.rs, artichoke-backend/src/prng.rs, artichoke-core/src/lib.rs, artichoke-core/src/prng.rs
`random` module in `extn` no longer depends on the internals of the
Artichoke implementation.
This PR is required for GH-442.
=> Add interpreter-level APIs for accessing the interpreter global PRNG

.github/workflows/ci.yaml, .github/workflows/fuzz.yaml, .github/workflows/rustdoc.yaml
It turns out not to be faster. Cache creation and download time on the
target directory is longer than the savings in compile time.
The real slowness is installing LLVM on Windows.
=> Remove caching from GitHub Actions workflows

artichoke-backend/src/artichoke.rs, artichoke-backend/src/convert/object.rs, artichoke-backend/src/state/mod.rs, artichoke-backend/tests/leak/mod.rs, artichoke-backend/tests/leak_mrb_tt_data_rc.rs
minimize the scope of unsafe code in the Guard pathway.
This PR triggered and led to fixing a lifetime issue causing a segfault: Ensure class and module specs are alive when running mrb_close.
The sometimes segfault on Windows is caused by `state.close()` consuming the
`State` before running the final gc in `mrb_close`. The gc relies on the class
specs free function to free Rust-defined data types. This data is not live
after the state is consumed.
The fix is to destructure the state, pulling apart the bits that need explicit
closes and those that must be kept alive. The class and module registries are
explicitly dropped last.
Regression introduced in GH-670.
=> Fix segfault in Artichoke::close

.prettierignore, .vscode/launch.json, artichoke-backend/src/fs.rs
Path traversal behaves differently in the presence of Windows
path prefixes like C:/. This PR splits tests for Windows from the
unix-like tests.
See GH-528.
This PR adds a lldb launch config for VSCode. I've been using VSCode on the Windows VM I'm working on and it has been lovely.
=> Specialize path dedot tests for Windows

.rubocop.yml, CONTRIBUTING.md, Gemfile.lock, Rakefile, artichoke-backend/src/extn/core/array/array.rb, artichoke-backend/src/extn/core/kernel/kernel.rb, artichoke-backend/src/extn/core/kernel/kernel_test.rb, artichoke-backend/src/extn/stdlib/forwardable/forwardable_test.rb
Upgrade RuboCop to 0.83.0 and fix warnings.
This PR disables the `Style/SlicingWithRange` cop because Artichoke does not yet support endless ranges: https://github.com/artichoke/artichoke/issues/441.
Rename `rake lint:all` to `rake lint`, update `CONTRIBUTING.md`.
Remove dependency update docs and mention dependabot.
=> Bump rubocop 0.83.0

.github/workflows/rustdoc.yaml, Rakefile, artichoke-backend/src/artichoke.rs, artichoke-backend/src/class_registry.rs, artichoke-backend/src/ffi.rs, artichoke-backend/src/fs.rs, artichoke-backend/src/lib.rs, artichoke-backend/src/state/mod.rs, artichoke-backend/src/sys/mod.rs, artichoke-core/src/lib.rs, spec-runner/src/main.rs, src/bin/airb.rs, src/bin/artichoke.rs, src/lib.rs
with many of the refactors stemming from GH-442, doc links have been broken.
Enforcement of doc link resolution warnings was accidentally removed in https://github.com/artichoke/artichoke/commit/2fcb2dbd6edac6e05950b4e1e9972533642dfffc. `cargo doc` does not respect `RUSTFLAGS`.
This PR adds `RUSTDOCFLAGS="-D warnings"` and fixes up the broken links.
=> Fail doc builds on warnings

artichoke-backend/src/lib.rs, artichoke-core/src/lib.rs, spec-runner/README.md, spec-runner/src/main.rs, src/bin/airb.rs, src/lib.rs
Set `html_favicon_url` and `html_logo_url` rustdoc attributes in source code
to favicon and logo hosted at www.artichokeruby.org.
https://doc.rust-lang.org/rustdoc/the-doc-attribute.html#at-the-crate-level
=> Add favicon and Artichoke logo to rustdocs

.github/workflows/ci.yaml
https://github.com/actions/virtual-environments/issues/104 added llvm to the windows base image but did not stop `choco install llvm` from taking 5 minutes per CI run.
This PR removes the llvm install build step.
Removing this first `choco` invocation caused the `winflexbison3` install step, which normally takes 15 seconds, to take almost 3 minutes. It appears that chocolatey does quite a bit of initialization or cache warming on first launch.
Replace `choco install winflexbison3` with a tarball install of a recent release from GitHub.
This PR reduces windows build times from 15 minutes to 10.5 minutes.
=> Remove CI dependency on chocolatey

Cargo.lock, artichoke-backend/Cargo.toml
This PR pulls in the latest rust-onig fork which syncs master as of
rust-onig/rust-onig@742dc25ab7750c21493b666b90bdee7656d0b221. This patch
level removed most of my patches except the one that adds bindgen
support for wasm32 targets.
The fork also updates the bindgen dep, which we propagate to
artichoke-backend as well.
=> Update rust-onig and bindgen to latest

Gemfile.lock, artichoke-backend/src/extn/core/array/array.rb, artichoke-backend/src/extn/core/array/inline_buffer_test.rb, artichoke-backend/src/extn/core/comparable/comparable.rb, artichoke-backend/src/extn/core/enumerable/enumerable.rb, artichoke-backend/src/extn/core/enumerator/enumerator.rb, artichoke-backend/src/extn/core/env/env.rb, artichoke-backend/src/extn/core/hash/hash.rb, artichoke-backend/src/extn/core/integer/integer.rb, artichoke-backend/src/extn/core/kernel/kernel.rb, artichoke-backend/src/extn/core/range/range.rb, artichoke-backend/src/extn/core/string/string.rb, artichoke-backend/src/extn/core/string/string_test.rb, artichoke-backend/src/extn/core/thread/thread.rb, artichoke-backend/src/extn/stdlib/strscan/strscan.rb, artichoke-backend/src/extn/stdlib/strscan/strscan_test.rb, artichoke-backend/src/extn/stdlib/uri/uri_test.rb, spec-runner/src/spec_runner.rb
Update RuboCop to 0.84 and apply all autocorrects.
All autocorrects come from RuboCop increasing the default max line length to 120.
Obsoletes GH-685.
=> Rubocop 0.84

Cargo.lock, Rakefile, artichoke-backend/Cargo.toml, artichoke-backend/build.rs, deny.toml
Remove:
- num_cpus
- git2
- rustc_version
- jobserver (combination of the above removals and not enabling cc's `parallel` feature)
This change hardcodes some repo metadata into the build script and reduces the number of external subprocesses which can fail.
Previous work on the build script made resolving compiler version and revision count optional in the build script but Artichoke would still fail to build. This PR adds zeroed defaults when emitting the env vars to the compiler.
=> Remove some build deps from artichoke-backend

.github/workflows/ci.yaml, Cargo.toml, artichoke-backend/Cargo.toml, artichoke-backend/src/extn/core/regexp/backend/lazy.rs, artichoke-backend/src/extn/core/regexp/backend/mod.rs, artichoke-backend/src/extn/core/regexp/backend/onig.rs, artichoke-backend/src/extn/core/regexp/backend/regex/utf8.rs, artichoke-backend/src/extn/core/regexp/enc.rs, artichoke-backend/src/extn/core/regexp/mod.rs, artichoke-backend/src/extn/core/regexp/opts.rs, artichoke-backend/src/extn/core/regexp/pattern.rs
This PR adds a cargo feature to `artichoke` and `artichoke-backend` called `core-regexp-oniguruma`.
`core-regexp-oniguruma` is enabled by default. When the feature is enabled, `onig` dependency is built and the core `Regexp` implementation is a hybrid of the Rust `regex` crate and oniguruma.
Disabling this feature builds the core `Regexp` backend such that only the Rust `regex` crate powers it. Disabling this feature should make building for Wasm targets easier since Rust `regex` is pure Rust and the C `onig` dependency is excluded.
This PR opportunistically gives some love to the rest of the `Regexp` Rust implementation, refactoring to use more Rust idioms, iterators, and trait implementations; increase readability and performance; and add tests.
Fixes GH-489.
Fixes GH-26.
=> Make onig an optional dependency

Cargo.lock, artichoke-backend/Cargo.toml
Update all interior deps in `Cargo.lock`.
Dependabot only bumps direct dependencies. If those direct dependencies don't update their dependency constraints, deps at depth > 1 will not be updated.
This PR also explicitly bumps `target-lexicon` which was released today at 0.11.0.
=> Run `cargo update`

artichoke-backend/src/extn/stdlib/base64/mod.rs, artichoke-backend/src/extn/stdlib/base64/vendor/base64.rb, artichoke-backend/src/extn/stdlib/mod.rs, spec-runner/enforced-specs.yaml
close https://github.com/artichoke/artichoke/issues/75
Hi!
I added base64 standard library.
```sh
$ bundle exec rake spec | grep Base64
cargo run -q -p spec-runner -- spec-runner/enforced-specs.yaml
rb warning: encoding option is ignored -- N
rb warning: flags ignored when initializing from Regexp
rb warning: encoding option is ignored -- N
rb warning: flags ignored when initializing from Regexp
Base64#encode64: ..
Base64#decode64: .
Base64#urlsafe_encode64: ...
Base64#urlsafe_decode64: ...
```
=> Implement base64 standard library

artichoke-backend/src/block.rs, artichoke-backend/src/convert.rs, artichoke-backend/src/convert/bytes.rs, artichoke-backend/src/convert/string.rs, artichoke-backend/src/def.rs, artichoke-backend/src/eval.rs, artichoke-backend/src/exception.rs, artichoke-backend/src/exception_handler.rs, artichoke-backend/src/extn/core/env/backend/mod.rs, artichoke-backend/src/extn/core/exception/mod.rs, artichoke-backend/src/extn/core/kernel/mod.rs, artichoke-backend/src/extn/core/math/mod.rs, artichoke-backend/src/ffi.rs, artichoke-backend/src/interpreter.rs, artichoke-backend/src/io.rs, artichoke-backend/src/parser.rs, artichoke-backend/src/string.rs, artichoke-backend/src/value.rs
This allows e.g. impls of Display to be used to satisfy these APIs when
implementing the trait.
In the common case, it makes the API more flexible while still avoiding allocations.
This commit adds ConvertMut impls for `Cow<'_, [u8]>` and `Cow<'_, str>`.
=> Change RubyException::message and RubyException::name to return Cow

artichoke-backend/src/block.rs, artichoke-backend/src/convert/boxing.rs, artichoke-backend/src/eval.rs, artichoke-backend/src/extn/core/array/args.rs, artichoke-backend/src/extn/core/array/mod.rs, artichoke-backend/src/extn/core/array/mruby.rs, artichoke-backend/src/extn/core/array/trampoline.rs, artichoke-backend/src/extn/core/exception/mod.rs, artichoke-backend/src/extn/core/integer/mod.rs, artichoke-backend/src/extn/core/kernel/integer.rs, artichoke-backend/src/extn/core/kernel/require.rs, artichoke-backend/src/extn/core/kernel/trampoline.rs, artichoke-backend/src/extn/core/matchdata/mod.rs, artichoke-backend/src/extn/core/matchdata/trampoline.rs, artichoke-backend/src/extn/core/math/mod.rs, artichoke-backend/src/extn/core/numeric/mod.rs, artichoke-backend/src/extn/core/random/mod.rs, artichoke-backend/src/extn/core/random/trampoline.rs, artichoke-backend/src/extn/core/regexp/backend/lazy.rs, artichoke-backend/src/extn/core/regexp/backend/mod.rs, artichoke-backend/src/extn/core/regexp/backend/onig.rs, artichoke-backend/src/extn/core/regexp/backend/regex/utf8.rs, artichoke-backend/src/extn/core/regexp/mod.rs, artichoke-backend/src/extn/core/regexp/trampoline.rs, artichoke-backend/src/extn/core/string/trampoline.rs, artichoke-backend/src/extn/stdlib/securerandom/mod.rs, artichoke-backend/src/extn/stdlib/securerandom/trampoline.rs, artichoke-backend/src/value.rs, artichoke-backend/src/warn.rs, src/ruby.rs
`extn::core::exception` implements all `Exception` descendants in Ruby Core using macros because there are a bunch of them.
These macros define the inherent methods:
```rust
impl $excepton {
pub fn new<T: Into<Cow<'static, str>>>(interp: &Artchoke, msg: T)` {}
pub fn new_raw<T: Into<Cow<'static, [u8]>>>(interp: &Artchoke, msg: T)` {}
}
```
The interp parameters were present since the initial implementation of these structs. When `Artichoke` was clone-able, each exception struct owned a copy of the `Rc`-wrapped interpreter to resolve its classname. 042bc4b3484c9e89890b3f3114053f56141a67bb removed this struct member in favor of a `stringified` class name, but did not refactor the constructor or any call sites.
This PR changes the inherent impl to:
```rust
impl $exception {
pub fn new() -> …
```
=> Remove Artichoke parameter from $exception::new for all Exceptions in Core

Cargo.lock, Cargo.toml, src/backtrace.rs, src/bin/airb.rs, src/bin/artichoke.rs, src/repl.rs, src/ruby.rs
Artichoke previously used ansi_term because that was bundled with clap.
clap v3 switches to using termcolor for colorizing output for better
Windows support. termcolor is also used in ripgrep.
termcolor's API is a bit more awkward, but it was fairly straightforward
to make this change.
=> Switch frontend binaries from ansi_term to termcolor

.github/workflows/audit.yaml, .github/workflows/ci.yaml, .github/workflows/rustdoc.yaml, artichoke-backend/src/interpreter.rs
Don't pass --workspace or --no-deps to `cargo doc` to enable better inter crate linking and linking to `std`.
Pull in latest cargo-deny release
=> Tweaks to rustdoc generation

artichoke-backend/src/class.rs, artichoke-backend/src/class_registry.rs, artichoke-backend/src/constant.rs, artichoke-backend/src/convert/boxing.rs, artichoke-backend/src/convert/string.rs, artichoke-backend/src/def.rs, artichoke-backend/src/gc/arena.rs, artichoke-backend/src/globals.rs, artichoke-backend/src/intern.rs, artichoke-backend/src/method.rs, artichoke-backend/src/module.rs, artichoke-backend/src/module_registry.rs, artichoke-backend/src/parser.rs, artichoke-backend/src/top_self.rs, artichoke-backend/src/value.rs, artichoke-core/src/intern.rs, src/parser.rs
`Artichoke::with_ffi_boundary` was introduced in https://github.com/artichoke/artichoke/pull/670.
I'm currently working on implementing `Symbol` and the backing symbol
table in Rust. _Lots_ of operations in the mruby VM depend on access to
the symbol table. This PR ensures that the `State` is moved into the
`mrb_state` whenever an mruby FFI function is called.
This commit also unnnests some long functional chains to make them
friendlier to the debugger.
The primary mechanism for rolling this change out is to move
`sys::RClass` resolution out of the `class::Spec` and `module::Spec`
into a companion struct. Resolving an `RClass` does not require the
`mrb_data_type`, so it is not necessary to maintain a borrow on the
`State` when resolving one. This change enables using
`with_ffi_boundary` …
=> Use Artichoke::with_ffi_boundary in more places

Cargo.lock, spec-runner/Cargo.toml, spec-runner/src/main.rs
If an exception in the spec-runner happens outside of `MSpec`, it is
currently swallowed. This makes debugging difficult as we modify the
core VM.
This change catches errors returned from the interpreter and formats
them to stderr with the backtrace formatting routines in Artichoke
crate.
This change brings in a dependency in spec-runner on `termcolor`.
=> Print exception backtraces for top-level errors in spec-runner

artichoke-backend/src/block.rs, artichoke-backend/src/exception_handler.rs, artichoke-backend/src/gc.rs, artichoke-backend/src/gc/arena.rs, artichoke-backend/src/interpreter.rs, artichoke-backend/src/value.rs, artichoke-backend/tests/leak_unbounded_arena_growth.rs
This commit try to solve issue #669. Now, if somehow fails to retrieve
the ArenaIndex in the GC, the default behavior is to return an error.
Down the path those exception are dealt with an `.expect(msg)`, as it
isn't clear at the time of writing, what should be the approach to a
failed retrieval.
Fixes GH-669.
=> Return `Result` from ArenaIndex::new

Cargo.lock, package-lock.json
dependabot does not upgrade non-direct dependencies, so regenerate the cargo and npm lock files.
```sh
cargo update
```
```
rm -rf ./node_modules
rm package-lock.json
npm i
```
=> Upgrade interior deps

artichoke-core/Cargo.toml, artichoke-core/README.md, artichoke-core/src/constant.rs, artichoke-core/src/convert.rs, artichoke-core/src/eval.rs, artichoke-core/src/file.rs, artichoke-core/src/globals.rs, artichoke-core/src/intern.rs, artichoke-core/src/io.rs, artichoke-core/src/lib.rs, artichoke-core/src/load.rs, artichoke-core/src/parser.rs, artichoke-core/src/prng.rs, artichoke-core/src/regexp.rs, artichoke-core/src/types.rs, artichoke-core/src/value.rs, artichoke-core/src/warn.rs
`artichoke-core` defines the traits that comprise an interpreter. There
is little implementation. It is feasible to make the crate `no_std`. To
make this transition, the following changes were made:
- Add `extern crate alloc` to `lib.rs`.
- Add an optional, enabled by default, `std` feature.
- `use alloc::vec::Vec` where `Vec` was used since there is no longer
any implicit `std` prelude.
- `use alloc::borrow::Cow` instead of `use std::borrow::Cow`.
- Remove `std::error::Error` bounds on all `Error` associated types.
- Update doc comments to refer to `core` instead of `std` where
possible, with external links otherwise.
- Gate `Eval::eval_os_str` behind the `std` feature and note the feature
requirement in the docs.
- Gate `Eval::eval_file` behind the `std` feature and note the feature …
=> Update artichoke-core to be no_std + alloc compatible

.github/workflows/ci.yaml, Rakefile, artichoke-backend/README.md, artichoke-backend/src/extn/core/numeric/mod.rs, artichoke-backend/src/lib.rs, artichoke-backend/tests/leak_funcall.rs, artichoke-backend/tests/leak_unbounded_arena_growth.rs, fuzz/fuzz_targets/eval.rs, spec-runner/src/main.rs, spec-runner/src/mspec.rs, spec-runner/src/rubyspec.rs, src/lib.rs, src/repl.rs, src/ruby.rs
Pass `--workspace` flag to clippy in `Rakefile` and CI.
This PR syncs the `Rakefile` to include the `--all-features` flag present in CI.
All doctests that wrap the example in a function renamed that function from `main` to `example` and add an additional hidden line `example().unwrap()` to ensure the example code is executed.
The biggest code change in this PR is reworking the way traits in `artichoke-core` are included in the `prelude` modules in `artichoke-backend` and `artichoke` to avoid clippy complaining about glob imports.
=> Lint entire workspace with clippy

.clang-format, artichoke-backend/mruby-sys/include/mruby-sys/artichoke.h, artichoke-backend/mruby-sys/include/mruby-sys/ext.h, artichoke-backend/mruby-sys/src/mruby-sys/ext.c
This formatting config makes the mruby-sys C extension look more like mruby
C sources.
=> Add a clang-format configuration

.github/workflows/ci.yaml, Cargo.lock, Cargo.toml, Rakefile, artichoke-core/Cargo.toml, spinoso-array/Cargo.toml, spinoso-array/README.md, spinoso-array/src/array/mod.rs, spinoso-array/src/array/smallvec/convert.rs, spinoso-array/src/array/smallvec/eq.rs, spinoso-array/src/array/smallvec/impls.rs, spinoso-array/src/array/smallvec/mod.rs, spinoso-array/src/array/vec/convert.rs, spinoso-array/src/array/vec/eq.rs, spinoso-array/src/array/vec/impls.rs, spinoso-array/src/array/vec/mod.rs, spinoso-array/src/lib.rs
This is an experiment to move core data structures used to implement
Ruby Core and Standard Library out of `artichoke-backend`. The goal is
to have `artichoke-backend` be the VM and Ruby <-> Rust type
orchestrator via the `BoxUnboxVmValue` trait.
This idea has already been trialed with `intaglio` extracting the
`Symbol` backend.
The `spinoso` crate prefix comes from _Carciofo spinoso di Sardegna_,
the thorny artichoke of Sardinia. The idea is that the data structures
defined in the `spinoso` family of crates will form the backbone of Ruby
Core in Artichoke.
`spinoso-array` is a generalization of the `Array` and `InlineBuffer`
found in `artichoke_backend::extn::core::array`. It includes many more
slice and mutation methods which will allow defining more of Ruby
`Array` in native code at …
=> Add spinoso-array crate

artichoke-backend/src/macros.rs
Types were not resolvable using the shortlinks.
This commit cleans up some of the doc comments to make them more readable.
Unblocks the build failure on GH-760.
=> Fix rustdoc generation in artichoke-backend on latest nightly

spinoso-array/README.md
The README was copied from intaglio and the top header was not updated.
This commit also adds some spacing to the code example to make it easier
to read.
=> Fix a copy-paste error when crafting the spinoso-array README

artichoke-backend/src/extn/core/regexp/mod.rs, artichoke-backend/src/extn/core/regexp/syntax.rs
artichoke-backend maintains a small fork of several functions from regex-syntax.
There have been some upstream changes I noticed. This commit pulls them in and
rebases the fork.
This commit restructures the 'escape_into' function, changes how form feed char
is handled, adds comments, and adds tests.
The only use of the 'syntax' module is Regexp::escape. The call sites were
refactored to be more debugger friendly.
=> Update fork of regex-syntax escape functions

README.md, artichoke-backend/README.md, artichoke-core/README.md, spinoso-array/README.md
- Make the code block in artichoke-core a Rust code block.
- Make wording and code annotations consistent in License section of
crate READMEs.
=> README tweaks

artichoke-backend/src/extn/core/array/mod.rs, artichoke-backend/src/extn/core/kernel/mod.rs, artichoke-backend/src/extn/core/kernel/require.rs, artichoke-backend/src/extn/core/string/mod.rs, artichoke-backend/src/extn/core/thread/mod.rs, artichoke-backend/src/extn/stdlib/abbrev/mod.rs, artichoke-backend/src/extn/stdlib/forwardable/mod.rs, artichoke-backend/src/extn/stdlib/json/mod.rs, artichoke-backend/src/extn/stdlib/monitor/mod.rs, artichoke-backend/src/extn/stdlib/strscan/mod.rs, artichoke-backend/src/extn/stdlib/uri/mod.rs
Ensure all exceptions are output with the full message and backtrace.
Parameterize harness to make it easier to copy and paste.
Relocate the `Kernel#require` functionals to the
`extn::core::kernel::require` module.
=> Improve setup and assertions in extn functional tests

.github/labels.json, .github/workflows/repo-labels.yaml
Declare repository labels with a JSON file.
This PR builds on the same techniques used in many other Artichoke organization
repositories.
This PR normalizes some of the label texts for labels already present in this
repo and fleshes out some categories, for example adding O-macOS and O-linux,
or adding B-Artichoke for eventual Rust VM backend plans.
Fixes GH-532.
=> Manage repository labels with a GitHub Action

Cargo.lock
Run `cargo update` because dependabot doeasn't update indirect dependencies.
This removes `syn-mid` from the lockfile and pulls in `intaglio` v1.1.1.
=> Update interior deps

.github/workflows/rustdoc.yaml, CONTRIBUTING.md, Rakefile, spinoso-array/Cargo.toml, spinoso-array/src/array/mod.rs, spinoso-array/src/array/smallvec/mod.rs, spinoso-array/src/array/vec/mod.rs, spinoso-array/src/lib.rs
Annotate `SmallArray` and `INLINE_CAPACITY` as only available when `spinoso-array` is built with the `small-array` feature.
Add rustdoc flags to `Rakefile`, `Cargo.toml` and GitHub Actions rustdoc workflow.
Add `Rakefile` build task.
Additionally, make `Array::new` a const function.
=> Add cfg_doc annotations to spinoso-array

.github/workflows/ci.yaml, CONTRIBUTING.md, Cargo.lock, Cargo.toml, Rakefile, artichoke-backend/Cargo.toml, artichoke-backend/src/convert/boolean.rs, artichoke-backend/src/convert/nilable.rs, artichoke-backend/src/extn/core/symbol/ffi.rs, artichoke-backend/src/extn/core/symbol/mod.rs, artichoke-backend/src/extn/core/symbol/mruby.rs, artichoke-backend/src/extn/core/symbol/symbol.rb, artichoke-backend/src/extn/core/symbol/trampoline.rs, artichoke-backend/src/globals.rs, artichoke-backend/src/intern.rs, artichoke-backend/src/module.rs, artichoke-backend/src/value.rs, artichoke-core/Cargo.toml, artichoke-core/src/intern.rs, spec-runner/enforced-specs.yaml, spinoso-symbol/Cargo.toml, spinoso-symbol/README.md, spinoso-symbol/src/all_symbols.rs, spinoso-symbol/src/casecmp/ascii.rs, spinoso-symbol/src/casecmp/mod.rs, spinoso-symbol/src/casecmp/unicode.rs, spinoso-symbol/src/convert.rs, spinoso-symbol/src/eq.rs, spinoso-symbol/src/inspect.rs, spinoso-symbol/src/lib.rs
This continues the experiement started with `spinoso-array` (#759) to extract
data structures from `artichoke-backend` and generically implement Ruby
Core.
`spinoso-symbol` goes further than `spinoso-array` by implementing
`Symbol` APIs that depend on an Artichoke interpreter. It does this by
having an `artichoke` Cargo feature that pulls in `artichoke-core`. APIs
that require resolving the underlying `Symbol` byte content take a
generic parameter `T where T: Intern`.
`spinoso-symbol` implements an `AllSymbols` iterator that is `'static`
and implements a buggy version of `Symbol#inspect` with an iterator (#725).
`spinoso-symbol` resolves `Symbol` byte contents for ASCII and Unicode
casecmp functions using `focaccia`. `spinoso-symbol` also depends on
`bstr`.
`spinoso-symbol` re-exports …
=> Add spinoso-symbol crate

artichoke-backend/src/extn/core/array/ffi.rs, artichoke-backend/src/extn/core/array/gc.rs, artichoke-backend/src/extn/core/array/mod.rs
These functions are specific to mruby. If `Array` APIs are moved to
`spinoso-array`, these functions cannot go with them.
=> Split Array GC routines out of data structure

artichoke-backend/src/extn/core/symbol/symbol.rb, spec-runner/enforced-specs.yaml
This required moving from a stabby lambda definition to a more relaxed
lambda expression, checking for no receiver, and overriding Proc#parameters.
Enabled by #787.
=> Add Symbol#to_proc to enforced ruby/specs

artichoke-backend/src/string.rs, spinoso-symbol/src/ident.rs, spinoso-symbol/src/inspect.rs, spinoso-symbol/src/lib.rs, spinoso-symbol/src/unicode.rs
=> Improve handling of Unicode replacement character and invalid UTF-8 in Symbol#inspect

artichoke-backend/src/class.rs, artichoke-backend/src/constant.rs, artichoke-backend/src/def.rs, artichoke-backend/src/method.rs, artichoke-backend/src/module.rs, artichoke-backend/src/sys/mod.rs
Remove unnecessary `CStr` unsafe from `mrb_state` debug functions
Replace unsafe calls to `CStr::from_bytes_with_nul_unchecked` with safe calls to
`CStr::from_bytes_with_nul` and additional error handling/squashing.
Update the tests module to pull in the test prelude.
---
Improve readability of `DefineConstant` impl in artichoke-backend
Short circuit return with `CString` errors to unnest the indent level.
Split calls to resolve `RClass` into separate `with_ffi_boundary` invocations.
---
Improve safety and code quality of artichoke-backend VM internals
- Add safety comments for `CString` pointer lifetime invariants being
upheld by `class::Spec`.
- Store `Box<CStr>` instead of `CString` because these C strings do not
need to be mutable.
- Refactor `EnclosingScope` enum to use tuple …
=> Unsafe internals code quality improvements

Cargo.lock, Cargo.toml, artichoke-backend/Cargo.toml, artichoke-backend/src/extn/stdlib/securerandom/mod.rs, artichoke-backend/src/extn/stdlib/securerandom/mruby.rs, artichoke-backend/src/extn/stdlib/securerandom/trampoline.rs, artichoke-backend/src/macros.rs, spinoso-securerandom/Cargo.toml, spinoso-securerandom/README.md, spinoso-securerandom/src/hex.rs, spinoso-securerandom/src/lib.rs, src/lib.rs
This PR extracts the implementation of `SecureRandom` from `artichoke-backend` into a separate crate.
This is desirable because:
- Code quality has improved significantly: the new crate has tests, documentation, examples, and doctests.
- There is a proper space to include utilities: this PR removes the dependency on `hex` in favor of a hand rolled hexadecimal encoder using techniques similar to the ones in `spinoso-symbol`.
- Disabling the swath of dependencies related with a CSPRNG in `artichoke-backend` is much simpler: there is now a single optional dependency linked up to a single Cargo feature.
- The new crate is a drop-in replacement: other than deleting the now duplicate code, there was zero code change in the `extn::stdlib::securerandom` module.
- Errors in the secure random APIs …
=> Add spinoso-securerandom crate

spinoso-symbol/src/casecmp/unicode.rs
linking to 'str' requires a disambiguator.
=> Fix breakage in intradoc links in latest nightly

spec-runner/enforced-specs.yaml
- Update `Symbol` enforced specs to only skip known problematic suites.
- Consistently format `enforced-specs.yaml`.
- Improve doc comments for why some suites are skipped.
=> Add better documentation to enforced-specs.yaml

Cargo.lock, artichoke-backend/Cargo.toml
I started publishing git tags for each vendored SHA of our rust-onig
fork. Store the git tag name in the `rev` field instead of a raw SHA.
Move `artichoke-core` to inline syntax like the spinoso crates. Add
crate version to `artichoke-core` dependency declaration.
=> Clean up artichoke-backend Cargo.toml

.github/workflows/rustdoc.yaml, CONTRIBUTING.md, README.md, Rakefile, artichoke-backend/src/extn/stdlib/vendor/gen/README.md
This PR turned into a big fixup of the markdown documentation.
- Fix broken links in `gen/README.md` in stdlib.
- Fix broken `rake lint:links` task.
- Remove outdated section on node.js packages from `CONTRIBUTING.md`.
- Bring link definitions down to bottom of `README.md` for ease of editing.
This PR also re-enables rustdoc generation for the entire workspace, which was accidentally disabled in https://github.com/artichoke/artichoke/pull/719.
=> Add ruby-build installation method to README

Cargo.lock, Gemfile, Gemfile.lock
- Add version constraints on RuboCop and rubocop-rake.
- `cargo update` for interior deps.
=> Cargo and Bundler dep updates

artichoke-core/src/types.rs
Rust 1.46.0 brings support for `match` in const fn.
=> Add const to functions that can be in artichoke-core

spinoso-array/src/array/vec/mod.rs
This makes the code look a bit nicer and eliminates an unnecessary function call.
=> Cleanup alloc::vec usage in Array backend in spinoso-array

scolapasta-hex/Cargo.toml, scolapasta-hex/src/lib.rs
- Remove references to spinoso-symbol in comments and feature documentation -- this
was a leftover from copy-pasting the crate definition.
- Add EscapedByte::as_str, EscapedByte::len, and EscapedByte::is_empty.
- Simplify Iterator impl for EscapedByte.
- Use EscapedByte::len in Hex::len.
- Use EscapedByte::is_empty in Hex::is_empty.
=> Cleanups to hex impl

scolapasta-hex/README.md, scolapasta-string-escape/README.md, spinoso-array/README.md, spinoso-exception/README.md, spinoso-securerandom/README.md, spinoso-symbol/README.md
> _Spinoso_ refers to _Carciofo spinoso di Sardegna_, the thorny artichoke of
> Sardinia. The data structures defined in the `spinoso` family of crates form the
> backbone of Ruby Core in Artichoke.
> _Scolapasta_ refers to a specialized colander used to drain pasta. The utilities
> defined in the `scolapasta` family of crates are the kitchen tools for preparing
> Artichoke Ruby.
=> Improve README descriptions of Italian crate prefixes

.github/workflows/audit.yaml, .github/workflows/ci.yaml, .github/workflows/fuzz.yaml, .github/workflows/rustdoc.yaml
- Do not explicitly install `bison` on Ubuntu runners -- it is installed by default.
- Update `cargo-deny` to latest release.
- Refactor `cargo-deny` installer workflow step to be easier to update.
=> Updates to GitHub Actions package installers

artichoke-backend/src/state/parser.rs, spinoso-securerandom/src/lib.rs
- Primitive associated constants can now be resolved - rust-lang/rust#76093 -
remove hard-coded links to `f64::NAN` in `spinoso-securerandom`.
- Fix unresolved link to `artichoke_backend::eval::Eval`. The trait
definition has lived in `artichoke-core` for some time now.
=> Fix broken build due to intradoc links updates'

.rubocop.yml, CONTRIBUTING.md, Rakefile, artichoke-backend/scripts/auto_import/get_package_files.rb
- Use `RuboCop::RakeTask` to define RuboCop tasks.
- Split formatting tasks into their own namespace.
- Default task runs `format` and `lint`.
- Add separate tasks for formatting Rust, C, and text sources.
- Make formatting tasks available as `format` or `fmt` and e.g.
`format:rust` or `fmt:rust`.
- Update Clippy restriction lint names.
- Refactor clippy restriction lint to use an array of lints and
shelljoin to construct a command.
- Move `lint:restriction` to `lint:clippy:restriction`.
- Adopt code to touch Rust source roots for `lint:clippy:restriction`.
- Dynamically discover markdown sources in `lint:links` task.
- Add a sleep to `lint:links` to avoid 429 rate limiting errors.
- Improve task descriptions.
=> Re-organize Rakefile

CONTRIBUTING.md, Rakefile
Split markdown link check into a _release_ namespace.
Remove hardcoded markdown sources in link check task -- sync globbing
rules with .prettierignore.
Remove explicit and unnecessary `fileutils` require.
=> Use FileList APIs in Rakefile

spinoso-env/src/env/memory.rs, spinoso-env/src/env/system.rs, spinoso-env/src/lib.rs, spinoso-symbol/src/lib.rs
- Quote symbol examples with invalid UTF-8.
- Add more fallible APIs and examples to Error docs.
- Add doc(cfg(feature = ...)) to System backend.
- Make first doc line consistent between Memory and System type.
=> Improve spinoso-env docs

.github/workflows/audit.yaml, Cargo.toml, artichoke-backend/Cargo.toml, deny.toml
Intend to use this same setup and execute block in all Rust
repositories, which will allow keeping the cargo-deny version in sync by
updating a single secret.
See artichoke/rand_mt#44.
=> Configure cargo-deny version with an organization secret

artichoke-backend/src/extn/stdlib/securerandom/mod.rs, spinoso-securerandom/README.md, spinoso-securerandom/src/lib.rs
- Rename `RandomNumber` to `Rand`.
- Simplify `len` checking in `random_bytes` and `alphanumeric` by matching over `Option<Result<usize>>` from calling `len.map(usize::try_from)`.
- Add `From<E> for Error` impls for sum type sub-errors.
- Add `#[inline]` annotations to all trait methods.
- Return more specific error from `alphanumeric`.
Followup to #836.
=> Sync SecureRandom implementation with spinoso-random

build.rs
Improve the maintainability and operability of `build.rs` for the `artichoke` crate.
- Remove methods on `Date` container. The inner fields are already public, so replace methods with field accesses and constructors.
- Replace `unwrap`s for env variable parsing with `expect` or `panic!` with specific error messages about which env variables are malformed or missing.
=> Remove unnecessary code and add error messages to artichoke build.rs

artichoke-backend/src/extn/mod.rs, artichoke-backend/src/interpreter.rs, artichoke-backend/src/release_metadata.rs
Remove the generic bound on `ReleaseMetadata` in
`artichoke_backend::interpreter_with_config` and
`artichoke_backend::extn::init`. Replace it with taking the
concrete `ReleaseMetadata` type defined in `artichoke-backend`.
Implement all of the `core::ReleaseMetadata` trait methods as `const fn`
associated methods on `ReleaseMetadata`. Combined with taking the
concrete type, this should allow const propagation to fill in the Ruby
constants.
Followup to #703.
=> Remove generic bound in artichoke_backend::interpreter_with_config

.github/workflows/ci.yaml, CONTRIBUTING.md, Rakefile
Add build steps to compile the root, fuzz, and spec-runner workspaces
with the --locked argument to ensure that all workspaces maintain up-to-date
Cargo.lock files
This commit adds a `rake build:all` task that builds all Rust workspaces
in this repository.
=> Compile all workspaces with --locked in CI

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-backend/src/string.rs, fuzz/Cargo.lock, spec-runner/Cargo.lock
The only use of `write_float_into` was the extn `Random` implementation. The usage
was removed in GH-836.
Relates GH-561.
=> Remove dtoa dependency from artichoke-backend

src/ruby.rs
The enclosing function returns `Box<dyn std::error::Error>` now which
removes the `RubyException` impl requirement.
This error will get propagated to the console.
=> Address TODO in Ruby CLI driver

Cargo.lock, Cargo.toml, fuzz/Cargo.lock, spec-runner/Cargo.lock, spinoso-time/Cargo.toml
See chronotope/chrono#478 which was released as chrono v0.4.16.
This PR pegs the minimum chrono to 0.4.17 to pull in a wasm fix from
chronotope/chrono#483.
=> Update to latest chrono and remove time from Cargo.lock

deny.toml
=> Ban time crate from dependency tree using cargo-deny

artichoke-backend/src/extn/core/time/trampoline.rs
The `airb` REPL calls `#inspect` on each value returned by
`Artichoke::eval`. `Time` raises `NotImplementedError` in its `#inspect`
implementation. There is a nasty interaction here between the
`Time#inspect` implementation and the mruby locals tables that cause a
local bound to a `Time` to get reassigned to the `NotImplementedError`.
```console
artichoke 0.1.0-pre.0 (2020-10-01 revision 3626) [x86_64-apple-darwin]
[rustc 1.46.0 (04488afe3 2020-08-24)]
>>> t = Time.now
=>
>>> t.month
Traceback (most recent call last):
1: from (airb):2
NoMethodError (undefined method 'month')
>>> t.class
=> NilClass
>>>
```
With this patch, the REPL behaves like this:
```console
artichoke 0.1.0-pre.0 (2020-10-01 revision 3627) [x86_64-apple-darwin]
[rustc 1.46.0 (04488afe3 2020-08-24)]
>>> t = Time.now
=> …
```
=> Fix Time locals in airb REPL

Cargo.lock, artichoke-backend/src/extn/stdlib/securerandom/trampoline.rs, fuzz/Cargo.lock, scolapasta-hex/src/lib.rs, spec-runner/Cargo.lock, spinoso-securerandom/Cargo.toml, spinoso-securerandom/README.md, spinoso-securerandom/src/lib.rs, spinoso-securerandom/src/uuid.rs
Remove the dependency on the `uuid` crate and implement the UUID V4
generation algorithm directly with `rand`.
The UUID V4 generation algorithm is ~25 lines and is not worth the cost
of an extra dependency.
Pulling this code into `spinoso-securerandom` drops another dependeny
that indirectly depends on `rand` and `getrandom`. Both of these crates
have pending semver incompatible updates. Removing transitive deps on
these crates will make orchestrating the upgrade easier.
The code change in `artichoke-backend` to consume this new change, which
properly exposes the fallibility of random bytes generation, is trivial
(the addition of a single `?` operator to propagate the error).
This change adds property tests to ensure the generated UUIDs serialize
to the correct format with the correct …
=> Remove dependency on uuid crate

spinoso-random/src/random/ruby/mod.rs
Breakage caused by https://github.com/rust-lang/rust/pull/76811
=> Doc alias does not allow spaces with latest nightly

Cargo.lock, artichoke-backend/Cargo.toml, artichoke-backend/src/coerce_to_numeric.rs, artichoke-backend/src/debug.rs, artichoke-backend/src/extn/core/array/mod.rs, artichoke-backend/src/extn/core/kernel/integer.rs, artichoke-backend/src/extn/core/numeric/mod.rs, artichoke-backend/src/extn/core/string/trampoline.rs, artichoke-backend/src/extn/core/time/trampoline.rs, artichoke-backend/src/lib.rs, artichoke-backend/src/value.rs, artichoke-core/Cargo.toml, artichoke-core/src/debug.rs, artichoke-core/src/lib.rs, artichoke-core/src/types.rs, artichoke-core/src/value.rs, fuzz/Cargo.lock, spec-runner/Cargo.lock, spinoso-symbol/Cargo.toml
This PR removes the `pretty_name` method from `artichoke-core`, which is likely the grossest generic code in Artichoke:
```rust
pub fn pretty_name<'a, V, T>(value: V, interp: &mut T) -> &'a str
where
V: Copy + Value<Artichoke = T>,
T: TryConvert<V, Option<bool>, Error = V::Error>
+ TryConvertMut<V, &'a str, Error = V::Error>
+ TryConvertMut<<<V as Value>::Value as Value>::Value, &'a str, Error = V::Error>,
V::Value: Value<Artichoke = T>,
<V::Value as Value>::Value: Value<Artichoke = T, Error = V::Error>,
{
// ...
}
```
This function is replaced with a new `Debug` trait and a method for retrieving the inspect name for the class of the given value: `inspect_type_name_for_value`. The name is better too.
This PR bumps `artichoke-core` to version 0.6.0.
This PR fixes a long-standing bug with …
=> Remove pretty name

Cargo.lock, artichoke-backend/Cargo.toml, deny.toml, fuzz/Cargo.lock, spec-runner/Cargo.lock
Switch bak to the stable build of `onig`. This now contains the
bindgen + WASM work done by the Artichoke team. Nice work peeps!
=> Switch to Onig Stable

spinoso-random/src/lib.rs
Fix for rust-lang/rust#76329 being merged into the latest nightly.
=> doc(alias = ...) is not allowed at crate level

artichoke-backend/src/convert/fixnum.rs, artichoke-backend/src/extn/core/regexp/backend/onig.rs, artichoke-backend/src/extn/core/regexp/backend/regex/utf8.rs, artichoke-backend/src/state/parser.rs, artichoke-backend/src/types.rs, src/parser.rs
Replace explicit calls to Iterator::fold with Iterator::min
use `::MAX` associated constants instead of `::max_value` associated
function.
Use `cmp` instead of `partial_cmp` since we're comparing unsigned
integers which are total.
---
Use `::MAX` and `::MIN` instead of `::max_value()` and `::min_value()` for integer primitives
=> Folds and max value

.github/workflows/ci.yaml
The CI workflow dynamically sets the `PATH` environment variable on
Windows to access a custom `win_flex_bison` artifact when building
mruby.
CVE-2020-15228 is a vulnerability in the GitHub Actions hosted runner
that will interpret arbitrary `set-env` and `add-path` sequences in
stdout logs, including untrusted output.
GitHub has stated that they are immediately deprecating these commands
and intend to remove them in the near future:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
This PR replaces the `add-path` magic stdout sequence with an append to
the special `$GITHUB_PATH` file.
This commit also updates OS conditionals in the `build` job to switch on
`runner.os` instead of `matrix.os` to match usage in the nightly repo.
See also …
=> Use updated GitHub Actions path file syntax

spinoso-symbol/src/ident.rs
This new technique is usable in const contexts whereas PartialEq is not.
=> Prefer slice destructuring instead of PartialEq comparison to empty slice and NUL

spinoso-random/src/random/mod.rs, spinoso-random/src/random/ruby/mod.rs
Previously, printing a `spinoso_random::Random` with the debug format specifier would output something like:
```
---- random::tests::fmt_debug_does_not_leak_seed stdout ----
thread 'random::tests::fmt_debug_does_not_leak_seed' panicked at 'Random { mt: Mt {}, seed: [123456, 0, 0, 0] }', spinoso-random/src/random/mod.rs:325:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
random::tests::fmt_debug_does_not_leak_seed
```
which leaks the internal seed.
It is typical for PRNGs to hide internal state in `fmt::Debug` implementations.
This commit alters the debug repr of `Random` to print `Random {}` and enforces this behavior with a test.
=> Fix: Do not leak Random seed in fmt::Debug implementation in spinoso-random

spinoso-random/src/random/ruby/mod.rs
Enabled by the toolchain update to 1.47.0 see #874 which lifted the `AtMostLength32` restriction for standard trait impls on array types.
=> Derive Hash, PartialEq, Eq, PartialOrd, and Ord for mersenne twister struct

artichoke-backend/src/extn/core/array/array.rb
Revert Hash#compare_by_identity RuboCop fix from Artichoke::Array::reachable?
introduced in 13a1fb945abe08119348b78addc6796914830d8b. Hash#compare_by_identity
is not implemented, which made Array#inspect raise an exception.
```
$ cargo run -q --bin airb
artichoke 0.1.0-pre.0 (2020-11-08 revision 3708) [x86_64-apple-darwin]
[rustc 1.47.0 (18bf6b4f0 2020-10-07)]
>>> [1,2,3]
=>
>>> a = [1,2,3]
=>
>>> a.inspect
Traceback (most recent call last):
3: from (airb):3
2: from (eval):927:in inspect
1: from (eval):9:in reachable?
NoMethodError (undefined method 'compare_by_identity')
>>>
```
```
$ cargo run -q --bin airb
artichoke 0.1.0-pre.0 (2020-11-08 revision 3708) [x86_64-apple-darwin]
[rustc 1.47.0 (18bf6b4f0 2020-10-07)]
>>> [1,2,3]
=> [1, 2, 3]
>>> a = [1,2,3]
=> [1, 2, 3]
>>> a.inspect
=> …
```
=> Fix Array#inspect implementation

artichoke-backend/vendor/mruby/src/vm.c
Fixes array destructing. Currently, arrays are unreachable because OP_APOST uses the wrong function to create them. Artichoke expects arrays to be rust internals instead of `mrb_array` (`MRB_TT_ARRAY`).
It fixes #789.
=> Fix array destructing

.github/workflows/ci.yaml
- Use native PowerShell cmdlets e.g. `Invoke-WebRequest`,
`Expand-Archive`.
- Use PowerShell cmdlets for generating temp files and zip extraction
paths instead of hardcoding destinations in the Artichoke checkout
workspace.
- Factor artifact URL to an env variable for readability
- Collapse 'Check bison' build steps to one step that executes a bash script
I spun up a local Windows VM to get this right. Revives and fixes https://github.com/artichoke/artichoke/pull/912.
=> Refactor `win_flex_bison` installation PowerShell in ci workflow

Cargo.toml, artichoke-backend/Cargo.toml, artichoke-core/Cargo.toml, spec-runner/Cargo.toml, spinoso-math/Cargo.toml, spinoso-random/Cargo.toml
Enable docsrs cfg for access to nightly rustdoc features.
=> Sync package.metadata.docs.rs section to all workspace Cargo.toml files

.github/workflows/ci.yaml, clippy.toml, spinoso-random/Cargo.toml, spinoso-random/src/lib.rs, spinoso-random/src/random/mod.rs, spinoso-random/src/random/ruby/mod.rs
Add a `clippy.toml` configuration file and add permitted idents to
`doc-valid-idents`.
This PR renames the `rand_core` feature in `spinoso-random` to `rand-core` (with hyphen). This stylizes the feature to match other multi-word crate features in this workspace and avoids adding `rand_core` to the permitted idents list (because as a crate name, `rand_core` should be surrounded by backticks).
=> Stop disabling clippy::doc_markdown lint

artichoke-backend/src/extn/core/array/args.rs, artichoke-backend/src/extn/core/integer/mod.rs, artichoke-backend/src/extn/core/kernel/integer.rs, artichoke-backend/src/extn/core/matchdata/mod.rs, artichoke-backend/src/extn/core/math/trampoline.rs, artichoke-backend/src/extn/core/regexp/mod.rs, artichoke-backend/src/string.rs, artichoke-backend/src/sys/mod.rs
Remove `string::format_int_into` and replace call sites with direct
calls to `itoa::fmt`.
`string::format_int_into` was a minimal wrapper around `itoa::fmt` that
only mapped the error type. It introduced a function call overhead for
minimal abstraction. There are only a handful of calls to this function,
so replace them with the one-liner implementation.
Some calls immediately unwrapped the inner `fmt::Error`. These calls
have been simplified to only `itoa::fmt(f, num)`.
=> Replace string::format_int_into with direct usage of itoa::fmt

artichoke-backend/src/eval.rs, artichoke-backend/src/fs/memory.rs, artichoke-backend/src/lib.rs, artichoke-backend/src/load.rs, artichoke-core/src/lib.rs, scolapasta-hex/src/lib.rs, scolapasta-string-escape/src/lib.rs, spec-runner/src/main.rs, spinoso-array/src/lib.rs, spinoso-env/src/lib.rs, spinoso-exception/src/lib.rs, spinoso-math/src/lib.rs, spinoso-random/src/lib.rs, spinoso-securerandom/src/lib.rs, spinoso-symbol/src/lib.rs, spinoso-time/src/lib.rs, src/lib.rs, src/ruby.rs
Enable `clippy:needless_borrow` lint to check for unnecessary references
that are immediately dereferenced by the compiler.
I first asked about this in rust-lang/rust-clippy#4271 but never got
around to enabling it.
This lint is in the nursery lint group, so explicitly activate it in all
`lib.rs` sources for all workspace crates.
This lint caught a few needless borrows in `artichoke-backend`'s
interpreter infrastructure and `artichoke`'s Ruby CLI.
=> Enable clippy::needless_borrow lint

Cargo.toml, src/lib.rs
The `artichoke` crate is the public frontend to the Artichoke
interpreter. It exposes a top-level `artichoke::interpreter` function
that constructs an interpreter with all of the correct metadata that is
generated from its `build.rs` script. For these reasons, `artichoke` is
useful as a library crate.
The `artichoke` crate also exposes two executables: `artichoke` and
`airb`. These exceutables depend on platform-specific libraries like
`termcolor` and `rustyline` as well as unneeded dependencies in a lib
setting like `clap` and `structopt`.
The inclusion of `nix` via `rustyline` prevents the `artichoke` crate
from compiling on the `wasm32-unknown-emscripten` target even though the
readline binary frontend is not used. `wasm32-unknown-emscripten` is not
a supported platform in any tier for …
=> Allow building artichoke crate without CLI for lib targets

Cargo.lock, artichoke-backend/Cargo.toml, fuzz/Cargo.lock, spec-runner/Cargo.lock, spinoso-array/Cargo.toml, spinoso-array/src/array/vec/mod.rs
Add `Array::from_raw_parts` and `Array::into_raw_parts` APIs to the
`Vec`-based `Array` type in `spinoso-array`.
These APIs may be used to turn an `Array` into a raw pointer that can
later be reconstructed to an `Array`. These APIs are highly unsafe and
calling these APIs moves ownership of the underlying allocation.
These APIs are most useful in FFI contexts and are being introduced to
prepare for fixing GH-922.
Both `from_raw_parts` and `into_raw_parts` are marked must use to force
callers to acknowledge drop/leak intent with a wildcard binding.
The corresponding raw parts APIs cannot be added to the `SmallArray`
type because its internal `SmallVec` can only soundly be decomposed into
a raw parts triple when the storage is spilled to a `Vec`. This would
force users of `SmallArray` to …
=> Add raw parts APIs to spinoso_array::Array

artichoke-backend/src/class.rs
The fuzz GitHub Actions workflow found a small memory leak:
https://github.com/artichoke/artichoke/runs/1469791093?check_suite_focus=true
This leak was intentionally introduced in #927 to allow the
`BoxUnboxVmValue` implementation for `HeapAllocatedData` to pass the
data type to `mrb_data_object_alloc` without holding a borrow on the
interpreter so the mruby API call could be wrapped in
`Artichoke::with_ffi_boundary`.
This leak to raw `*mut sys::mrb_data_type` is not necessary:
- `mrb_data_type`s can be safely cloned.
- It is safe to reference a cloned `free` function or `&CStr` name.
- `mrb_data_object_alloc` only takes `*const sys::mrb_data_type`.
These three factors allow implementing `class::Spec::data_type` in safe
code without ever leaking the `mrb_data_type`.
=> Avoid leaking sys::mrb_data_type on class::Spec construction

artichoke-backend/src/class.rs, artichoke-backend/src/def.rs, artichoke-backend/src/module.rs
Calling `spec.clone()` and using this cloned spec to initialize objects
with `sys::mrb_data_object_alloc` is unsafe if the cloned spec is
dropped before the interpreter is closed because a `dfree` function
pointer associated with an `mrb_data_type` may be deallocated before
the object is collected.
This commit reworks the `EnclosingRubyScope` to store the components of
the class and module specs it requires, which does not include the
`mrb_data_type`.
This refactor was made easier by #793 which moved the
`EnclosingRubyScope` `Box` to the `EnclosingRubyScope` fields that
require it instead of boxing in the specs.
=> Remove Clone derive on class and module specs

artichoke-backend/src/convert/fixnum.rs, artichoke-backend/src/ffi.rs, artichoke-backend/src/sys/mod.rs, artichoke-backend/src/test/prelude.rs, artichoke-backend/src/value.rs
None of the unit tests (`#[test]` in `cfg(test)` blocks) in the
`artichoke-backend` crate call `Artichoke::close`, which means every
test that creates an interpreter via `interpreter().unwrap()` leaks
memory.
This makes running the tests with LeakSanitizer fail:
```shell
RUSTFLAGS="-Z sanitizer=leak" cargo +nightly test --target x86_64-apple-darwin -p artichoke-backend --lib
```
This commit exports a new `interpreter` function from the `test::prelude`
which wraps the `Artichoke` in a struct that derefs and deref muts to
`Artichoke` and has a custom `Drop` implementation which closes the
interpreter.
Some tests had to be modified to manually deref in cases where the
compiler could not insert auto-derefs.
Some FFI-oriented tests had to be modified to use `crate::interpreter`
directly for …
=> Modify artichoke-backend test harness to pass LeakSanitizer

README.md
- Add `alt` fields to embedded logo and playground HTML images.
- Update `artichoke` binary usage to note that Artichoke can `require`,
`require_relative`, and `load` sources from the host filesystem.
- Clarify that license details are noted in other crates in the
*workspace*.
- Update file an issue link to point to GitHub's new issue template
form.
=> Quality tweaks to the README

artichoke-backend/src/extn/stdlib/securerandom/trampoline.rs, spinoso-securerandom/src/lib.rs
`SecureRandom::random_bytes` returns 16 bytes by default if given a
`nil` length. Add a test that asserts the constant used in
`spinoso-secursecurerandom` is set correctly.
`SecureRandom::random_bytes` converts its argument using
`Object#to_int`. Add a comment documenting this to the `SecureRandom`
trampoline in `artichoke-backend`.
https://github.com/ruby/ruby/blob/v2_6_3/lib/securerandom.rb#L135
=> Add tests and documentation for default bytes returned by SecureRandom

scolapasta-string-escape/src/literal.rs, spinoso-symbol/src/inspect.rs
Reduce the size of `spinoso_symbol::Inspect` from 152 bytes to 136
bytes. This commit contains optimizations and code quality and
readability improvements:
- Change `scolapasta_string_escape::Literal` to wrap a byte slice
iterator instead of a `Chars` iterator. `Literal` only ever yields
ASCII characters, so this change removes the overhead of decoding
codepoints from the underlying slice.
- Implement `Default` for `scolapasta_string_escape::Literal` such that
it yields the empty string.
- Remove the `string` field of the source byte slice from `Inspect`'s
inner `State` struct. `bstr::CharIndices` has a
`CharIndices::as_bytes` method that gives access to the remaining
slice. This change required reworking the subslice indexing slightly.
- Collapse `is_ident`, `leading_colon_sigil`, …
=> Reduce size of spinoso_symbol::Inspect iterator

spinoso-symbol/Cargo.toml, spinoso-symbol/src/ident.rs
- Use `ByteSlice::chars` when only checking for case properties of valid
UTF-8 characters.
- Use `bstr::decode_utf8` in local/constant ident parsing routines.
- Add tests for `is_special_global_name`.
- Add tests for `is_ident_until`.
- Add tests for `is_next_ident_exhausting`.
Similar to #953.
=> Remove uses of bstr::CharIndices from spinoso-symbol ident parser

artichoke-backend/src/eval.rs, artichoke-backend/src/extn/core/kernel/require.rs, artichoke-backend/src/fs.rs, artichoke-backend/src/fs/hybrid.rs, artichoke-backend/src/fs/memory.rs, artichoke-backend/src/fs/native.rs, artichoke-backend/src/state/mod.rs, spec-runner/src/mspec.rs
This PR removes the `Filesystem` trait from `artichoke_backend::fs`. This trait is a holdover from long ago when Artichoke depended on the `filesystem` crate (https://github.com/artichoke/ferrocarril/pull/1!).
This significant refactor of the `fs` module follows the same approach I've been using in the Spinoso crates: make multiple backends that are source compatible so they can be swapped out with Cargo feature flags.
This change introduces three `fs` backends:
- `Memory`: an in-memory backend that stores file contents in a `HashMap` and uses a `HashSet` to track `$LOADED_FEATURES`. `Memory` filesystems support storing extension hooks, which are used to initialize gems in Artichoke.
- `Native`: a host filesystem adapter that stores and reads file contents from local disk and uses a …
=> Remove trait objects from the artichoke-backend virtual filesystem
