artichoke/artichoke

- .circleci/config.yml
- package.json
- scripts/format-c.sh
- scripts/format-text.sh
- scripts/lint.sh
- webpack.config.js
- yarn.lock
This is the first step to folding https://github.com/artichoke/logo into this repo and getting a proper build for static assets. Maybe building an index page for https://artichoke.github.io/artichoke/?
> Improve text linting and add a webpack config

- README.md
- artichoke-wasm/src/index.html
- artichoke-wasm/src/playground.js
- Prepopulate the playground editor with sample code.
- Add a documentation index to the playground navbar.
- Link to the playground in the repo README.
> WASM Playground Polish

- artichoke-wasm/src/playground.js
Fixes GH-50.
Make a wrapper around Set using Forwardable. Requires two packages from
stdlib.
> Make the playground example more interesting

- package.json
- scripts/spec-compliance.sh
Avoid recompilation of workspace in spec-compliance.sh
> Build speed up spec runner

- .circleci/config.yml
- .eslintignore
- artichoke-wasm/.eslintrc.json
- artichoke-wasm/src/index.html
- artichoke-wasm/src/playground.js
- package.json
- scripts/lint.sh
- yarn.lock
In `scripts/lint.sh` and CI.
Fixes GH-52.
> Lint JS and HTML with eslint

- README.md
https://github.com/artichoke/artichoke/milestone/7
[HN feedback](https://news.ycombinator.com/item?id=20604119) showed me how important this is. We'll try our best to make it happen. 😄 💎
> Move MRI C API from non-goal to goal

- README.md
> Update README to target full compatibility with MRI

- CONTRIBUTING.md
- README.md
> Add Discord invite link to README and CONTRIBUTING

- README.md
Replace all of the milestone links with links to area labels.
Fixes GH-133.
Fixes GH-102.
> Reframe README in terms of Artichoke's architecture

- .circleci/config.yml
- artichoke-backend/build.rs
- artichoke-backend/scripts/auto_import/get_package_files.rb
- artichoke-backend/src/extn/stdlib/mod.rs
- artichoke-backend/src/extn/stdlib/uri.rs
Generate sources for as many standard lib packages as possible as part of artichoke-backend build. See GH-12.
cc @johnwahba
> Generate sources stdlib packages

- artichoke-backend/src/extn/core/comparable/comparable.rb
- artichoke-backend/src/extn/core/comparable/mod.rs
- artichoke-backend/src/extn/core/mod.rs
- doc/ruby-spec.md
- mruby-sys/build.rs
- scripts/spec-compliance.sh
> Add spec-compliant Comparable implementation to Core

- artichoke-backend/src/extn/core/enumerable/enumerable.rb
> Reduce complexity of Enumerable#drop_while and Enumerable#group_by

- CONTRIBUTING.md
- README.md
> Fix capitalization in E-easy label

- artichoke-backend/src/extn/core/mod.rs
- artichoke-backend/src/extn/core/symbol/mod.rs
- artichoke-backend/src/extn/core/symbol/symbol.rb
- mruby-sys/build.rs
Part of #32 to remove dependency on mruby-*-ext mrbgems.
> Remove dependency on mruby-symbol-ext

- artichoke-backend/src/extn/core/mod.rs
- artichoke-backend/src/extn/core/proc/mod.rs
- artichoke-backend/src/extn/core/proc/proc.rb
Part of #32 to remove dependency on mruby-*-ext mrbgems.
> Remove dependency on mruby-proc-ext

- CONTRIBUTING.md
- README.md
- doc/build.md
> Add docs on how to build

- artichoke-backend/src/extn/core/string/scan.rs
> Remove explicit GC disable in String#scan

- Cargo.lock
- artichoke-backend/Cargo.toml
- artichoke-backend/build.rs
Build packages in parallel rather than iteratively. This takes the build time on my laptop from 30 sec => 16 sec
> parallel ruby build for artichoke-backend

- artichoke-backend/src/extn/core/kernel/kernel.rb
- artichoke-backend/src/extn/core/mod.rs
- artichoke-backend/src/extn/core/object.rb
- artichoke-backend/src/extn/core/object/mod.rs
- artichoke-backend/src/extn/core/object/object.rb
- mruby-sys/build.rs
Part of #32 to remove dependency on mruby-*-ext mrbgems.
> Remove dependency on mruby-object-ext

- artichoke-backend/src/extn/core/env/env.rb
- artichoke-backend/src/extn/core/env/mod.rs
@lopopolo I had come back from vacation and fixed your remarks (from [this](https://github.com/artichoke/artichoke/issues/156#issuecomment-521088939) comment).
> #156 implement rest env api in ruby

- README.md
The playground is our best piece of marketing. Make it stand out.
> Add a screenshot of the playground to the README

- artichoke-backend/src/eval.rs
- artichoke-backend/src/value.rs
Implement `Protect` as a `Copy` struct for `Eval::eval` and `ValueLike::funcall` in `artichoke-backend`.
This ensures that no memory leaks as we unwind during a raised Ruby `Exception`. It also has the benefit of removing some allocations.
This PR unifies the `Protect::run` implementation for `ValueLike::funcall` and `ValueLike::funcall_with_block`. This is the first step to implementing `Value` in `artichoke-backend` with the trait in `artichoke-core`.
> Improve safety of Protect in Eval and ValueLike::funcall

- artichoke-backend/src/extn/core/env/env.rb
@lopopolo another small piece of changes
> #156 implement rest env api in ruby v2

- artichoke-backend/src/extn/core/range/range.rb
Fixes #207 
Still fail the following 1 spec.
https://github.com/artichoke/artichoke/blob/44f1e83473decc16332eb6632e87743032dee6ac/spec-runner/vendor/spec/core/range/shared/cover_and_include.rb#L22-L29
> Implement Range#cover? in Ruby

- artichoke-backend/src/extn/core/env/env.rb
@lopopolo Yet another piece of ENV object has been done
> #156 implement rest env api in ruby v3

- artichoke-backend/src/extn/core/range/range.rb
> Implement Range#last in Ruby

- artichoke-backend/src/extn/core/env/env.rb
@lopopolo the `reject!` was added. I hope I understood the method description correctly.
> #156 added reject! method

- artichoke-backend/src/extn/core/float/float.rb
- artichoke-backend/src/extn/core/float/mod.rs
- artichoke-backend/src/extn/core/mod.rs
- artichoke-backend/src/extn/core/object.rb
- artichoke-backend/src/extn/core/range/range.rb
> Implement Range#size

- artichoke-backend/build.rs
- artichoke-backend/src/extn/core/env/env.rb
- artichoke-backend/src/extn/core/float/float.rb
- artichoke-backend/src/extn/core/float/mod.rs
- artichoke-backend/src/extn/core/kernel/mod.rs
- artichoke-backend/src/extn/core/kernel/require.rs
- artichoke-backend/src/extn/core/mod.rs
- artichoke-backend/src/extn/core/object.rb
- artichoke-backend/src/extn/core/range/range.rb
- artichoke-core/src/file.rs
- artichoke-core/src/load.rs
- package.json
- scripts/format-text.sh
Adds in support for Ruby load function.
> Add load function

- scripts/format-c.sh
- scripts/format-text.sh
Cleanup to format-text.sh and format-c.sh.
> Formatter fixups

- artichoke-backend/src/extn/core/kernel/require.rs
load_impl had a Vec of file Paths that it looped over, despite only ever
trying one Path. This is a leftover from using require_impl as a base.
This commit removes the Vec and removes the for loop over it.
cc @Elang89
> Remove Vec from load_impl

- Cargo.lock
- artichoke-backend/Cargo.toml
cargo update + manually bumping versions for breaking changes to get to latest.
> Bump Cargo Dependencies

- artichoke-backend/src/extn/core/kernel/integer.rs
- artichoke-backend/src/extn/core/kernel/mod.rs
Clean up and implement remaining feedback from GH-293.
> Kernel#Integer cleanup

- artichoke-backend/src/convert/array.rs
- artichoke-backend/src/convert/nilable.rs
- artichoke-backend/src/convert/object.rs
Support extracting e.g. `Option<&[u8]>`.
> Add slice converters

- artichoke-frontend/src/bin/artichoke.rs
artichoke -e 'code' now accepts arguments containing invalid UTF-8
and evals them on the Artichoke interpreter.
$ ./target/debug/artichoke -e "$(echo -e "puts '\xFF'.inspect")"
"\xff"
Piping code to artichoke via stdin.
$ echo -e "puts '\xFF'.inspect" | ./target/debug/artichoke
"\xff"
> artichoke -e takes multiple OsStr arguments

- artichoke-backend/src/extn/core/string/scan.rs
- artichoke-frontend/src/bin/artichoke.rs
> >  I should be able to implement substring matching
> Out of curiosity, why not just use bstr's substring search, since it sounds like you are already depending on bstr?
_Originally posted by @BurntSushi in https://github.com/BurntSushi/rust-memchr/issues/61#issuecomment-544349809_
`bstr`'s twoway implementation has more optimizations than I could ever dream of implementing. I was turned of from trying it initially because of a slower experience using the `twoway` crate. bstr's twoway uses `memchr` and is faster than my handrolled memchr only implementation.
This PR also adds an option `--with-fixture` to the `artichoke` binary which loads a file into a global variable `$fixture`.
> Replace bespoke byte substring searcher with bstr

- artichoke-backend/vendor/mruby/src/backtrace.c
- artichoke-backend/vendor/mruby/src/class.c
- artichoke-backend/vendor/mruby/src/error.c
- artichoke-backend/vendor/mruby/src/kernel.c
- artichoke-backend/vendor/mruby/src/string.c
- artichoke-backend/vendor/mruby/src/vm.c
Just a little bit of UB and type confusion.
> Add missing indirection via Array access macros in mruby impl

- artichoke-backend/src/extn/core/kernel/kernel.rb
- artichoke-backend/src/extn/core/kernel/mod.rs
- artichoke-backend/src/extn/core/mod.rs
- artichoke-backend/src/extn/core/warning/mod.rs
- artichoke-backend/src/extn/core/warning/warning.rb
- artichoke-backend/src/warn.rs
> Split Warning out into its own core module

- artichoke-backend/src/extn/core/array/backend/buffer.rs
> Fix mutable borrow errors when cloning a buffer in Buffer::set_slice

- artichoke-backend/build.rs
- artichoke-backend/src/extn/core/enumerator/enumerator.rb
- artichoke-backend/src/extn/core/enumerator/lazy.rb
- artichoke-backend/src/extn/core/enumerator/mod.rs
- artichoke-backend/src/extn/core/mod.rs
> Remove dependency on mruby-enumerator and mruby-enum-lazy

- artichoke-backend/build.rs
- Thread target triple through to all build parts.
- Invoke minirake via ruby binary instead of via shebang.
- Disable auto importer on expect, pty, and syslog packages
which are not available on windows.
> Modify build.rs to build artichoke-backend under Windows

- artichoke-backend/src/extn/core/string/scan.rs
Do this before calling into the VM for implicit conversions.
> Attempt to unbox Regexp first in String#scan

- artichoke-backend/src/extn/core/env/backend/memory.rs
- artichoke-backend/src/extn/core/env/backend/system.rs
- artichoke-backend/src/extn/core/exception/mod.rs
- Store `RubyException` messages as byte strings.
- Check for NUL bytes before `=` when validating `ENV` names and values.
- Convert validation chains to one if-else statement.
- Include raw env name in EINVAL exception message.
> Improve compatability of ENV implementation

- artichoke-backend/src/class.rs
Refer to core types with their proper specs attached to the
interpreter.
Create real types instead of injecting ().
> Cleanup class spec tests

- .circleci/config.yml
- package.json
- yarn.lock
@artichoke-ci is a machine user that has push access.
> Build gh-pages branch with a machine user

- package.json
- yarn.lock
Reduce the surface area of JS dependencies to only those required for linting.
> Prune JS deps

- artichoke-frontend/README.md
- artichoke-frontend/src/bin/airb.rs
- artichoke-frontend/src/bin/artichoke.rs
- artichoke-frontend/src/bin/ruby.rs
- artichoke-frontend/src/lib.rs
- artichoke-frontend/src/ruby.rs
- spec-runner/src/main.rs
- airb
- artichoke
- ruby
- spec-runner
> Add top-level documentation for artichoke workspace binaries

- artichoke-backend/src/def.rs
These traits were unused after the refactor in GH-398.
> Remove ClassLike and Define traits in artichoke_backend::def

- artichoke-backend/src/extn/core/integer/mod.rs
I added a new operator and checked it with my own test code.
I also wanted to run spec, but the command in contributing guidelines didn't work like this: 
```sh
$ ruby scripts/spec.rb core array each
spec.rb runs ruby/specs against Artichoke and MRI.
Usage: scripts/spec.rb artichoke [ --timed ITERATIONS | --profile ] [ passing | family [ component [ spec ] ] ]
Usage: scripts/spec.rb ruby [ --timed ITERATIONS ] family [ component [ spec ] ]
Examples:
$ scripts/spec.rb artichoke passing
$ scripts/spec.rb artichoke core
$ scripts/spec.rb artichoke core string
$ scripts/spec.rb ruby core string scan
$ scripts/spec.rb artichoke --timed 30 core string scan
$ scripts/spec.rb artichoke --profile passing
```
Anything I did wrong or update for this tool?
> Add Integer::[] operator

- artichoke-backend/Cargo.toml
- artichoke-core/Cargo.toml
- artichoke-frontend/Cargo.toml
- artichoke-vfs/Cargo.toml
- spec-runner/Cargo.toml
https://rust-lang.github.io/rust-clippy/master/index.html#cargo_common_metadata
> Add cargo metadata

- artichoke-backend/src/convert/hash.rs
> Preallocate Vecs in Hash converters

- artichoke-backend/build.rs
I ran nightly clippy for investigating GH-453 and clippy lints build.rs
scipts now! :hooray:
This commit fixes lint errors up to clippy::pedantic.
This commit also introduces a build step to emit cargo:rerun-if-changed
lines for all files in:
- mruby bootstrap configuration
- mruby vendored include dir
- mruby vendored source dir
- mruby-sys extension dir
- ruby vendored lib dir
- auto_import script package
This commit simplifies the source detection logic in
`libmruby::staticlib`.
> Improve artichoke-backend build.rs script

- artichoke-backend/src/extn/core/array/mod.rs
Array implicitly converts variables to array in several places. This commit
propagates Exceptions from the funcalls these conversions make. This unnests
the code a bit and gets rid of some TODOs.
This PR was inspired by GH-442.
> Propagate exceptions during to_ary implicit conversion

- artichoke-backend/src/extn/mod.rs
> Remove unnecessary value conversion on interpreter boot

- Cargo.lock
- artichoke-backend/Cargo.toml
> Turn off default features of quickcheck

- README.md
- doc/artichoke-design-and-goals.md
- spec-runner/src/main.rs
Clean up language and dead links in design and goals doc
> Clean up dead VFS links and content

- .github/workflows/audit.yaml
- .github/workflows/rustdoc.yaml
- Add name to rustdoc job.
- Add name to cargo-deny job.
- Add yarn audit job to Audit workflow.
- Run Audit workflow on every push AND once a week.
> Update Github Actions workflows

- Cargo.lock
- deny.toml
> cargo update

- yarn.lock
> yarn upgrade to fix audit failure for acorn

- artichoke-backend/src/extn/core/regexp/backend/regex/utf8.rs
- artichoke-backend/src/extn/core/regexp/mod.rs
Use global variable APIs and refactor some logic for clarity.
Onig backend will come in a separate PR.
This work is related to GH-442.
> Refactor Utf8 Regexp backend to use global variable APIs

- artichoke-backend/src/extn/core/regexp/backend/onig.rs
Follow up to GH-556.
This work is related to Gh-442.
> Migrate onig Regexp backend to use global variable APIs

- yarn.lock
Fixes vulnerability advisiory https://github.com/advisories/GHSA-7fhm-mqm4-2wp7
> yarn upgrade to address CVE-2020-7598

- .github/markdown-link-check.json
- .github/workflows/fuzz.yaml
https://github.com/artichoke/artichoke/actions/runs/61397710
> Setup artichoke-backend build deps in fuzz workflow

- artichoke-backend/build.rs
- artichoke-backend/src/convert/hash.rs
- artichoke-backend/src/eval.rs
- artichoke-backend/src/extn/core/array/args.rs
- artichoke-backend/src/extn/core/kernel/mod.rs
- artichoke-backend/src/extn/core/kernel/require.rs
- artichoke-backend/src/extn/core/matchdata/element_reference.rs
- artichoke-backend/src/extn/core/regexp/backend/regex/mod.rs
- artichoke-backend/src/extn/core/regexp/opts.rs
- artichoke-backend/src/extn/core/thread.rs
- artichoke-backend/src/extn/stdlib/forwardable.rs
- artichoke-backend/src/fs.rs
- artichoke-backend/src/parser.rs
- artichoke-backend/src/sys/ffi_tests.rs
- artichoke-backend/src/sys/mod.rs
- artichoke-backend/src/value.rs
- spec-runner/src/mspec.rs
> Fix broken GitHub issue references in TODO comments

- Cargo.lock
- Cargo.toml
- deny.toml
https://github.com/mgeisler/version-sync/issues/84
> Update version-sync to 0.9

- artichoke-backend/src/extn/core/numeric/mod.rs
- Propagate internal exceptions from `Numeric#coerce` impls
- Propagate `"coerce must return [x, y]"` messages if received non-Array
- Propagate `"coerce must return [x, y]"` if received non assoc-Array
> Propagate exceptions raised from coerce implementations

- artichoke-backend/src/extn/core/kernel/trampoline.rs
- artichoke-backend/src/extn/core/regexp/enc.rs
- artichoke-backend/src/extn/core/regexp/opts.rs
- artichoke-backend/src/extn/core/string/trampoline.rs
- artichoke-backend/src/value.rs
Followup to Gh-630.
Required for GH-442.
> Remove interpreter field from Value

- artichoke-backend/src/extn/core/kernel/require.rs
Closes https://github.com/artichoke/artichoke/issues/477
I hope that this is the proper way to go about solving the issue
> Fix: load_error escaping invalid utf-8

- artichoke-backend/src/extn/core/regexp/backend/mod.rs
- artichoke-backend/src/extn/core/string/trampoline.rs
closes https://github.com/artichoke/artichoke/issues/616
> Implement ConvertMut for Scan

- artichoke-backend/src/extn/core/regexp/backend/onig.rs
- artichoke-backend/src/extn/core/regexp/backend/regex/utf8.rs
- artichoke-backend/src/extn/core/regexp/mod.rs
- artichoke-backend/src/state/mod.rs
- artichoke-backend/src/state/regexp.rs
> Extract active regexp globals into a standalone state component

- README.md
https://github.com/artichoke/docker-artichoke-nightly
Fixes GH-287.
> Add docker install instructions

- .prettierrc.yaml
- README.md
- Rakefile
- package.json
GH-287
https://github.com/artichoke/nightly/releases/latest
> Add install instructions for prebuilt nightlies

- .github/workflows/fuzz.yaml
- fuzz/Cargo.lock
- fuzz/fuzz_targets/eval.rs
Only run fuzzer if on the scheduled build because it takes 30 minutes.
This commit is expected to fail CI.
> Ensure fuzz targets build on master push and PR

- .github/workflows/ci.yaml
- .github/workflows/fuzz.yaml
- .github/workflows/rustdoc.yaml
See also https://github.com/artichoke/playground/pull/78
> GitHub actions cache rust deps

- Cargo.lock
- Cargo.toml
- artichoke-backend/Cargo.toml
- artichoke-backend/src/lib.rs
- artichoke-core/Cargo.toml
- artichoke-core/src/lib.rs
- src/lib.rs
Remove an unneeded dep that has begun to expand its scope beyond what this project requires.
> Replace doc-comment with an inline macro_rules macro

- artichoke-backend/src/extn/core/time/mruby.rs
- artichoke-backend/src/extn/core/time/trampoline.rs
This pull request _may_ solve issue #735 . I've also implemented the methods for the other weekdays, hope you don't mind. :)
> Implementation of Time's commodity methods

- artichoke-backend/src/extn/core/env/mruby.rs
- artichoke-backend/src/extn/core/env/trampoline.rs
- artichoke-backend/src/extn/core/kernel/integer.rs
- artichoke-backend/src/extn/core/kernel/require.rs
- artichoke-backend/src/extn/core/kernel/trampoline.rs
- artichoke-backend/src/extn/core/matchdata/mod.rs
- artichoke-backend/src/extn/core/regexp/mod.rs
- artichoke-backend/src/extn/core/regexp/trampoline.rs
- artichoke-backend/src/value.rs
Work toward removing this `unsafe`:
https://twitter.com/artichokeruby/status/1280118990379945984?s=20
Introduced in GH-730.
> Remove unwrap from Value::implicitly_convert_to_string

- artichoke-backend/src/block.rs
- artichoke-backend/src/class.rs
- artichoke-backend/src/def.rs
- artichoke-backend/src/exception.rs
- artichoke-backend/src/extn/core/env/backend/mod.rs
- artichoke-backend/src/extn/core/exception/mod.rs
- artichoke-backend/src/extn/core/kernel/integer.rs
- artichoke-backend/src/extn/core/math/mod.rs
- artichoke-backend/src/extn/core/regexp/backend/mod.rs
- artichoke-backend/src/extn/core/regexp/enc.rs
- artichoke-backend/src/extn/core/regexp/opts.rs
- artichoke-backend/src/ffi.rs
- artichoke-backend/src/gc/arena.rs
- artichoke-backend/src/interpreter.rs
- artichoke-backend/src/method.rs
- artichoke-backend/src/module.rs
- artichoke-backend/src/string.rs
- artichoke-backend/src/sys/mod.rs
- artichoke-backend/src/value.rs
- artichoke-core/src/types.rs
- src/repl.rs
some improvements to string formatting code.
> Use Formatter::write_str where possible

- Cargo.lock
- Gemfile.lock
- spec-runner/src/spec_runner.rb
> Bump rubocop 0.88

- artichoke-backend/src/extn/core/symbol/mod.rs
- artichoke-backend/src/extn/core/symbol/mruby.rs
- artichoke-backend/src/extn/core/symbol/trampoline.rs
Progress on #725
Are tests necessary? if so, where should i create them?
> Implement Symbol#inspect

- .github/labels.json
> Re-generate missing A-compiler label

- spinoso-symbol/src/inspect.rs
The existing iterator escapes " (double quote) with a backslash, but does
not escape the escape character.
Add state, cases to the match arms, and tests. Spot checked airb vs irb.
Followup to and bugfix for GH-787.
> Escape \ (backslash) in Symbol#inspect for non-ident Symbols

- artichoke-backend/src/extn/core/range/range.rb
- Convert arg if civen to to Integer with #to_int.
- Raise appropriate TypeErrors.
- Simplify implementation to use each and take.
> Improve Range#first implementation

- .github/workflows/audit.yaml
- .github/workflows/ci.yaml
- .github/workflows/fuzz.yaml
- .github/workflows/repo-labels.yaml
- .github/workflows/rustdoc.yaml
- .prettierrc.yaml
- .rubocop.yml
- .yamllint.yaml
> Lint YAML with yamllint

- .github/workflows/block-merge.yaml
See artichoke/project-infrastructure#44.
> Block WIP or unmergeable PRs

- spinoso-random/README.md
Fixup for https://github.com/artichoke/artichoke/pull/836
> Fix broken links in spinoso-random README

- spinoso-random/src/lib.rs
Fixup for https://github.com/artichoke/artichoke/pull/836
> Impl std::error::Error for spinoso_random::Error

- artichoke-backend/src/extn/core/math/trampoline.rs
Use map_err and a match statement for clarity and denser code.
> Refactor math::trampoline::ldexp exponent integer conversion

- artichoke-backend/src/extn/core/regexp/backend/onig.rs
Unnest, use explicit for loops for readability.
> Simplify uses of foreach_name in Onig Regexp backend

- spec-runner/src/mspec.rs
> Ensure spec-runner tests pass when running with LeakSanitizer

- spinoso-symbol/src/inspect.rs
Reimplement `spinoso_symbol::Inspect` to use `bstr::decode_utf8` and
`bstr::decode_last_utf8` instead of `bstr::CharIndices`. This reduces
the size of `spinoso_symbol::Inspect` from 136 bytes to 120 bytes.
Despite the APIs used being lower level, the code size doesn't increase
and the match arms are a bit more obvious in that they don't need
comments explaining what they do and why they are implemented the way
they are. The match arms also remove a special branch for the Unicode
replacement character which is likely to be fairly cold.
I learned about the [`bstr::decode_utf8`] and [`bstr::decode_last_utf8`] in
this discussion on an upstream issue: https://github.com/BurntSushi/bstr/issues/12#issuecomment-744470786.
Thanks @BurntSushi!
[`bstr::decode_utf8`]: …
> Reimplement spinoso_symbol::Inspect to use raw bstr decode UTF-8 APIs

- artichoke-backend/src/extn/core/string/trampoline.rs
Reimplement `String#ord` in the artichoke-backend string trampoline to
use `bstr::decode_utf8` instead of `bstr::ByteSlice::char_indices`.
This fixes a bug where `String`s that began with the Unicode replacement
character did not return 65,533.
This change also properly raises `ArgumentError` with message "invalid byte
sequence in UTF-8" when the `String` begins with an invalid UTF-8 byte
sequence. This change assumes that all Artichoke `String`s implicitly have
UTF-8 encoding. Work is underway on `spinoso-string` which explicitly
tags `String`s with either UTF-8, ASCII, or binary encoding.
This commit updates the link to the `char` converter source in
rust-lang/rust to 1.48.0, which accounts for the source directory layout
changes that took place since the link was generated with the …
> Simplify implementation of String#ord
